-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom item definitions here

cloneObject{
	name= "chitin_gloves",
	baseObject = "leather_gloves",
	uiName = "Chitin Gloves",
	model = "mod_assets/models/chitin_gloves.fbx",
	slot = "Gauntlets",
	armorSkill = "light_armor",
	armorSet = "chitin",
	gfxAtlas = "mod_assets/textures/chitin_items.tga",
	gfxIndex = 0,
	protection = 9,
	weight = 1.5,
	description = "These modified gloves have heavy bug carcasses on them. Ew.",

}