-- This file has been generated by Dungeon Editor 1.3.1

-- TODO: place your custom item definitions here


cloneObject {
	name = "hint_book",
	baseObject = "scroll",
	uiName = "Cluebook",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 33,
	model = "mod_assets/models/items/cluebook.fbx",
	weight = 1.0,
}

cloneObject {
	name = "bestiary",
	baseObject = "scroll",
	uiName = "The Bestiary",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 33,
	model = "mod_assets/models/items/cluebook.fbx",
	weight = 0.2,
	onUseItem = function(self,champion)
		return bestiaryTracker.flipPage(self)
	end,
}

cloneObject {
	name = "sword_silver",
	baseObject = "long_sword",
	uiName = "Silversword",
	description = "Lighter than a standard Longsword, the blade yet feels sharp and deadly.",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 0,
	glitterEffect = "glitter_silver",
	model = "mod_assets/models/items/sword_silver.fbx",
	requiredLevel = 5,
	attackPower = 21,
	accuracy = 5,
	coolDownTime = 3.0,
	weight = 2.8,	
}

cloneObject {
	name = "spectral_blade",
	baseObject = "long_sword",
	uiName = "Spectral Blade",
	description = "This obsidian blade seems to hold all light, yet shimmers with strange reflections when glanced at from certain angles, like if it was folding onto itself.",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 32,
	glitterEffect = "glitter_silver",
	model = "mod_assets/models/items/blackblade.fbx",
	attackPower = 14,
	accuracy = 2,
	coolDownTime = 3.0,
	weight = 2.8,	
}

fw_defineObject {
	name = "iron_bracelet",
	uiName = "Iron Bracelet",
	class = "Item",
	model = "assets/models/items/brace_fortitude.fbx",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 1,
	slot = "Bracers",
	description = "The material remains cold to the touch, and heavier than it appears. You feel you should hold on to it.",
	protection = 2,
	resistCold = 10,
	weight = 0.6,
}

cloneObject {
	name = "redguard_shield",
	baseObject = "legionary_shield",
	uiName = "Redguard Shield",
	model = "mod_assets/models/items/redguard_shield.fbx",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 2,
	evasion = 8,
	resistFire = 10,
	description = "The deadly Redguards, keepers of the halls of Ku-Dhaar, bear his mark.",
}

fw_defineObject{
	name = "skeleton_remains",
	class = "Item",
	uiName = "Remains",
	description = "Long ago decayed remains of a fellow adventurer. You should leave them rest in peace.",
	model = "assets/models/items/remains_of_toorum.fbx",
	gfxIndex = 212,
	weight = 5.0,
}

cloneObject {
	name = "rusted_long_sword",
	baseObject = "long_sword",
	uiName = "Rusted Sword",
	model = "mod_assets/models/items/rusted_sword.fbx",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 3,
	attackPower = 10,
	accuracy = -5,
	description = "This blade has seen better days. Its dull blade will not be of much use.",
}

cloneObject{
	name = "rusted_mail",
	baseObject = "ring_mail",
	uiName = "Rusted Mail",
	model = "mod_assets/models/items/rusted_ringmail.fbx",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 4,
	protection = 4,
	evasion = -5,
	weight = 10.0,
	description = "The corroded chain and loose rings offer inferior protection.",
}

cloneObject{
	name = "rusted_greaves",
	baseObject = "ring_greaves",
	uiName = "Rusted Greaves",
	model = "mod_assets/models/items/rusted_ring_greaves.fbx",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 5,
	protection = 4,
	evasion = -5,
	weight = 7.0,
	description = "The corroded chain and loose rings offer inferior protection.",
}

cloneObject{
	name = "rusted_gauntlets",
	baseObject = "ring_gauntlets",
	uiName = "Rusted Gauntlets",
	model = "mod_assets/models/items/rusted_ring_gauntlets.fbx",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 6,
	protection = 3,
	evasion = -5,
	description = "These rusted gauntlets are uncomfortable and offer little protection.",
}

cloneObject{
	name = "rusted_helm",
	baseObject = "iron_basinet",
	uiName = "Rusted Helm",
	model = "mod_assets/models/items/rusted_helm.fbx",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 7,
	protection = 4,
	evasion = -5,
	description = "This old helm barely holds together and will not deflect many more blows before it breaks.",
}

cloneObject{
	name = "rusted_axe",
	baseObject = "battle_axe",
	uiName = "Rusted Axe",
	model = "mod_assets/models/items/rusted_axe.fbx",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 8,
	attackPower = 14,
	accuracy = -5,
	description = "Devoured by rust and cracked, this axe can only do some minor blunt damage.",
}

cloneObject{
	name = "rusted_arrow",
	baseObject = "arrow",
	uiName = "Rusted Arrow",
	ammoType = "arrow",
	model = "mod_assets/models/items/rusted_arrow.fbx",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 9,
	attackPower = 1,
	sharpProjectile = true,
	description = "The arrowhead is rusted and fragile. It is still usable but not strong enough to bear an enchantment.",
}

cloneObject{
	name = "spectral_arrow",
	baseObject = "arrow",
	uiName = "Spectral Arrow",
	ammoType = "arrow",
	model = "mod_assets/models/items/rusted_arrow.fbx",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 9,
	attackPower = 1,
	sharpProjectile = true,
	description = "The obsidian arrowhead himmers with strange reflections, light yet dark.",
}

cloneObject{
	name = "rusted_mace",
	baseObject = "knoffer",
	uiName = "Rusted Mace",
	model = "mod_assets/models/items/rusted_mace.fbx",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 10,
	attackPower = 10,
	accuracy = -5,
	description = "This old and rusty mace is cumbersome and rather ineffective",
}

cloneObject{
	name = "plate_light",
	baseObject = "cuirass_valor",
	uiName = "Plate of Light",
	armorSet = "Light",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 14,
	dexterity = 1,
	vitality = 1,
	resistShock = 10,
	protection = 16,
	description = "Radiating with energy, forged from light, in this cuirass was the champion Tanriel clad. Almost invincible was she in her suit of white, yet by vile deceit did the demon Gotrakar take her life.",
	weight = 10.8,
	glitterEffect = "glitter_silver",
}

cloneObject{
	name = "greaves_light",
	baseObject = "greaves_valor",
	uiName = "Greaves of Light",
	armorSet = "Light",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 15,
	dexterity = 1,
	vitality = 1,
	resistShock = 5,
	protection = 16,
	description = "Shining even in the darkest shadow, these flexible greaves lent speed and protection to Tanriel. Blinded where her enemies as she thurst her sword, but yet she too her bane one day met.",
	weight = 7.7,
	glitterEffect = "glitter_silver",
}

cloneObject{
	name = "helm_light",
	baseObject = "helmet_valor",
	uiName = "Helm of Light",
	armorSet = "Light",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 16,
	dexterity = 1,
	vitality = 1,
	resistShock = 5,
	protection = 16,
	description = "Thunder left Tanriel unscathed as she fought her way through the storms. The helm radiated with light and showed her the way, yet the way led to darkness and for Tanriel to her death.",
	weight = 3.2,
	glitterEffect = "glitter_silver",
}

cloneObject{
	name = "boots_light",
	baseObject = "boots_valor",
	uiName = "Boots of Light",
	armorSet = "Light",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 17,
	dexterity = 1,
	vitality = 1,
	resistShock = 5,
	protection = 16,
	description = "Swift was Tanriel in her white boots, and swift was her white sword. Yet Gotrakar's heart was black and spelled her demise.",
	weight = 4.1,
	glitterEffect = "glitter_silver",
}

cloneObject{
	name = "gauntlets_light",
	baseObject = "gauntlets_valor",
	uiName = "Gauntlets of Light",
	armorSet = "Light",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 18,
	dexterity = 1,
	vitality = 1,
	resistShock = 5,
	protection = 16,
	description = "Her soft hands clad in white steel, Tanriel hold her weapon still. But the demon laughed at her elven grace and yet bent her to his will.",
	weight = 2.3,
	glitterEffect = "glitter_silver",
}

cloneObject{
	name = "shield_light",
	baseObject = "shield_valor",
	uiName = "Shield of Light",
	armorSet = "Light",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 19,
	dexterity = 1,
	vitality = 1,
	resistShock = 10,
	evasion	= 12,
	description = "In Tanriel's gleaming shield did the demon mirror his gaze. The white steel withheld the blows, yet against treachery she could not hold.",
	weight = 5.9,
	glitterEffect = "glitter_silver",
}

cloneObject{
	name = "ruby_key",
	baseObject = "gold_key",
	uiName = "Ruby Key",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 11,
}

cloneObject{
	name = "amethyst_key",
	baseObject = "gold_key",
	uiName = "Amethyst Key",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 12,
}

cloneObject{
	name = "emerald_key",
	baseObject = "gold_key",
	uiName = "Emerald Key",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 13,
}

cloneObject{
	name = "onyx_key",
	baseObject = "prison_key",
	uiName = "Onyx Key",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 36,
}

cloneObject{
	name = "crystal_key",
	baseObject = "prison_key",
	uiName = "Crystal Key",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 37,
}

fw_defineObject{
	name = "essence_air",
	class = "Item",
	uiName = "Essence of Air",
	model = "mod_assets/models/items/essence_air.fbx",
	description = "A miniature thunderstorm rages inside the orb, and you hear the howling of winds as you bring it to your ear.",
	skill = "spellcraft",
	requiredLevel = 5,
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 26,
	attackMethod = "castRuneSpell",
	willpower = 5,
	energy = 10,
	resistShock = 5,
	impactSound = "impact_blunt",
	weight = 2.5,
}

fw_defineObject{
	name = "essence_earth",
	class = "Item",
	uiName = "Essence of Earth",
	model = "mod_assets/models/items/essence_earth.fbx",
	description = "Images of mountains shimmer in the orb, tiny but yet so distant. The sphere rumbles slightly like an earthquake.",
	skill = "spellcraft",
	requiredLevel = 5,
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 27,
	attackMethod = "castRuneSpell",
	willpower = 5,
	energy = 10,
	resistPoison = 5,
	impactSound = "impact_blunt",
	weight = 2.5,
}

fw_defineObject{
	name = "essence_fire",
	class = "Item",
	uiName = "Essence of Fire",
	model = "mod_assets/models/items/essence_fire.fbx",
	description = "A blazing fire is consuming your gaze as you peer into the orb, crackling sounding in your mind.",
	skill = "spellcraft",
	requiredLevel = 5,
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 28,
	attackMethod = "castRuneSpell",
	willpower = 5,
	energy = 10,
	resistFire = 5,
	impactSound = "impact_blunt",
	weight = 2.5,
}

fw_defineObject{
	name = "essence_ice",
	class = "Item",
	uiName = "Essence of Air",
	model = "mod_assets/models/items/essence_ice.fbx",
	description = "The orb reveals a snowstorm on a desolate icy field. The surface is freezing to the touch.",
	skill = "spellcraft",
	requiredLevel = 5,
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 29,
	attackMethod = "castRuneSpell",
	willpower = 5,
	energy = 10,
	resistCold = 5,
	impactSound = "impact_blunt",
	weight = 2.5,
}

cloneObject{
	name = "enchanted_doublet",
	baseObject = "doublet",
	uiName = "Enchanted Doublet",
	model = "mod_assets/models/items/enchanted_clothes.fbx",
	description = "A fine cloth, weaved with magic.",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 30,
	protection = 3,
	willpower = 2,
	energy = 5,
}

cloneObject{
	name = "enchanted_hose",
	baseObject = "doublet",
	uiName = "Enchanted Hose",
	model = "mod_assets/models/items/enchanted_clothes.fbx",
	description = "A fine cloth, weaved with magic.",
	slot = "Legs",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 31,
	protection = 3,
	willpower = 2,
	energy = 5,
}

cloneObject{
	name = "frostbite_necklace_lesser",
	baseObject = "frostbite_necklace",
	uiName = "Lesser Frostbite Necklace",
	model = "assets/models/items/frostbite_necklace.fbx",
	description = "This necklace, made out of Ice Lizard teeth, freezes everything it lays on but feels warm to touch. Some teeth seem to have fallen out however.",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 35,
	resistCold = 25,
}

cloneObject{
	name = "frostbite_necklace_greater",
	baseObject = "frostbite_necklace",
	uiName = "Greater Frostbite Necklace",
	model = "assets/models/items/frostbite_necklace.fbx",
	description = "This necklace, made out of Ice Lizard teeth, freezes everything it lays on but feels warm to touch. A powerful enchantment also seems to have been laid on it, lending it a bluish glow.",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 36,
	resistCold = 75,
}

fw_defineObject{
	name = "amulet_light",
	class = "Item",
	uiName = "Amulet of Light",
	model = "assets/models/items/spirit_mirror_pendant.fbx",
	description = "The warm light of this amulet strengthens the will of its bearer. The elven champion Tanriel wore it boldly as she walked in the halls of the dead, and undead monsters recoiled at the sight of its glowing crystal.",
	slot = "Neck",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 38,
	weight = 0.2,
	willpower = 3,
	gameEffect = "50% chance to negate damage dealt by undead.",
}

fw_defineObject{
	name = "amulet_dark",
	class = "Item",
	uiName = "Amulet of Darkness",
	model = "assets/models/items/spirit_mirror_pendant.fbx",
	description = "Worn by Maalgor, Night-Captain of the lost city of Zyx, this amulet irradiates with unnatural energy. Its cold touch steels the body, but its aura of darkness weakens the soul.",
	slot = "Neck",
	gfxAtlas = "mod_assets/textures/gui/items.tga",
	gfxIndex = 39,
	weight = 0.2,
	strength = 4,
	vitality = 3,
	willpower = -3,
	gameEffect = "Light spells cannot be cast while a champion is wearing this amulet.",
}

import "mod_assets/scripts/tomes.lua"