-- This file has been generated by Dungeon Editor 1.3.1

-- TODO: place your custom material definitions here

defineMaterial{
	name = "temple_wall_mosaic_ku",
	diffuseMap = "mod_assets/textures/env/temple_mosaic_wall_ku_dif.tga",
	specularMap = "mod_assets/textures/env/temple_mosaic_wall_ku_spec.tga",
	normalMap = "mod_assets/textures/env/temple_mosaic_wall_all_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 30,
	depthBias = 0,
}

defineMaterial{
	name = "temple_mosaic_wall_dain",
	diffuseMap = "mod_assets/textures/env/temple_mosaic_wall_dain_dif.tga",
	specularMap = "mod_assets/textures/env/temple_mosaic_wall_dain_spec.tga",
	normalMap = "mod_assets/textures/env/temple_mosaic_wall_all_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 30,
	depthBias = 0,
}

defineMaterial{
	name = "temple_mosaic_wall_ros",
	diffuseMap = "mod_assets/textures/env/temple_mosaic_wall_ros_dif.tga",
	specularMap = "mod_assets/textures/env/temple_mosaic_wall_ros_spec.tga",
	normalMap = "mod_assets/textures/env/temple_mosaic_wall_all_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 30,
	depthBias = 0,
}

defineMaterial{
	name = "cavern_rock",
	diffuseMap = "mod_assets/textures/env/cavern_rock_dif.tga",
	specularMap = "mod_assets/textures/env/cavern_rock_spec.tga",
	normalMap = "mod_assets/textures/env/cavern_rock_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "cavern_floor",
	diffuseMap = "mod_assets/textures/env/cavern_floor_dif.tga",
	specularMap = "assets/textures/env/temple_floor_spec.tga",
	normalMap = "assets/textures/env/temple_floor_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 30,
	depthBias = 0,
}

defineMaterial{
	name = "skeleton_redguard",
	diffuseMap = "mod_assets/textures/monsters/skeleton_redguard_dif.tga",
	specularMap = "assets/textures/monsters/skeleton_warrior_spec.tga",
	normalMap = "assets/textures/monsters/skeleton_warrior_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 75,
	depthBias = 0,
}

defineMaterial{
	name = "skeleton_redguard_weapons",
	diffuseMap = "mod_assets/textures/monsters/skeleton_redguard_weapons_dif.tga",
	specularMap = "mod_assets/textures/monsters/skeleton_redguard_weapons_spec.tga",
	normalMap = "mod_assets/textures/monsters/skeleton_redguard_weapons_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 50,
	depthBias = 0,
}

defineMaterial{
	name = "sword_silver",
	diffuseMap = "mod_assets/textures/items/sword_silver_dif.tga",
	specularMap = "mod_assets/textures/items/sword_silver_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 55,
	depthBias = 0,
}

defineMaterial{
	name = "blackblade",
	diffuseMap = "mod_assets/textures/items/blackblade_dif.tga",
	specularMap = "mod_assets/textures/items/sword_silver_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 55,
	depthBias = 0,
}

defineMaterial{
	name = "cluebook",
	diffuseMap = "mod_assets/textures/items/cluebook_dif.tga",
	specularMap = "assets/textures/common/black.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "rusted_sword",
	diffuseMap = "mod_assets/textures/items/rusted_long_sword_dif.tga",
	specularMap = "mod_assets/textures/items/rusted_long_sword_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 35,
	depthBias = 0,
}

defineMaterial{
	name = "rusted_ringmail_01",
	diffuseMap = "mod_assets/textures/items/rusted_ringmail_01_dif.tga",
	specularMap = "mod_assets/textures/items/rusted_ringmail_01_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 15,
	depthBias = 0,
}

defineMaterial{
	name = "rusted_ringmail_02",
	diffuseMap = "mod_assets/textures/items/rusted_ringmail_02_dif.tga",
	specularMap = "mod_assets/textures/items/rusted_ringmail_02_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 15,
	depthBias = 0,
}

defineMaterial{
	name = "rusted_helm",
	diffuseMap = "mod_assets/textures/items/rusted_helm_dif.tga",
	specularMap = "mod_assets/textures/items/rusted_helm_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 15,
	depthBias = 0,
}

defineMaterial{
	name = "rusted_axe",
	diffuseMap = "mod_assets/textures/items/rusted_axe_dif.tga",
	specularMap = "mod_assets/textures/items/rusted_axe_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 35,
	depthBias = 0,
}

defineMaterial{
	name = "rusted_arrow",
	diffuseMap = "mod_assets/textures/items/rusted_arrow_dif.tga",
	specularMap = "mod_assets/textures/items/rusted_arrow_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 15,
	depthBias = 0,
}

defineMaterial{
	name = "rusted_mace",
	diffuseMap = "mod_assets/textures/items/rusted_mace_dif.tga",
	specularMap = "mod_assets/textures/items/rusted_mace_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 15,
	depthBias = 0,
}

defineMaterial{
	name = "temple_floor_ku",
	diffuseMap = "mod_assets/textures/env/temple_floor_ku_dif.tga",
	specularMap = "mod_assets/textures/env/temple_floor_ku_spec.tga",
	normalMap = "mod_assets/textures/env/temple_floor_all_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 30,
	depthBias = 0,
}

defineMaterial{
	name = "temple_floor_ku_02",
	diffuseMap = "mod_assets/textures/env/temple_floor_ku2_dif.tga",
	specularMap = "mod_assets/textures/env/temple_floor_ku_spec.tga",
	normalMap = "mod_assets/textures/env/temple_floor_all_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 30,
	depthBias = 0,
}

defineMaterial{
	name = "temple_floor_dain",
	diffuseMap = "mod_assets/textures/env/temple_floor_dain_dif.tga",
	specularMap = "mod_assets/textures/env/temple_floor_dain_spec.tga",
	normalMap = "mod_assets/textures/env/temple_floor_all_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 30,
	depthBias = 0,
}

defineMaterial{
	name = "temple_floor_dain_02",
	diffuseMap = "mod_assets/textures/env/temple_floor_dain2_dif.tga",
	specularMap = "mod_assets/textures/env/temple_floor_dain_spec.tga",
	normalMap = "mod_assets/textures/env/temple_floor_all_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 30,
	depthBias = 0,
}

defineMaterial{
	name = "temple_floor_ros",
	diffuseMap = "mod_assets/textures/env/temple_floor_ros_dif.tga",
	specularMap = "mod_assets/textures/env/temple_floor_ros_spec.tga",
	normalMap = "mod_assets/textures/env/temple_floor_all_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 30,
	depthBias = 0,
}

defineMaterial{
	name = "temple_floor_ros_02",
	diffuseMap = "mod_assets/textures/env/temple_floor_ros2_dif.tga",
	specularMap = "mod_assets/textures/env/temple_floor_ros_spec.tga",
	normalMap = "mod_assets/textures/env/temple_floor_all_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 30,
	depthBias = 0,
}

defineMaterial{
	name = "wall_ruby_keyhole",
	diffuseMap = "mod_assets/textures/env/wall_keyhole_ruby_dif.tga",
	specularMap = "assets/textures/env/wall_keyhole_golden_spec.tga",
	normalMap = "assets/textures/env/wall_keyhole_golden_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 85,
	depthBias = 0,
}

defineMaterial{
	name = "wall_amethyst_keyhole",
	diffuseMap = "mod_assets/textures/env/wall_keyhole_amethyst_dif.tga",
	specularMap = "assets/textures/env/wall_keyhole_golden_spec.tga",
	normalMap = "assets/textures/env/wall_keyhole_golden_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 85,
	depthBias = 0,
}

defineMaterial{
	name = "wall_emerald_keyhole",
	diffuseMap = "mod_assets/textures/env/wall_keyhole_emerald_dif.tga",
	specularMap = "assets/textures/env/wall_keyhole_golden_spec.tga",
	normalMap = "assets/textures/env/wall_keyhole_golden_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 85,
	depthBias = 0,
}

defineMaterial{
	name = "wall_keyhole_onyx",
	diffuseMap = "mod_assets/textures/env/wall_keyhole_onyx_dif.tga",
	specularMap = "mod_assets/textures/env/wall_keyhole_onyx_spec.tga",
	normalMap = "assets/textures/env/wall_keyhole_prison_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 60,
	depthBias = 0,
}

defineMaterial{
	name = "wall_keyhole_crystal",
	diffuseMap = "mod_assets/textures/env/wall_keyhole_crystal_dif.tga",
	specularMap = "mod_assets/textures/env/wall_keyhole_crystal_spec.tga",
	normalMap = "assets/textures/env/wall_keyhole_prison_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 50,
	depthBias = 0,
}

defineMaterial{
	name = "fire_drake",
	diffuseMap = "mod_assets/textures/monsters/fire_drake_dif.tga",
	specularMap = "mod_assets/textures/monsters/fire_drake_spec.tga",
	normalMap = "assets/textures/monsters/wyvern_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "goromorg_white",
	diffuseMap = "mod_assets/textures/monsters/goromorg_white_dif.tga",
	specularMap = "assets/textures/monsters/goromorg_spec.tga",
	normalMap = "assets/textures/monsters/goromorg_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "spider_great",
	diffuseMap = "mod_assets/textures/monsters/spider_great_dif.tga",
	specularMap = "mod_assets/textures/monsters/spider_great_spec.tga",
	normalMap = "assets/textures/monsters/spider_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}

defineMaterial{
	name = "spider_death",
	diffuseMap = "mod_assets/textures/monsters/death_spider_dif.tga",
	specularMap = "assets/textures/monsters/spider_spec.tga",
	normalMap = "assets/textures/monsters/spider_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}

defineMaterial{
	name = "gobelin_ku",
	diffuseMap = "mod_assets/textures/env/dungeon_gobelin_ku_dif.tga",
	specularMap = "mod_assets/textures/env/dungeon_gobelin_ku_spec.tga",
	normalMap = "assets/textures/env/dungeon_gobelin_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "gobelin_ku_torn",
	diffuseMap = "mod_assets/textures/env/dungeon_gobelin_ku_torn_dif.tga",
	specularMap = "mod_assets/textures/env/dungeon_gobelin_ku_torn_spec.tga",
	normalMap = "assets/textures/env/dungeon_gobelin_torn_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "gobelin_dain",
	diffuseMap = "mod_assets/textures/env/dungeon_gobelin_dain_dif.tga",
	specularMap = "mod_assets/textures/env/dungeon_gobelin_dain_spec.tga",
	normalMap = "assets/textures/env/dungeon_gobelin_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "gobelin_dain_torn",
	diffuseMap = "mod_assets/textures/env/dungeon_gobelin_dain_torn_dif.tga",
	specularMap = "mod_assets/textures/env/dungeon_gobelin_dain_torn_spec.tga",
	normalMap = "assets/textures/env/dungeon_gobelin_torn_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "gobelin_ros",
	diffuseMap = "mod_assets/textures/env/dungeon_gobelin_ros_dif.tga",
	specularMap = "mod_assets/textures/env/dungeon_gobelin_ros_spec.tga",
	normalMap = "assets/textures/env/dungeon_gobelin_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "gobelin_ros_torn",
	diffuseMap = "mod_assets/textures/env/dungeon_gobelin_ros_torn_dif.tga",
	specularMap = "mod_assets/textures/env/dungeon_gobelin_ros_torn_spec.tga",
	normalMap = "assets/textures/env/dungeon_gobelin_torn_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "third_circle_door_ku",
	diffuseMap = "mod_assets/textures/env/third_circle_door_ku_dif.tga",
	specularMap = "mod_assets/textures/env/third_circle_door_ku_spec.tga",
	normalMap = "mod_assets/textures/env/third_circle_door_all_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 35,
	depthBias = 0,
}

defineMaterial{
	name = "essence_air",
	diffuseMap = "mod_assets/textures/items/essence_air_dif.tga",
	specularMap = "mod_assets/textures/items/essence_all_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 70,
	depthBias = 0,
}

defineMaterial{
	name = "essence_earth",
	diffuseMap = "mod_assets/textures/items/essence_earth_dif.tga",
	specularMap = "mod_assets/textures/items/essence_all_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 70,
	depthBias = 0,
}

defineMaterial{
	name = "essence_fire",
	diffuseMap = "mod_assets/textures/items/essence_fire_dif.tga",
	specularMap = "mod_assets/textures/items/essence_all_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 70,
	depthBias = 0,
}

defineMaterial{
	name = "essence_ice",
	diffuseMap = "mod_assets/textures/items/essence_ice_dif.tga",
	specularMap = "mod_assets/textures/items/essence_all_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 70,
	depthBias = 0,
}

defineMaterial{
	name = "enchanted_clothes",
	diffuseMap = "mod_assets/textures/items/enchanted_doublet_dif.tga",
	specularMap = "assets/textures/items/blue_clothes_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}



defineMaterial{
	name = "drainage_tentacles_fire",
	diffuseMap = "mod_assets/textures/monsters/drain_tentacles_fire_dif.tga",
	specularMap = "mod_assets/textures/monsters/drain_tentacles_fire_spec.tga",
	normalMap = "assets/textures/monsters/drain_tentacles_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 35,
	depthBias = 0,
}




defineMaterial{
	name = "uggardian_frozen",
	diffuseMap = "mod_assets/textures/isgardian_textures/frozen_uggardian_dif.tga",
	doubleSided = true,
	lighting = false,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}

defineMaterial{
	name = "isgardian_plate",
	diffuseMap = "mod_assets/textures/isgardian_textures/isgardian_plate_dif.tga",
	specularMap ="mod_assets/textures/isgardian_textures/isgardian_plate_spec.tga",
	normalMap = "assets/textures/monsters/uggardian_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 60,
	depthBias = 0,
}

defineMaterial{
	name = "light_elemental",
	diffuseMap = "mod_assets/textures/monsters/light_elemental_dif.tga",
	specularMap = "assets/textures/monsters/wyvern_spec.tga",
	normalMap = "assets/textures/monsters/wyvern_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 70,
	depthBias = 0,
}




import "mod_assets/scripts/particles.lua"
