-- This file has been generated by Dungeon Editor 1.3.1

-- TODO: place your custom dungeon object definitions here

cloneObject {
	name = "zone_marker",
	baseObject = "script_entity",
	editorIcon = 104,
}

cloneObject {
	name = "onParty_marker",
	baseObject = "script_entity",
	editorIcon = 104,
}

cloneObject {
    name = "lock_ruby",
    baseObject = "lock_golden",
    model = "mod_assets/models/env/wall_lock_ruby.fbx",
}

cloneObject {
    name = "lock_amethyst",
    baseObject = "lock_golden",
    model = "mod_assets/models/env/wall_lock_amethyst.fbx",
}

cloneObject {
    name = "lock_emerald",
    baseObject = "lock_golden",
    model = "mod_assets/models/env/wall_lock_emerald.fbx",
}

cloneObject {
    name = "lock_onyx",
    baseObject = "lock_prison",
    model = "mod_assets/models/env/wall_lock_onyx.fbx",
}

cloneObject {
    name = "lock_crystal",
    baseObject = "lock_prison",
    model = "mod_assets/models/env/wall_lock_crystal.fbx",
}

cloneObject {
    name = "cavern_wall_grating",
    baseObject = "temple_wall_grating",
}

cloneObject {
    name = "cavern_pillar",
    baseObject = "temple_pillar",
}

defineObject{
	name = "cavern_wall",
	class = "Decoration",
	model = "mod_assets/models/env/cavern_wall.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}

cloneObject {
    name = "teleporter_rotator90",
    baseObject = "teleporter",
}

cloneObject {
    name = "teleporter_rotator180",
    baseObject = "teleporter",
}

cloneObject {
    name = "teleporter_rotator270",
    baseObject = "teleporter",
}

defineObject{
name = "red_tentacle_light",
class = "LightSource",
lightPosition = vec(0, -1, 0),
lightRange = 6,
lightColor = vec(1, 0.2, 0.1),
brightness = 40,
particleSystem = "fire",
castShadow = true,
placement = "floor",
editorIcon = 88,
}

defineObject{
name = "dark_square",
class = "LightSource",
lightPosition = vec(0, 1.4, 0),
lightRange = 2.6,
lightColor = vec(-1, -1, -1),
brightness = 200,
castShadow = false,
placement = "floor",
editorIcon = 88,
}

--general spell projectile object
defineObject{
   name = "spell_projectile",
   class = "Item",
   uiName = "Spell projectile",
   model = "mod_assets/models/spell_projectile_null.fbx",
   gfxIndex = 109,
   attackPower = 1,
   stackable = false,
   sharpProjectile = false,
   sharpProjectile = false,
   projectileRotationY = 0,
   weight = 0,   
}

cloneObject{
	name = "spectral_bolt",
	baseObject = "spell_projectile",
	uiName = "Spectral Bolt",
}

defineObject{
	name = "spectral_bolt_effect",
	--baseObject = "lightning_bolt",
	class = "ProjectileSpell",
	particleSystem = "spectral_bolt",
	hitParticleEffect = "spectral_bolt_hit",
	lightColor = vec(1, 0.9, 0.9),
	lightBrightness = 15,
	lightRange = 7,
	lightHitBrightness = 40,
	lightHitRange = 10,
	castShadow = true,
	launchSound = "lightning_bolt_launch",
	projectileSound = "lightning_bolt",
	hitSound = "lightning_bolt_hit",
	projectileSpeed = 10,
	attackPower = 0,
	damageType = "physical",
	--cameraShake = true,
	tags = { "spell" },
}

import "mod_assets/scripts/particles_and_teleporters.lua"
import "mod_assets/scripts/skeletons_impaled.lua"
import "mod_assets/scripts/ways_decorations.lua"
