-- This file has been generated by Dungeon Editor 1.3.1

-- TODO: place your custom sound definitions here

defineSound{
	name = "ice_uggardian_walk",
	filename = "assets/samples/magic/blob_01.wav",
	loop = false,
	volume = 0.3,
	minDistance = 1,
	maxDistance = 10,
}