-- This file has been generated by Dungeon Editor 1.3.1

-- TODO: place your custom spell definitions here

defineSpell{
      name = "spectral_bolt",
      uiName = "Spectral Bolt",
      skill = "spellcraft",
      level = 5,
      runes = "BH",
      manaCost = 15,
      description = "The mage creates a bolt of spectral energy that unerringly strikes one target.",
      onCast = function(caster,x,y,direction,skill)
         spectralTracker.castSpectralBolt(caster,x,y,direction,skill)
      end
   }
   

