-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom monster definitions here
cloneObject{
	name = "party",
	baseObject = "party",
	onAttack = function(nChampionID, hWeapon)	
	local nXAdjust = 0;
	local nYAdjust = 0;
	local hParty = findEntity("party");
	local tNPCObjects = {"npc_boatman"};
		
		--get the tile in front of the party
		if hParty.facing == 0 then
		nYAdjust = -1;
		
		elseif hParty.facing == 1 then
		nXAdjust = 1;
		
		elseif hParty.facing == 2 then
		nYAdjust = 1;
		
		elseif hParty.facing == 3 then
		nXAdjust = -1;
		
		end
		
		--check to ensure no NPCs are in front of the partyXXXXX	
		for hEntity in entitiesAt(hParty.level, hParty.x + nXAdjust, hParty.y + nYAdjust) do
			
			for nObjectID, sObject in pairs(tNPCObjects) do
				
				if hEntity.name == sObject then
				hudPrint("You cannot attack other characters.");
				return false
				end
				
			end
			
		end
		
	return true
	end,
}


defineObject{
	name = "npc_boatman",
	class = "Monster",
	model = "assets/models/monsters/goromorg.fbx",
	meshName = "goromorg_mesh",
	animations = {
		idle = "assets/animations/monsters/goromorg/goromorg_idle.fbx",
		moveForward = "assets/animations/monsters/goromorg/goromorg_walk.fbx",
		strafeLeft = "assets/animations/monsters/goromorg/goromorg_strafe_left.fbx",
		strafeRight = "assets/animations/monsters/goromorg/goromorg_strafe_right.fbx",
		turnLeft = "assets/animations/monsters/goromorg/goromorg_turn_left.fbx",
		turnRight = "assets/animations/monsters/goromorg/goromorg_turn_right.fbx",
		attack = "assets/animations/monsters/goromorg/goromorg_idle.fbx",--"assets/animations/monsters/goromorg/goromorg_attack.fbx",
		getHitFrontLeft = "assets/animations/monsters/goromorg/goromorg_get_hit_front_left.fbx",
		getHitFrontRight = "assets/animations/monsters/goromorg/goromorg_get_hit_front_right.fbx",
		getHitBack = "assets/animations/monsters/goromorg/goromorg_get_hit_back.fbx",
		getHitLeft = "assets/animations/monsters/goromorg/goromorg_get_hit_left.fbx",
		getHitRight = "assets/animations/monsters/goromorg/goromorg_get_hit_right.fbx",
		fall = "assets/animations/monsters/goromorg/goromorg_get_hit.fbx",
	},
	--attackAnimSpeed = 1.7,
	--moveAnimSpeed = 1.2,
	--turnAnimSpeed = 1.3,
	moveSound = "goromorg_walk",
	footstepSound = "goromorg_footstep",
	attackSound = "empty",
	hitSound = "goromorg_hit",
	dieSound = "goromorg_die",
	hitEffect = "hit_dust",
	capsuleHeight = 0.8,
	capsuleRadius = 0.25,
	collisionRadius = 0.8,
	health = 400,
	sight = 0,
	seeInvisible = true,
	allAroundSight = false,
	attackPower = 0,
	evasion = 25000,
	protection = 25000,
	rangedAttack = {},
	coolDown = {21600,21601},
	movementCoolDown = 7,
	exp = 0,	
	particleSystem = "goromorg_lantern",
	particleSystemNode = "light1",
	lightName = "light1",
	lightColor = vec(0.2, 1.0, 2.5),
	lightBrightness = 5,
	lightRange = 4.5,
	healthIncrement = 50,
	brain = "Melee",
}