-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom sound definitions here
defineSound{
    name = "empty",
    filename = "mod_assets/sounds/empty.wav",
    loop = false,
    volume = 0.0,
    minDistance = 1,
    maxDistance = 1,
}