-- This file has been generated by Dungeon Editor 1.3.6

--- level 1 ---

mapName("Unnamed")
setWallSet("dungeon")
playStream("assets/samples/music/dungeon_ambient.ogg")
mapDesc([[
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
######..##..####.###############
######..##..####.###############
#######.##.#####.###############
####........##...###############
####..##.##......###############
####..#..#####...###############
#######..######.################
###############.################
###############.################
##############..################
###############...##############
###############...##############
###############...##############
################################
################################
################################
################################
################################
################################
################################
################################
]])
spawn("starting_location", 11,15,0, "starting_location")
spawn("script_entity", 17,12,2, "script_entity_2")
	:setSource("function endgame()\
hudPrint (\"The End! Lemme know what you think.\")\
end")
spawn("script_entity", 12,6,1, "script_entity_3")
	:setSource("")
spawn("timer", 6,9,1, "timer_1")
	:setTimerInterval(1)
	:addConnector("activate", "script_entity_4", "hpGuard1")
	:addConnector("activate", "timer_1", "deactivate")
	:addConnector("activate", "timer_2", "activate")
spawn("timer", 7,9,0, "timer_2")
	:setTimerInterval(4)
	:addConnector("activate", "script_entity_5", "suretu")
	:addConnector("activate", "timer_2", "deactivate")
	:addConnector("activate", "timer_3", "activate")
spawn("timer", 8,9,1, "timer_3")
	:setTimerInterval(4)
	:addConnector("activate", "script_entity_6", "suretu")
	:addConnector("activate", "timer_3", "deactivate")
	:addConnector("activate", "timer_4", "activate")
spawn("timer", 9,9,1, "timer_4")
	:setTimerInterval(6)
	:addConnector("activate", "timer_4", "deactivate")
	:addConnector("activate", "script_entity_7", "hpGuard1")
	:addConnector("activate", "timer_5", "activate")
spawn("timer", 10,9,1, "timer_5")
	:setTimerInterval(6)
	:addConnector("activate", "timer_5", "deactivate")
	:addConnector("activate", "timer_6", "activate")
	:addConnector("activate", "script_entity_8", "suretu")
spawn("timer", 11,9,3, "timer_6")
	:setTimerInterval(5)
	:addConnector("activate", "timer_7", "activate")
	:addConnector("activate", "timer_6", "deactivate")
	:addConnector("activate", "script_entity_10", "hpGuard1")
spawn("script_entity", 6,10,1, "script_entity_4")
	:setSource("function hpGuard1()\
playSound \"damage_minotaur_male\"\
hudPrint (\"Ogre Guard: Hey, buddy! Could you give me a hand?\")\
end")
spawn("script_entity", 7,10,0, "script_entity_5")
	:setSource("function suretu()\
hudPrint (\"GUI BOX: ['Umm, sure.'/ 'Maybe later.]'\")\
end")
spawn("script_entity", 8,10,3, "script_entity_6")
	:setSource("function suretu()\
playSound \"secret\"\
hudPrint (\"You: Umm, sure.\")\
end")
spawn("script_entity", 9,10,0, "script_entity_7")
	:setSource("function hpGuard1()\
playSound \"damage_minotaur_male\"\
hudPrint (\"Ogre Guard: That's great!, I locked myself in this cell\")\
hudPrint (\"for the 3rd time this week, and my Captain is on his way back.\")\
end")
spawn("script_entity", 10,10,0, "script_entity_8")
	:setSource("function suretu()\
playSound \"secret\"\
hudPrint (\"You: What do I need to do?\")\
end")
spawn("script_entity", 12,10,3, "script_entity_9")
	:setSource("function hpGuard1()\
hudPrint  (\"Ogre Guard: Take this to get to the barracks.\")\
setMouseItem(spawn(\"brass_key\"))\
hudPrint (\"The password is 'Please'. Genius, right?\")\
end")
spawn("script_entity", 11,10,1, "script_entity_10")
	:setSource("function hpGuard1()\
playSound \"damage_minotaur_male\"\
hudPrint (\"Ogre Guard: I just need you to get my key from the barracks\")\
hudPrint (\"and let me out before my Captain gets back!\")\
end")
spawn("counter", 10,3,2, "cMove")
	:setInitialValue(1)
	:setValue(1)
spawn("pressure_plate_hidden", 7,12,2, "pressure_plate_hidden_1")
	:setTriggeredByParty(false)
	:setTriggeredByMonster(true)
	:setTriggeredByItem(false)
	:setActivateOnce(true)
	:setSilent(true)
	:addConnector("activate", "blocker_3", "activate")
spawn("pressure_plate_hidden", 7,13,2, "pressure_plate_hidden_2")
	:setTriggeredByParty(true)
	:setTriggeredByMonster(false)
	:setTriggeredByItem(false)
	:setActivateOnce(true)
	:setSilent(true)
	:addConnector("activate", "blocker_1", "deactivate")
	:addConnector("activate", "timer_1", "activate")
	:addConnector("activate", "cMove", "decrement")
spawn("lock_prison", 7,13,3, "lock_prison_1")
	:setOpenedBy("prison_key")
	:addConnector("activate", "dungeon_door_portcullis_3", "open")
	:addConnector("activate", "timer_18", "activate")
spawn("lock_prison", 10,13,1, "lock_prison_2")
spawn("lock_prison", 8,15,3, "lock_prison_4")
spawn("blocker", 7,12,3, "blocker_1")
spawn("blocker", 6,11,1, "blocker_2")
spawn("blocker", 7,11,2, "blocker_3")
	:deactivate()
spawn("blocker", 6,12,0, "blocker_4")
spawn("ogre", 7,11,2, "ogre_1")
	:setAIState("guard")
	:addItem(spawn("blue_gem"))
	:addItem(spawn("blue_gem"))
spawn("timer", 12,9,2, "timer_7")
	:setTimerInterval(6)
	:addConnector("activate", "timer_7", "deactivate")
	:addConnector("activate", "script_entity_9", "hpGuard1")
	:addConnector("activate", "timer_8", "activate")
	:addConnector("activate", "cMove", "increment")
spawn("timer", 13,9,2, "timer_8")
	:setTimerInterval(4)
	:addConnector("activate", "timer_8", "deactivate")
	:addConnector("activate", "script_entity_11", "hpGuard1")
spawn("script_entity", 13,10,2, "script_entity_11")
	:setSource("function hpGuard1()\
playSound \"damage_minotaur_male\"\
hudPrint (\"Ogre Guard: Hurry! I'm sure to get fired!\")\
end")
spawn("prison_ceiling_lamp", 15,14,2, "prison_ceiling_lamp_1")
spawn("prison_ceiling_lamp", 8,14,1, "prison_ceiling_lamp_2")
spawn("prison_ceiling_shaft", 15,14,2, "prison_ceiling_shaft_1")
spawn("prison_ceiling_shaft", 8,14,3, "prison_ceiling_shaft_2")
spawn("temple_ceiling_lamp", 16,22,2, "temple_ceiling_lamp_1")
spawn("grim_bed", 17,21,2, "grim_bed_1")
spawn("grim_bed", 17,23,0, "grim_bed_2")
spawn("grim_bed", 15,23,3, "grim_bed_3")
spawn("gobelin", 9,14,0, "gobelin_1")
spawn("gobelin", 12,15,2, "gobelin_2")
spawn("gobelin", 16,14,1, "gobelin_3")
spawn("gobelin", 15,18,1, "gobelin_4")
spawn("gobelin", 15,23,2, "gobelin_5")
spawn("gobelin", 17,23,1, "gobelin_6")
spawn("gobelin", 17,21,1, "gobelin_7")
spawn("dungeon_door_portcullis", 8,16,0, "dungeon_door_portcullis_2")
spawn("dungeon_door_portcullis", 7,13,0, "dungeon_door_portcullis_3")
spawn("dungeon_door_portcullis", 10,13,0, "dungeon_door_portcullis_4")
spawn("dungeon_wall_text", 11,14,0, "dungeon_wall_text_1")
	:setWallText("Holding Cells\
 <----")
spawn("dungeon_wall_text", 15,17,1, "dungeon_wall_text_2")
	:setWallText("Barracks")
spawn("dungeon_wall_drainage", 15,18,1, "dungeon_wall_drainage_1")
spawn("prison_key", 17,21,3, "prison_key_1")
spawn("dungeon_door_metal", 15,20,3, "dungeon_door_metal_1")
spawn("ogre", 14,20,1, "ogre_2")
spawn("pressure_plate_hidden", 15,20,0, "pressure_plate_hidden_5")
	:setTriggeredByParty(true)
	:setTriggeredByMonster(false)
	:setTriggeredByItem(false)
	:setActivateOnce(true)
	:setSilent(true)
	:addConnector("activate", "timer_16", "activate")
spawn("dungeon_door_wooden_locked", 15,17,2, "dungeon_door_wooden_locked_2")
	:setOpenedBy("brass_key")
spawn("dungeon_door_wooden", 15,21,0, "dungeon_door_wooden_1")
spawn("timer", 17,19,1, "timer_16")
	:setTimerInterval(1)
	:addConnector("activate", "timer_16", "deactivate")
	:addConnector("activate", "timer_9", "activate")
	:addConnector("activate", "script_entity_19", "hpGuard1")
spawn("timer", 18,19,0, "timer_9")
	:setTimerInterval(4)
	:addConnector("activate", "script_entity_12", "suretu")
	:addConnector("activate", "timer_9", "deactivate")
	:addConnector("activate", "timer_10", "activate")
spawn("timer", 19,19,1, "timer_10")
	:setTimerInterval(3)
	:addConnector("activate", "timer_10", "deactivate")
	:addConnector("activate", "timer_11", "activate")
	:addConnector("activate", "script_entity_13", "suretu")
spawn("timer", 20,19,1, "timer_11")
	:setTimerInterval(4)
	:addConnector("activate", "timer_11", "deactivate")
	:addConnector("activate", "script_entity_14", "hpGuard1")
	:addConnector("activate", "timer_12", "activate")
spawn("timer", 21,19,1, "timer_12")
	:setTimerInterval(5)
	:addConnector("activate", "dungeon_door_wooden_1", "open")
spawn("timer", 22,19,3, "timer_13")
	:setTimerInterval(5)
spawn("script_entity", 17,20,1, "script_entity_19")
	:setSource("function hpGuard1()\
playSound \"damage_minotaur_male\"\
hudPrint (\"Ogre Guard: What's the password?\")\
end")
spawn("script_entity", 18,20,0, "script_entity_12")
	:setSource("function suretu()\
hudPrint (\"GUI BOX: ['Please?' / 'Open Sesame' / 'Ogre's are great!' ]'\")\
end")
spawn("script_entity", 19,20,3, "script_entity_13")
	:setSource("function suretu()\
playSound \"secret\"\
hudPrint (\"You: Please?\")\
end")
spawn("script_entity", 20,20,0, "script_entity_14")
	:setSource("function hpGuard1()\
playSound \"damage_minotaur_male\"\
hudPrint (\"Ogre Guard: Correct, and you couldn't have guessed it.\")\
hudPrint (\"I thought it up myself! You must be okay.\")\
end")
spawn("script_entity", 21,20,0, "script_entity_15")
	:setSource("function suretu()\
playSound \"secret\"\
hudPrint (\"You: What do I need to do?\")\
end")
spawn("script_entity", 23,20,3, "script_entity_16")
	:setSource("function hpGuard1()\
hudPrint  (\"Ogre Guard: Take this to get to the barracks.\")\
setMouseItem(spawn(\"brass_key\"))\
hudPrint (\"The password is 'Please'. Genius, right?\")\
end")
spawn("script_entity", 22,20,1, "script_entity_17")
	:setSource("function hpGuard1()\
playSound \"damage_minotaur_male\"\
hudPrint (\"Ogre Guard: I just need you to get my key from the barracks\")\
hudPrint (\"and let me out before my Captain gets back!\")\
end")
spawn("timer", 23,19,2, "timer_14")
	:setTimerInterval(6)
spawn("torch_holder", 10,14,2, "torch_holder_1")
	:addTorch()
spawn("torch_holder", 7,16,3, "torch_holder_3")
	:addTorch()
spawn("torch_holder", 15,19,3, "torch_holder_4")
	:addTorch()
spawn("timer", 5,11,2, "timer_15")
	:setTimerInterval(1.5)
spawn("timer", 5,12,3, "timer_17")
	:setTimerInterval(4)
	:addConnector("activate", "script_entity_20", "suretu")
	:addConnector("activate", "timer_17", "deactivate")
	:addConnector("activate", "timer_15", "activate")
spawn("timer", 5,13,0, "timer_18")
	:setTimerInterval(1)
	:addConnector("activate", "timer_18", "deactivate")
	:addConnector("activate", "timer_17", "activate")
	:addConnector("activate", "script_entity_21", "hpGuard1")
spawn("script_entity", 4,11,2, "script_entity_18")
	:setSource("function suretu()\
hudPrint (\"[Maybe that Death chamber can help.]\")\
end")
spawn("script_entity", 4,12,0, "script_entity_20")
	:setSource("function suretu()\
playSound \"secret\"\
hudPrint (\"You: Hey! What's the big idea?!\")\
end")
spawn("script_entity", 4,13,0, "script_entity_21")
	:setSource("function hpGuard1()\
playSound \"damage_minotaur_male\"\
hudPrint (\"Ogre Guard: Thanks! Now to eliminate the witnesses!\")\
end")
spawn("spawner", 4,14,2, "spawner_1")
	:setSpawnedEntity("powerbolt")
	:setCoolDown(0)
spawn("spawner", 5,16,0, "spawner_2")
	:setSpawnedEntity("powerbolt")
	:setCoolDown(0)
spawn("lever", 6,14,2, "lever_1")
	:addConnector("any", "timer_19", "toggle")
	:addConnector("any", "dungeon_door_metal_2", "toggle")
spawn("timer", 6,15,3, "timer_19")
	:setTimerInterval(0.5)
	:addConnector("activate", "spawner_2", "activate")
	:addConnector("activate", "spawner_1", "activate")
	:addConnector("activate", "<SELECT TARGET>", "")
spawn("dungeon_wall_text", 6,14,0, "dungeon_wall_text_3")
	:setWallText("Death Chamber")
spawn("dungeon_door_metal", 5,14,1, "dungeon_door_metal_2")
	:setDoorState("open")
spawn("daemon_head_eye_slots", 15,14,0, "daemon_head_eye_slots_1")
spawn("pressure_plate_hidden", 16,12,1, "pressure_plate_hidden_3")
	:setTriggeredByParty(true)
	:setTriggeredByMonster(false)
	:setTriggeredByItem(false)
	:setActivateOnce(true)
	:setSilent(true)
	:addConnector("activate", "script_entity_2", "endgame")
spawn("dungeon_stairs_up", 16,11,0, "dungeon_stairs_up_1")
spawn("dungeon_door_ornament", 16,13,2, "dungeon_door_ornament_1")
spawn("eye_socket_left", 15,14,0, "eye_socket_left_1")
	:addConnector("activate", "counter_1", "decrement")
spawn("eye_socket_right", 15,14,0, "eye_socket_right_1")
	:addConnector("activate", "counter_1", "decrement")
spawn("counter", 15,13,0, "counter_1")
	:setInitialValue(2)
	:setValue(2)
	:addConnector("activate", "dungeon_door_ornament_1", "open")
