-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom item definitions here

defineObject{
		name = "grim_eye",
		class = "Item",
		uiName = "Eye of Grimwold",
		model = "assets/models/items/gear_necklace.fbx",
		description = "This Pendant seems to be a key of some sort. Best to hold on to it.",
		skill = "air_magic",
		requiredLevel = 41,


		slot = "Neck",
		gfxIndex = 219,
		weight = 0.4,
		gameEffect = "Control Shadow (Protection from Spirits.) This artifact is sought after by many conjurers and necromancers.  ",

	}

defineObject{
		name = "magic_key",
		class = "Item",
		uiName = "Magic Key",
		model = "assets/models/items/key_gold.fbx",
		description = "Well, that's handy..",
		glitterEffect = "glitter_gold",
		gfxIndex = 116,
		key = true,
		weight = 0.2,
	}


defineObject{
		name = "spring",
		class = "Item",
		uiName = "Spring",
		model = "assets/models/items/brace_fortitude.fbx",
		description = "It's a spring.",
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_1.tga",
		gfxIndex = 24,
		attackPower = 1,
		accuracy = 8,
		coolDownTime = 1.5,
		attackMethod = "meleeAttack",
		attackSwipe = "vertical",
		attackSound = "swipe_light",
		impactSound = "impact_blade",
		weight = 0.8,
	}

defineObject{
		name = "raekenierh",
		class = "Item",
		uiName = "Raekenierh",
		model = "assets/models/items/lurker_clothes_small.fbx",
		description = "This mask emanates a low humming noise.",
		slot = "Head",
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_1.tga",
		gfxIndex = 0,
		protection = 0,
		evasion = 5,
		weight = 0.2,
		gameEffect = "Wearer gains experience points 25% faster",
	}

defineObject{
		name = "broken_saber",
		class = "Item",
		uiName = "Broken Mechanical Hilt",
		model = "assets/models/items/knife.fbx",
		description = "It appears to be a non- functioning light sword, or saber, if you will..",
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_1.tga",
		gfxIndex = 2,
		attackPower = 5,
		accuracy = 8,
		coolDownTime = 2.5,
		attackMethod = "meleeAttack",
		attackSwipe = "vertical",
		attackSound = "swipe_light",
		impactSound = "impact_blade",
		weight = 0.8,
	}

defineObject{
		name = "spider_venom",
		class = "Item",
		uiName = "Spider queen venom",
		model = "assets/models/items/flask_full.fbx",
		description = "The potent toxin of the queen arachnid.",
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_1.tga",
		gfxIndex =11,
		weight = 0.2,
	}
defineObject{
		name = "magnet",
		class = "Item",
		uiName = "Magnet",
		model = "assets/models/items/gear_necklace.fbx",
		description = "There is a  force inside that attracts metal.Definitely magical.",
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_1.tga",
		gfxIndex =15,
		attackPower = 5,
		accuracy = 8,
		coolDownTime = 2.5,
		attackMethod = "meleeAttack",
		attackSwipe = "vertical",
		attackSound = "swipe_light",
		impactSound = "impact_blade",
		weight = 0.8,
	}

		defineObject{
		name = "nunchaku",
		class = "Item",
		uiName = "Nunchaku",
		model = "assets/models/items/sling.fbx",
		description = "Numb Chucks. Good range",
		skill = "daggers",
		requiredLevel = 10,
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_4.tga",
		gfxIndex =10,
		attackPower = 10,
		accuracy = 3,
		coolDownTime = 2.0,
		attackMethod = "meleeAttack",
		attackSwipe = "thrust",
		attackSound = "swipe",
		impactSound = "impact_blunt",
		weight = 2.0,
		reachWeapon = true,
	}

defineObject{
		name = "ninja_gi",
		class = "Item",
		uiName = "Ninja Gi",
		model = "assets/models/items/lurker_clothes.fbx",
		description = "A rogue suit allowing for mobility and blending into surrounding shadows.",
		slot = "Torso",
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_4.tga",
		gfxIndex =14,
		protection = 5,
		evasion = 15,
		weight = 0.75,
	}
defineObject{
		name = "tanto",
		class = "Item",
		uiName = "Assassin Tanto",
		model = "assets/models/items/assassin_dagger.fbx",
		description = "A lithe concealable blade. Half dagger, half sword.",
		skill = "daggers",
		requiredLevel = 15,
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_4.tga",
		gfxIndex =4,
		attackPower = 20,
		accuracy = 3,
		coolDownTime = 2.8,
		attackMethod = "meleeAttack",
		attackSwipe = "vertical",
		attackSound = "swipe_light",
		impactSound = "impact_blade",
		gameEffect = "Life Leech: Successful hit drains life from target and heals you",
		weight = 2.0,
	}
		defineObject{
		name = "rose_circlet",
		class = "Item",
		uiName = "Circlet of Rose",
		model = "assets/models/items/circlet_war.fbx",
		description = "These flowers are hundreds of years old,yet vibrant and alive.",
		slot = "Head",
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_4.tga",
		gfxIndex =16,
		protection = 5,
		willpower = 3,
		weight = 0.5,
	}
defineObject{
		name = "shield_cavalier",
		class = "Item",
		uiName = "Cavalier Shield",
		model = "assets/models/items/shield_elements.fbx",
		description = "A shield used by knights when battling from horseback.",
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_4.tga",
		gfxIndex =18,
		evasion = 12,
		resistFire = 50,
		resistPoison = 20,
		weight = 5.5,
		shield = true,
}
defineObject{
		name = "dragon_gauntlets",
		class = "Item",
		uiName = "Dragon Gauntlets",
		model = "assets/models/items/plate_gauntlets.fbx",
		slot = "Gauntlets",
		armorSkill = "light_armor",
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_4.tga",
		gfxIndex =30,
		protection = 15,
		evasion = 5,
		resistFire = 20,
		weight = 3.0,
	}

defineObject{
		name = "pool_ball",
		class = "Item",
		uiName = "Runed Sphere",
		model = "assets/models/items/apprentice_orb.fbx",
		description = "A standard jade colored sphere with a strange rune painted on it. It is unnaturally hard.",
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_5.tga",
		gfxIndex = 17,
		attackPower = 8,
		accuracy = 8,
		coolDownTime =  .5,
		attackMethod = "meleeAttack",
		attackSwipe = "vertical",
		attackSound = "swipe_light",
		impactSound = "impact_blade",
		weight = 0.8,
	}


defineObject{
		name = "emerald_sceptre",
		class = "Item",
		uiName = "Emerald Sceptre",
		model = "assets/models/items/cudgel.fbx",
		description = "Gem encrusted mace with a crystal head.",
		skill = "maces",
		requiredLevel = 12,
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_5.tga",
		gfxIndex = 13,

		attackPower = 20,
		accuracy = 2,
		coolDownTime = 3,
		attackMethod = "meleeAttack",
		attackSwipe = "horizontal", --{ {time=0, swipe="horizontal"}, {time=0.2, swipe="vertical"}, {time=0.4, swipe="horizontal"} },
		attackSound = "swipe_heavy",
		impactSound = "impact_blunt",
		weight = 4.0,
	}


defineObject{
		name = "darkwood_wand",
		class = "Item",
		uiName = "Darkwood Wand",
		model = "assets/models/items/whitewood_wand.fbx",
		description = "A beautifully crafted maple wand that can be used to turn invisible for a short time.",
		skill = "spellcraft",
		requiredLevel = 15,
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_5.tga",
		gfxIndex = 7,

		energy = 10,
		attackMethod = "castWandSpell",
		spell = "invisibility",
		wandPower = 25,
		charges = 3,
		impactSound = "impact_blunt",
		weight = 1.5,
	}


defineObject{
		name = "zokathra",
		class = "Item",
		uiName = "Zo-Kath-Ra",
		model = "assets/models/items/apprentice_orb.fbx",
		description = "A strange object that appears as though it were created from nothingness.",
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_3.tga",
		gfxIndex = 5,
		weight = 0.8,
	}


defineObject{
		name = "katana",
		class = "Item",
		uiName = "Katana",
		model = "assets/models/items/scimitar.fbx",
		description = "A lithe and agile sword used by Samurai and Ninja alike.",
		skill = "swords",
		requiredLevel = 15,
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_4.tga",
		gfxIndex = 4,
		attackPower = 24,
		accuracy = 15,
		coolDownTime = 1.8,
		attackMethod = "meleeAttack",
		attackSwipe = "horizontal",
		attackSound = "swipe",
		impactSound = "impact_blade",
		weight = 3.2,
	}


defineObject{
		name = "dragon_cape",
		class = "Item",
		uiName = "Dragon Cape",
		description = "A protective cloak used in long hunts.",
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_5.tga",
		gfxIndex = 65,
		model = "assets/models/items/scaled_cloak.fbx",

		slot = "Cloak",
		evasion = 12,
		
		resist_fire = 50,
		weight = 1.8,
	}

defineObject{
		name = "dragon_sword",
		class = "Item",
		uiName = "Dragon Sword",
		model = "assets/models/items/dismantler.fbx",
		description = "A magical blade used by Paladinsws",
		skill = "swords",
		requiredLevel = 20,
		strength = 4,
		energy = 1,
		gfxAtlas = "mod_assets/wiz8_item_icons/wiz8_item_icons_5.tga",
		gfxIndex =  1,
		attackPower = 30,
		accuracy = 8,
		coolDownTime = 2.0,
		attackMethod = "meleeAttack",
		attackSwipe = "vertical",
		attackSound = "swipe_light",
		impactSound = "impact_blade",
		weight = 0.8,
		gameEffect = "Dragonbane (Wielder is granted a 3x damage bonus vs. Dragons.)",

	}




