-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom material definitions here

defineMaterial{
	name = "barb_f_body",

	diffuseMap = "mod_assets/textures/barb.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 0,

	depthBias = 1,

}

