-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom dungeon object definitions here

defineObject{
	name = "barb",
	class = "Blockage",
	model = "mod_assets/models/testbar.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "diz",
	class = "Altar",
	model = "mod_assets/models/diz.fbx",
	placement = "floor",
	editorIcon = 52,
}

