-- This file has been generated by Dungeon Editor 1.3.1

-- GOBELINS

defineObject{
	name = "gobelin_green",
	class = "WallTapestry",
	model = "mod_assets/lol_gobelins/models/env/gobelin_green.fbx",
	brokenModel = "mod_assets/lol_gobelins/models/env/gobelin_green_torn.fbx",
	placement = "wall",
	editorIcon = 92,
}

defineObject{
	name = "gobelin_crimson",
	class = "WallTapestry",
	model = "mod_assets/lol_gobelins/models/env/gobelin_crimson.fbx",
	brokenModel = "mod_assets/lol_gobelins/models/env/gobelin_crimson_torn.fbx",
	placement = "wall",
	editorIcon = 92,
}

defineObject{
	name = "gobelin_blue",
	class = "WallTapestry",
	model = "mod_assets/lol_gobelins/models/env/gobelin_blue.fbx",
	brokenModel = "mod_assets/lol_gobelins/models/env/gobelin_blue_torn.fbx",
	placement = "wall",
	editorIcon = 92,
}

defineObject{
	name = "gobelin_unicorns",
	class = "WallTapestry",
	model = "mod_assets/lol_gobelins/models/env/gobelin_unicorns.fbx",
	brokenModel = "mod_assets/lol_gobelins/models/env/gobelin_unicorns_torn.fbx",
	placement = "wall",
	editorIcon = 92,
}