-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom item definitions here



cloneObject{
	name= "lurker_gloves",
	baseObject = "leather_gloves",
	uiName = "Lurker Gloves",
	slot = "Gauntlets",
	model = "mod_assets/models/lurker_gloves.fbx",
	armorSet = "lurker",
	gfxAtlas = "mod_assets/textures/lurker_items.tga",
	gfxIndex = 0,
	protection = 0,
	evasion = 5,
	weight = .25,
	description = "Dark, lightweight gloves perfect for sneaky deeds.",

}