-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom item definitions here

cloneObject{
	name = "bone_shield_amulet",
	baseObject = "bone_amulet",
	uiName = "Bone Shield Amulet",
	protection = 2,
	description = "This amulet protects its wearer.",
}

cloneObject{
	name = "temple_fire_scroll",
	baseObject = "scroll",
	uiName = "The Fire Scroll",
	description = "The words written on this scroll are illegible but seem to emit their own heat.",
}

cloneObject{
	name = "temple_water_scroll",
	baseObject = "scroll",
	uiName = "The Water Scroll",
	description = "The words written on this scroll are illegible and seem to be dripping off the page. When you look away, they return to their original state.",
}

cloneObject{
	name = "temple_air_scroll",
	baseObject = "scroll",
	uiName = "The Air Scroll",
	description = "The words written on this scroll are illegible. A refreshing gust caresses your face as you open it.",
}

cloneObject{
	name = "temple_earth_scroll",
	baseObject = "scroll",
	uiName = "The Earth Scroll",
	description = "The words written on this scroll are illegible. The paper and ink reek of dirt.",
}

cloneObject{
	name = "scroll_lever_hint",
	baseObject = "scroll",
	uiName = "Ancient Scroll",
	description = "You must go above and beyond the call, to the deepest recess of your soul, rise to any challenge, or be dragged to depths below.",
}

cloneObject{
	name = "blue_mouth_gem",
	baseObject = "blue_gem",
	uiName = "Flawed Blue Gem",
	description = "This gem looks to have been chewed on, as impossible as it seems.",
}

cloneObject{
	name = "frost_brigandine",
	baseObject = "leather_brigandine",
	uiName = "Frost Brigandine",
	model = "mod_assets/models/frost_brigandine.fbx",
	slot = "Torso",
	armorSkill = "light_armor",
	armorSet = "frostleather",
	gfxAtlas = "mod_assets/textures/frost_items.tga",
	gfxIndex = 0,
	protection = 4,
	resistCold = 10,
	weight = 8.0,
	description = "This strange leather armor radiates with an unnatural warmth."
}

cloneObject{
	name = "frost_boots",
	baseObject = "leather_boots",
	uiName = "Frost Boots",
	model = "mod_assets/models/frost_boots.fbx",
	slot = "Feet",
	armorSkill = "light_armor",
	armorSet = "frostleather",
	gfxAtlas = "mod_assets/textures/frost_items.tga",
	gfxIndex = 1,
	protection = 4,
	resistCold = 5,
	weight = 8.0,
	description = "These strange leather boots radiate with an unnatural warmth."
}

cloneObject{
	name = "frost_cap",
	baseObject = "leather_cap",
	uiName = "Frost Cap",
	model = "mod_assets/models/frost_cap.fbx",
	slot = "Head",
	armorSkill = "light_armor",
	armorSet = "frostleather",
	gfxAtlas = "mod_assets/textures/frost_items.tga",
	gfxIndex = 2,
	protection = 4,
	resistCold = 5,
	weight = 0.8,
	description = "This strange leather cap radiates with an unnatural warmth."
}

cloneObject{
	name = "frost_gloves",
	baseObject = "leather_gloves",
	uiName = "Frost Gloves",
	model = "mod_assets/models/frost_clothes_small.fbx",
	slot = "Gauntlets",
	armorSkill = "light_armor",
	armorSet = "frostleather",
	gfxAtlas = "mod_assets/textures/frost_items.tga",
	gfxIndex = 4,
	protection = 2,
	resistCold = 5,
	weight = 0.8,
	description = "These strange leather gloves radiate with an unnatural warmth."
}


cloneObject{
	name = "frost_greaves",
	baseObject = "leather_greaves",
	uiName = "Frost Greaves",
	model = "mod_assets/models/frost_greaves.fbx",
	slot = "Legs",
	armorskill = "light_armor",
	armorSet = "frostleather",
	gfxAtlas = "mod_assets/textures/frost_items.tga",
	gfxIndex = 3,
	protection = 2,
	resistCold = 5,
	weight = 0.8,
	description = "These strange leather greaves radiate with an unnatural warmth."
}

cloneObject{
	name = "ember_sword",
	baseObject = "long_sword",
	uiName = "Longsword of Embers",
	model = "mod_assets/models/ember_sword.fbx",
	skill = "swords",
	gfxAtlas = "mod_assets/textures/ember_items.tga",
	gfxIndex = 0,
	attackPower = 16,
	damageType = "fire",
	accuracy = 0,
	coolDownTime = 3.2,
	attackMethod = "meleeAttack",
	attackSwipe = "horizontal",
	attackSound = "swipe",
	impactSound = "impact_blade",
	weight = 3.2,
	description = "This weapon burns any who touch its red-hot blade."
}

cloneObject{
	name= "chitin_gloves",
	baseObject = "leather_gloves",
	uiName = "Chitin Gloves",
	model = "mod_assets/models/chitin_gloves.fbx",
	armorSkill = "light_armor",
	armorSet = "chitin",
	slot = "Gauntlets",
	gfxAtlas = "mod_assets/textures/chitin_items.tga",
	gfxIndex = 0,
	protection = 9,
	weight = 3,
	description = "These modified gloves have heavy bug carcasses on them. Ew.",

}

cloneObject{
	name= "lurker_gloves",
	baseObject = "leather_gloves",
	uiName = "Lurker Gloves",
	slot = "Gauntlets",
	model = "mod_assets/models/lurker_gloves.fbx",
	armorSet = "lurker",
	gfxAtlas = "mod_assets/textures/lurker_items.tga",
	gfxIndex = 0,
	evasion = 5,
	weight = .25,
	description = "Dark, lightweight gloves perfect for sneaky deeds.",

}