-- This file has been generated by Dungeon Editor 1.3.6

--- level 1 ---

mapName("Castle Level 1")
setWallSet("castle_exterior")
playStream("assets/samples/music/dungeon_ambient.ogg")
mapDesc([[
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
#################...############
#################.#.############
#################...############
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
]])
spawn("castle_exterior_pillar_big", 18,19,2, "castle_exterior_pillar_big_17")
spawn("castle_exterior_pillar_big", 18,20,2, "castle_exterior_pillar_big_24")
spawn("castle_exterior_pillar_big", 19,20,2, "castle_exterior_pillar_big_25")
spawn("castle_exterior_pillar_big", 19,19,2, "castle_exterior_pillar_big_26")
spawn("castle_exterior_wall_windows", 18,18,2, "castle_exterior_wall_windows_1")
spawn("castle_exterior_wall_windows", 17,19,1, "castle_exterior_wall_windows_2")
spawn("sx_remove_wall", 17,18,0, "sx_remove_wall_2")
spawn("sx_remove_wall", 18,18,0, "sx_remove_wall_52")
spawn("sx_remove_wall", 19,18,0, "sx_remove_wall_53")
spawn("sx_remove_wall", 19,18,1, "sx_remove_wall_54")
spawn("sx_remove_wall", 19,19,1, "sx_remove_wall_55")
spawn("sx_remove_wall", 19,20,1, "sx_remove_wall_56")
spawn("sx_remove_wall", 19,20,2, "sx_remove_wall_57")
spawn("sx_remove_wall", 18,20,2, "sx_remove_wall_58")
spawn("sx_remove_wall", 17,20,2, "sx_remove_wall_59")
spawn("sx_remove_wall", 17,20,3, "sx_remove_wall_60")
spawn("sx_remove_wall", 17,19,3, "sx_remove_wall_61")
spawn("sx_remove_wall", 17,18,3, "sx_remove_wall_62")
spawn("sx_outwall_pillarkiller", 17,18,0, "sx_outwall_pillarkiller_2")
spawn("sx_outwall_pillarkiller", 19,18,0, "sx_outwall_pillarkiller_28")
spawn("sx_outwall_pillarkiller", 19,19,1, "sx_outwall_pillarkiller_29")
spawn("sx_outwall_pillarkiller", 19,20,2, "sx_outwall_pillarkiller_30")
spawn("sx_outwall_pillarkiller", 17,20,2, "sx_outwall_pillarkiller_31")
spawn("sx_outwall_pillarkiller", 17,19,3, "sx_outwall_pillarkiller_32")

--- level 2 ---

mapName("Castle Level 2")
setWallSet("castle_exterior")
playStream("assets/samples/music/dungeon_ambient.ogg")
mapDesc([[
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
############.......#############
############.......#############
############.........###########
############.......#...#########
############.......#.#.#########
############...........#########
############..........##########
##############...##...##########
##############...##.############
#############.......############
############......##############
############......##############
############......##############
#############.....##############
###############...##############
################################
################################
################################
################################
################################
]])
spawn("castle_exterior_pillar_big", 17,19,0, "castle_exterior_pillar_big_2")
spawn("castle_exterior_pillar_big", 19,19,0, "castle_exterior_pillar_big_16")
spawn("castle_exterior_pillar_big", 17,21,0, "castle_exterior_pillar_big_18")
spawn("castle_exterior_pillar_big", 19,17,0, "castle_exterior_pillar_big_20")
spawn("castle_exterior_pillar_big", 20,17,0, "castle_exterior_pillar_big_21")
spawn("castle_exterior_pillar_big", 20,15,0, "castle_exterior_pillar_big_22")
spawn("castle_exterior_pillar_big", 19,15,0, "castle_exterior_pillar_big_23")
spawn("castle_exterior_wall_windows", 18,16,1, "castle_exterior_wall_windows_3")
spawn("castle_exterior_wall_windows", 18,18,2, "castle_exterior_wall_windows_4")
spawn("sx_remove_ceiling", 12,14,2, "sx_remove_ceiling_49")
spawn("sx_remove_ceiling", 13,14,0, "sx_remove_ceiling_50")
spawn("sx_remove_ceiling", 14,14,0, "sx_remove_ceiling_51")
spawn("sx_remove_ceiling", 16,14,3, "sx_remove_ceiling_52")
spawn("sx_remove_ceiling", 18,14,3, "sx_remove_ceiling_53")
spawn("sx_remove_ceiling", 17,14,1, "sx_remove_ceiling_54")
spawn("sx_remove_ceiling", 15,14,2, "sx_remove_ceiling_55")
spawn("sx_remove_ceiling", 12,13,2, "sx_remove_ceiling_87")
spawn("sx_remove_ceiling", 13,13,0, "sx_remove_ceiling_68")
spawn("sx_remove_ceiling", 16,13,3, "sx_remove_ceiling_70")
spawn("sx_remove_ceiling", 18,13,3, "sx_remove_ceiling_71")
spawn("sx_remove_ceiling", 17,13,1, "sx_remove_ceiling_72")
spawn("sx_remove_ceiling", 15,13,2, "sx_remove_ceiling_73")
spawn("sx_remove_ceiling", 12,12,2, "sx_remove_ceiling_177")
spawn("sx_remove_ceiling", 13,12,0, "sx_remove_ceiling_112")
spawn("sx_remove_ceiling", 14,12,0, "sx_remove_ceiling_114")
spawn("sx_remove_ceiling", 16,12,3, "sx_remove_ceiling_115")
spawn("sx_remove_ceiling", 18,12,3, "sx_remove_ceiling_116")
spawn("sx_remove_ceiling", 17,12,1, "sx_remove_ceiling_117")
spawn("sx_remove_ceiling", 15,12,2, "sx_remove_ceiling_118")
spawn("sx_remove_ceiling", 13,18,0, "sx_remove_ceiling_368")
spawn("sx_remove_ceiling", 14,18,0, "sx_remove_ceiling_370")
spawn("sx_remove_ceiling", 16,18,3, "sx_remove_ceiling_371")
spawn("sx_remove_ceiling", 18,18,3, "sx_remove_ceiling_372")
spawn("sx_remove_ceiling", 17,18,1, "sx_remove_ceiling_373")
spawn("sx_remove_ceiling", 15,18,2, "sx_remove_ceiling_374")
spawn("sx_remove_ceiling", 13,17,0, "sx_remove_ceiling_388")
spawn("sx_remove_ceiling", 14,17,0, "sx_remove_ceiling_389")
spawn("sx_remove_ceiling", 16,17,3, "sx_remove_ceiling_390")
spawn("sx_remove_ceiling", 18,17,3, "sx_remove_ceiling_391")
spawn("sx_remove_ceiling", 17,17,1, "sx_remove_ceiling_392")
spawn("sx_remove_ceiling", 15,17,2, "sx_remove_ceiling_393")
spawn("sx_remove_ceiling", 21,17,2, "sx_remove_ceiling_406")
spawn("sx_remove_ceiling", 20,17,1, "sx_remove_ceiling_413")
spawn("sx_remove_ceiling", 19,17,2, "sx_remove_ceiling_414")
spawn("sx_remove_ceiling", 21,18,2, "sx_remove_ceiling_419")
spawn("sx_remove_ceiling", 20,18,1, "sx_remove_ceiling_426")
spawn("sx_remove_ceiling", 19,18,2, "sx_remove_ceiling_427")
spawn("sx_remove_ceiling", 12,22,2, "sx_remove_ceiling_497")
spawn("sx_remove_ceiling", 13,22,0, "sx_remove_ceiling_432")
spawn("sx_remove_ceiling", 14,22,0, "sx_remove_ceiling_434")
spawn("sx_remove_ceiling", 16,22,3, "sx_remove_ceiling_435")
spawn("sx_remove_ceiling", 17,22,1, "sx_remove_ceiling_437")
spawn("sx_remove_ceiling", 15,22,2, "sx_remove_ceiling_438")
spawn("sx_remove_ceiling", 13,21,0, "sx_remove_ceiling_452")
spawn("sx_remove_ceiling", 14,21,0, "sx_remove_ceiling_453")
spawn("sx_remove_ceiling", 16,21,3, "sx_remove_ceiling_454")
spawn("sx_remove_ceiling", 17,21,1, "sx_remove_ceiling_456")
spawn("sx_remove_ceiling", 15,21,2, "sx_remove_ceiling_457")
spawn("sx_remove_ceiling", 12,24,2, "sx_remove_ceiling_561")
spawn("sx_remove_ceiling", 13,24,0, "sx_remove_ceiling_496")
spawn("sx_remove_ceiling", 14,24,0, "sx_remove_ceiling_498")
spawn("sx_remove_ceiling", 16,24,3, "sx_remove_ceiling_499")
spawn("sx_remove_ceiling", 17,24,1, "sx_remove_ceiling_501")
spawn("sx_remove_ceiling", 15,24,2, "sx_remove_ceiling_502")
spawn("sx_remove_ceiling", 12,23,2, "sx_remove_ceiling_515")
spawn("sx_remove_ceiling", 13,23,0, "sx_remove_ceiling_516")
spawn("sx_remove_ceiling", 14,23,0, "sx_remove_ceiling_517")
spawn("sx_remove_ceiling", 16,23,3, "sx_remove_ceiling_518")
spawn("sx_remove_ceiling", 17,23,1, "sx_remove_ceiling_520")
spawn("sx_remove_ceiling", 15,23,2, "sx_remove_ceiling_521")
spawn("sx_remove_ceiling", 16,26,3, "sx_remove_ceiling_563")
spawn("sx_remove_ceiling", 17,26,1, "sx_remove_ceiling_565")
spawn("sx_remove_ceiling", 15,26,2, "sx_remove_ceiling_566")
spawn("sx_remove_ceiling", 13,25,0, "sx_remove_ceiling_580")
spawn("sx_remove_ceiling", 14,25,0, "sx_remove_ceiling_581")
spawn("sx_remove_ceiling", 16,25,3, "sx_remove_ceiling_582")
spawn("sx_remove_ceiling", 17,25,1, "sx_remove_ceiling_584")
spawn("sx_remove_ceiling", 15,25,2, "sx_remove_ceiling_585")
spawn("sx_remove_ceiling", 13,16,0, "sx_remove_ceiling_944")
spawn("sx_remove_ceiling", 14,16,0, "sx_remove_ceiling_946")
spawn("sx_remove_ceiling", 16,16,3, "sx_remove_ceiling_947")
spawn("sx_remove_ceiling", 18,16,3, "sx_remove_ceiling_948")
spawn("sx_remove_ceiling", 17,16,1, "sx_remove_ceiling_949")
spawn("sx_remove_ceiling", 15,16,2, "sx_remove_ceiling_950")
spawn("sx_remove_ceiling", 12,15,2, "sx_remove_ceiling_963")
spawn("sx_remove_ceiling", 13,15,0, "sx_remove_ceiling_964")
spawn("sx_remove_ceiling", 14,15,0, "sx_remove_ceiling_965")
spawn("sx_remove_ceiling", 16,15,3, "sx_remove_ceiling_966")
spawn("sx_remove_ceiling", 18,15,3, "sx_remove_ceiling_967")
spawn("sx_remove_ceiling", 17,15,1, "sx_remove_ceiling_968")
spawn("sx_remove_ceiling", 15,15,2, "sx_remove_ceiling_969")
spawn("sx_remove_ceiling", 21,16,2, "sx_remove_ceiling_994")
spawn("sx_remove_ceiling", 20,16,1, "sx_remove_ceiling_1001")
spawn("sx_remove_ceiling", 21,19,2, "sx_remove_ceiling_1033")
spawn("sx_remove_ceiling", 20,19,1, "sx_remove_ceiling_1013")
spawn("sx_remove_ceiling", 19,19,2, "sx_remove_ceiling_1014")
spawn("sx_remove_ceiling", 14,20,0, "sx_remove_ceiling_1034")
spawn("sx_remove_ceiling", 16,20,3, "sx_remove_ceiling_1035")
spawn("sx_remove_ceiling", 15,20,2, "sx_remove_ceiling_1036")
spawn("sx_remove_ceiling", 14,19,0, "sx_remove_ceiling_1051")
spawn("sx_remove_ceiling", 16,19,3, "sx_remove_ceiling_1052")
spawn("sx_remove_ceiling", 15,19,2, "sx_remove_ceiling_1053")
spawn("sx_remove_floor", 17,16,2, "sx_remove_floor_1")
spawn("sx_remove_floor", 17,15,1, "sx_remove_floor_2")
spawn("sx_remove_floor", 17,14,0, "sx_remove_floor_3")
spawn("sx_remove_floor", 17,13,2, "sx_remove_floor_4")
spawn("sx_remove_floor", 16,13,3, "sx_remove_floor_5")
spawn("sx_remove_floor", 15,13,0, "sx_remove_floor_6")
spawn("sx_remove_floor", 13,13,3, "sx_remove_floor_8")
spawn("sx_remove_floor", 13,14,3, "sx_remove_floor_9")
spawn("sx_remove_floor", 14,14,3, "sx_remove_floor_10")
spawn("sx_remove_floor", 15,14,0, "sx_remove_floor_11")
spawn("sx_remove_floor", 16,14,3, "sx_remove_floor_12")
spawn("sx_remove_floor", 16,15,0, "sx_remove_floor_13")
spawn("sx_remove_floor", 15,15,3, "sx_remove_floor_14")
spawn("sx_remove_floor", 14,15,3, "sx_remove_floor_15")
spawn("sx_remove_floor", 13,15,2, "sx_remove_floor_16")
spawn("sx_remove_floor", 13,16,2, "sx_remove_floor_17")
spawn("sx_remove_floor", 14,16,2, "sx_remove_floor_18")
spawn("sx_remove_floor", 15,16,2, "sx_remove_floor_19")
spawn("sx_remove_floor", 16,16,3, "sx_remove_floor_20")
spawn("sx_remove_floor", 16,17,3, "sx_remove_floor_21")
spawn("sx_remove_floor", 15,17,2, "sx_remove_floor_22")
spawn("sx_remove_floor", 14,17,2, "sx_remove_floor_23")
spawn("sx_remove_floor", 13,17,3, "sx_remove_floor_24")
spawn("sx_remove_floor", 17,17,1, "sx_remove_floor_25")
spawn("sx_remove_floor", 17,18,0, "sx_remove_floor_26")
spawn("sx_remove_floor", 18,18,1, "sx_remove_floor_27")
spawn("sx_remove_floor", 19,18,0, "sx_remove_floor_28")
spawn("sx_remove_floor", 20,18,3, "sx_remove_floor_29")
spawn("sx_remove_floor", 15,18,3, "sx_remove_floor_31")
spawn("sx_remove_floor", 15,19,0, "sx_remove_floor_32")
spawn("sx_remove_floor", 15,20,0, "sx_remove_floor_33")
spawn("sx_remove_floor", 15,21,0, "sx_remove_floor_34")
spawn("sx_remove_floor", 16,19,3, "sx_remove_floor_35")
spawn("sx_remove_floor", 16,20,3, "sx_remove_floor_36")
spawn("sx_remove_floor", 16,21,2, "sx_remove_floor_37")
spawn("sx_remove_floor", 16,22,0, "sx_remove_floor_39")
spawn("sx_remove_floor", 15,22,3, "sx_remove_floor_40")
spawn("sx_remove_floor", 14,22,1, "sx_remove_floor_41")
spawn("sx_remove_floor", 13,23,2, "sx_remove_floor_42")
spawn("sx_remove_floor", 14,23,3, "sx_remove_floor_43")
spawn("sx_remove_floor", 15,23,1, "sx_remove_floor_45")
spawn("sx_remove_floor", 16,23,3, "sx_remove_floor_46")
spawn("sx_remove_floor", 16,24,3, "sx_remove_floor_47")
spawn("sx_remove_floor", 15,24,3, "sx_remove_floor_48")
spawn("sx_remove_floor", 14,24,2, "sx_remove_floor_49")
spawn("sx_remove_floor", 16,25,1, "sx_remove_floor_50")
spawn("sx_ceiling_lamp_outside", 15,15,3, "sx_ceiling_lamp_outside_1")
spawn("sx_ceiling_lamp_outside", 19,18,1, "sx_ceiling_lamp_outside_2")
spawn("sx_ceiling_lamp_outside", 16,23,0, "sx_ceiling_lamp_outside_3")
spawn("sx_remove_ceiling", 20,14,0, "sx_remove_ceiling_94")
spawn("sx_remove_ceiling", 19,14,0, "sx_remove_ceiling_165")
spawn("sx_remove_ceiling", 20,15,0, "sx_remove_ceiling_767")
spawn("sx_simple_stairs_down", 20,16,2, "sx_simple_stairs_down_1")
spawn("teleporter", 20,17,0, "teleporter_1")
	:setTriggeredByParty(true)
	:setTriggeredByMonster(false)
	:setTriggeredByItem(false)
	:setTeleportTarget(20,15,0,2)
	:setInvisible(true)
	:setSilent(true)
	:setHideLight(true)
	:setScreenFlash(false)
spawn("sx_remove_floor", 20,17,3, "sx_remove_floor_1223")
spawn("castle_exterior_pillar_big", 22,16,0, "castle_exterior_pillar_big_28")
spawn("castle_exterior_pillar_big", 21,16,0, "castle_exterior_pillar_big_29")
spawn("castle_exterior_pillar_big", 21,17,0, "castle_exterior_pillar_big_30")
spawn("castle_exterior_pillar_big", 22,17,0, "castle_exterior_pillar_big_31")
spawn("castle_exterior_wall", 20,16,3, "castle_exterior_wall_5")
spawn("castle_exterior_wall", 20,16,1, "castle_exterior_wall_6")
spawn("castle_exterior_pillar_big", 19,21,0, "castle_exterior_pillar_big_65")
spawn("sx_remove_ceiling", 12,16,2, "sx_remove_ceiling_56")
spawn("sx_remove_ceiling", 12,17,2, "sx_remove_ceiling_60")
spawn("sx_remove_ceiling", 12,18,2, "sx_remove_ceiling_61")
spawn("sx_remove_wall", 12,18,3, "sx_remove_wall_1")
spawn("sx_remove_wall", 12,16,3, "sx_remove_wall_3")
spawn("sx_remove_wall", 12,15,3, "sx_remove_wall_4")
spawn("sx_remove_wall", 12,14,3, "sx_remove_wall_5")
spawn("sx_remove_wall", 12,13,3, "sx_remove_wall_6")
spawn("sx_remove_wall", 12,12,3, "sx_remove_wall_7")
spawn("sx_remove_wall", 12,12,0, "sx_remove_wall_8")
spawn("sx_remove_wall", 13,12,0, "sx_remove_wall_9")
spawn("sx_remove_wall", 14,12,0, "sx_remove_wall_10")
spawn("sx_remove_wall", 15,12,0, "sx_remove_wall_11")
spawn("sx_remove_wall", 16,12,0, "sx_remove_wall_12")
spawn("sx_remove_wall", 17,12,0, "sx_remove_wall_13")
spawn("sx_remove_wall", 18,12,0, "sx_remove_wall_14")
spawn("sx_remove_wall", 18,12,1, "sx_remove_wall_15")
spawn("sx_remove_wall", 18,13,1, "sx_remove_wall_16")
spawn("sx_remove_wall", 19,14,0, "sx_remove_wall_17")
spawn("sx_remove_wall", 20,14,0, "sx_remove_wall_18")
spawn("sx_remove_wall", 20,14,1, "sx_remove_wall_19")
spawn("sx_remove_wall", 21,15,0, "sx_remove_wall_20")
spawn("sx_remove_wall", 22,17,1, "sx_remove_wall_21")
spawn("sx_remove_wall", 21,18,1, "sx_remove_wall_22")
spawn("sx_remove_wall", 21,19,1, "sx_remove_wall_23")
spawn("sx_remove_wall", 21,19,2, "sx_remove_wall_24")
spawn("sx_remove_wall", 20,19,2, "sx_remove_wall_25")
spawn("sx_remove_wall", 19,20,1, "sx_remove_wall_26")
spawn("sx_remove_wall", 18,21,2, "sx_remove_wall_27")
spawn("sx_remove_wall", 17,22,1, "sx_remove_wall_28")
spawn("sx_remove_wall", 17,23,1, "sx_remove_wall_29")
spawn("sx_remove_wall", 17,24,1, "sx_remove_wall_30")
spawn("sx_remove_wall", 17,25,1, "sx_remove_wall_31")
spawn("sx_remove_wall", 17,26,1, "sx_remove_wall_32")
spawn("sx_remove_wall", 17,26,2, "sx_remove_wall_33")
spawn("sx_remove_wall", 16,26,2, "sx_remove_wall_34")
spawn("sx_remove_wall", 15,26,2, "sx_remove_wall_35")
spawn("sx_remove_wall", 15,26,3, "sx_remove_wall_36")
spawn("sx_remove_wall", 14,25,2, "sx_remove_wall_37")
spawn("sx_remove_wall", 13,25,2, "sx_remove_wall_38")
spawn("sx_remove_wall", 13,25,3, "sx_remove_wall_39")
spawn("sx_remove_wall", 12,24,2, "sx_remove_wall_40")
spawn("sx_remove_wall", 12,24,3, "sx_remove_wall_41")
spawn("sx_remove_wall", 12,23,3, "sx_remove_wall_42")
spawn("sx_remove_wall", 12,22,3, "sx_remove_wall_43")
spawn("sx_remove_wall", 12,22,0, "sx_remove_wall_44")
spawn("sx_remove_wall", 13,21,3, "sx_remove_wall_45")
spawn("sx_remove_wall", 13,21,0, "sx_remove_wall_46")
spawn("sx_remove_wall", 14,20,3, "sx_remove_wall_47")
spawn("sx_remove_wall", 14,19,3, "sx_remove_wall_48")
spawn("sx_remove_wall", 13,18,2, "sx_remove_wall_49")
spawn("sx_remove_wall", 12,18,2, "sx_remove_wall_50")
spawn("sx_remove_ceiling", 14,13,0, "sx_remove_ceiling_57")
spawn("sx_remove_floor", 14,13,3, "sx_remove_floor_44")
spawn("sx_remove_wall", 12,17,3, "sx_remove_wall_51")
spawn("sx_outwall_pillarkiller", 12,18,3, "sx_outwall_pillarkiller_1")
spawn("sx_outwall_pillarkiller", 12,16,3, "sx_outwall_pillarkiller_3")
spawn("sx_outwall_pillarkiller", 12,14,3, "sx_outwall_pillarkiller_4")
spawn("sx_outwall_pillarkiller", 12,12,3, "sx_outwall_pillarkiller_5")
spawn("sx_outwall_pillarkiller", 13,12,0, "sx_outwall_pillarkiller_6")
spawn("sx_outwall_pillarkiller", 15,12,0, "sx_outwall_pillarkiller_7")
spawn("sx_outwall_pillarkiller", 17,12,0, "sx_outwall_pillarkiller_8")
spawn("sx_outwall_pillarkiller", 18,12,1, "sx_outwall_pillarkiller_9")
spawn("sx_outwall_pillarkiller", 19,14,0, "sx_outwall_pillarkiller_10")
spawn("sx_outwall_pillarkiller", 20,14,1, "sx_outwall_pillarkiller_11")
spawn("sx_outwall_pillarkiller", 21,18,1, "sx_outwall_pillarkiller_12")
spawn("sx_outwall_pillarkiller", 21,19,2, "sx_outwall_pillarkiller_13")
spawn("sx_outwall_pillarkiller", 20,19,2, "sx_outwall_pillarkiller_14")
spawn("sx_outwall_pillarkiller", 17,22,1, "sx_outwall_pillarkiller_15")
spawn("sx_outwall_pillarkiller", 17,24,1, "sx_outwall_pillarkiller_16")
spawn("sx_outwall_pillarkiller", 17,26,1, "sx_outwall_pillarkiller_17")
spawn("sx_outwall_pillarkiller", 16,26,2, "sx_outwall_pillarkiller_18")
spawn("sx_outwall_pillarkiller", 15,26,3, "sx_outwall_pillarkiller_19")
spawn("sx_outwall_pillarkiller", 13,25,2, "sx_outwall_pillarkiller_20")
spawn("sx_outwall_pillarkiller", 12,24,2, "sx_outwall_pillarkiller_21")
spawn("sx_outwall_pillarkiller", 12,23,3, "sx_outwall_pillarkiller_22")
spawn("sx_outwall_pillarkiller", 12,22,0, "sx_outwall_pillarkiller_23")
spawn("sx_outwall_pillarkiller", 13,21,0, "sx_outwall_pillarkiller_24")
spawn("sx_outwall_pillarkiller", 14,19,3, "sx_outwall_pillarkiller_25")
spawn("sx_outwall_pillarkiller", 12,18,2, "sx_outwall_pillarkiller_26")
spawn("sx_remove_floor", 19,21,0, "sx_remove_floor_38")
spawn("sx_remove_ceiling", 19,21,1, "sx_remove_ceiling_59")
spawn("sx_remove_floor", 18,21,0, "sx_remove_floor_51")
spawn("sx_remove_ceiling", 18,21,1, "sx_remove_ceiling_62")
spawn("sx_remove_floor", 19,20,0, "sx_remove_floor_52")
spawn("sx_remove_ceiling", 19,20,1, "sx_remove_ceiling_63")
spawn("sx_outwall_pillarkiller", 18,21,2, "sx_outwall_pillarkiller_33")
spawn("sx_remove_wall", 19,21,1, "sx_remove_wall_64")
spawn("sx_remove_wall", 19,21,2, "sx_remove_wall_65")
spawn("sx_outwall_pillarkiller", 19,21,1, "sx_outwall_pillarkiller_34")
spawn("sx_remove_wall", 22,17,2, "sx_remove_wall_63")
spawn("sx_remove_wall", 22,16,1, "sx_remove_wall_66")
spawn("sx_remove_wall", 22,15,1, "sx_remove_wall_67")
spawn("sx_remove_wall", 22,15,0, "sx_remove_wall_68")
spawn("sx_outwall_pillarkiller", 22,15,0, "sx_outwall_pillarkiller_35")
spawn("sx_outwall_pillarkiller", 22,16,1, "sx_outwall_pillarkiller_36")
spawn("sx_outwall_pillarkiller", 22,17,2, "sx_outwall_pillarkiller_37")
spawn("sx_remove_floor", 21,15,2, "sx_remove_floor_53")
spawn("sx_remove_floor", 22,15,2, "sx_remove_floor_54")
spawn("sx_remove_floor", 22,16,2, "sx_remove_floor_55")
spawn("sx_remove_floor", 22,17,2, "sx_remove_floor_56")
spawn("sx_remove_floor", 14,20,0, "sx_remove_floor_86")
spawn("sx_remove_floor", 14,21,0, "sx_remove_floor_87")
spawn("sx_remove_floor", 13,21,0, "sx_remove_floor_88")
spawn("castle_exterior_parapet_pillar", 18,18,2, "castle_exterior_parapet_pillar_1")
spawn("castle_exterior_parapet_pillar", 18,13,1, "castle_exterior_parapet_pillar_2")
spawn("castle_exterior_parapet", 17,17,1, "castle_exterior_parapet_1")
spawn("castle_exterior_parapet", 17,16,1, "castle_exterior_parapet_3")
spawn("castle_exterior_parapet", 17,15,1, "castle_exterior_parapet_4")
spawn("castle_exterior_parapet", 17,14,1, "castle_exterior_parapet_5")
spawn("castle_exterior_parapet", 17,13,1, "castle_exterior_parapet_6")
spawn("castle_exterior_parapet", 18,12,2, "castle_exterior_parapet_7")
spawn("castle_exterior_parapet", 19,13,3, "castle_exterior_parapet_8")
spawn("castle_exterior_parapet", 19,13,2, "castle_exterior_parapet_9")
spawn("castle_exterior_parapet", 19,13,2, "castle_exterior_parapet_10")
spawn("castle_exterior_parapet", 20,13,2, "castle_exterior_parapet_11")
spawn("castle_exterior_parapet", 21,14,3, "castle_exterior_parapet_12")
spawn("castle_exterior_parapet", 21,15,3, "castle_exterior_parapet_13")
spawn("castle_exterior_parapet_pillar", 19,13,1, "castle_exterior_parapet_pillar_4")
spawn("castle_exterior_parapet_pillar", 19,14,1, "castle_exterior_parapet_pillar_5")
spawn("castle_exterior_parapet_pillar", 21,14,1, "castle_exterior_parapet_pillar_7")
spawn("sx_remove_ceiling", 21,15,0, "sx_remove_ceiling_199")
spawn("sx_remove_ceiling", 22,15,0, "sx_remove_ceiling_200")
spawn("sx_remove_ceiling", 22,16,0, "sx_remove_ceiling_201")
spawn("sx_remove_ceiling", 22,17,0, "sx_remove_ceiling_202")
spawn("castle_exterior_parapet", 18,17,2, "castle_exterior_parapet_14")
spawn("castle_exterior_parapet", 19,17,2, "castle_exterior_parapet_15")
spawn("castle_exterior_parapet", 20,17,3, "castle_exterior_parapet_16")
spawn("castle_exterior_parapet_pillar", 20,18,2, "castle_exterior_parapet_pillar_6")
spawn("castle_exterior_parapet_pillar", 18,14,1, "castle_exterior_parapet_pillar_8")
spawn("castle_exterior_parapet_pillar", 18,15,1, "castle_exterior_parapet_pillar_9")
spawn("castle_exterior_parapet_pillar", 18,16,1, "castle_exterior_parapet_pillar_10")
spawn("castle_exterior_parapet_pillar", 18,17,1, "castle_exterior_parapet_pillar_11")

--- level 3 ---

mapName("Castle Level 3")
setWallSet("castle_exterior")
playStream("assets/samples/music/dungeon_ambient.ogg")
mapDesc([[
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
###########.........############
###########.#######.############
###########.#.....#...##########
###########.#.....###.##########
#########...#.....###..#########
#########...#.....##.#.#########
#########...#.....##.#.#########
######......###.#....#.#########
######........#..#####.#########
######...........##....#########
######...........#..############
######......##...#.#############
######......#....#.#############
###########.##...#.#############
###########..###.#.#############
############...###.#############
##############.....#############
################################
################################
################################
################################
]])
spawn("torch_holder", 14,13,0, "torch_holder_1")
	:addTorch()
spawn("torch_holder", 17,16,1, "torch_holder_2")
	:addTorch()
spawn("castle_exterior_pillar_big", 15,13,2, "castle_exterior_pillar_big_1")
spawn("castle_exterior_pillar_big", 13,13,2, "castle_exterior_pillar_big_3")
spawn("castle_exterior_pillar_big", 13,15,0, "castle_exterior_pillar_big_4")
spawn("castle_exterior_pillar_big", 13,18,2, "castle_exterior_pillar_big_5")
spawn("castle_exterior_pillar_big", 15,18,2, "castle_exterior_pillar_big_6")
spawn("castle_exterior_pillar_big", 16,18,2, "castle_exterior_pillar_big_7")
spawn("castle_exterior_pillar_big", 17,18,2, "castle_exterior_pillar_big_8")
spawn("castle_exterior_pillar_big", 18,18,2, "castle_exterior_pillar_big_9")
spawn("castle_exterior_pillar_big", 18,13,2, "castle_exterior_pillar_big_10")
spawn("castle_exterior_pillar_big", 20,18,2, "castle_exterior_pillar_big_12")
spawn("castle_exterior_pillar_big", 21,19,2, "castle_exterior_pillar_big_13")
spawn("castle_exterior_pillar_big", 21,17,2, "castle_exterior_pillar_big_14")
spawn("castle_exterior_pillar_big", 20,17,2, "castle_exterior_pillar_big_15")
spawn("castle_exterior_pillar_big", 17,19,2, "castle_exterior_pillar_big_11")
spawn("script_entity", 18,14,0, "dungeonCompiler")
	:setSource("\9-- ==========================================================================\
\9--                 MULTI-LEVEL DUNGEON COMPILER\
\9-- ==========================================================================\
\
\
\9-- Wallset Definition\
\9-- ************************************\
\
\
\9wallset = {\
\9\9_wall  = {\
\9\9\9{1, \"_castle_exterior_wall_1above\"},\
\9\9\9{2, \"_castle_exterior_wall_2above\"},\
\9\9\9{3, \"_castle_exterior_wall_3above\"},\
\9\9\9{-1, \"_castle_exterior_wall_1below\"},\
\9\9\9{-2, \"_castle_exterior_wall_2below\"},\
\9\9},\
\9\9_pillar = {\
\9\9\9{1, \"_castle_exterior_pillar_small_1above\"},\
\9\9\9{2, \"_castle_exterior_pillar_small_2above\"},\
\9\9\9{-1, \"_castle_exterior_pillar_small_1below\"},\
\9\9},\
\9\9_floor = {\
\9\9\9{-1, \"_castle_exterior_floor_1below\"},\
\9\9},\
\9\9castle_exterior_pillar_big = {\
\9\9\9{1, \"_castle_exterior_pillar_big_1above\"},\
\9\9\9{2, \"_castle_exterior_pillar_big_2above\"},\
\9\9\9{3, \"_castle_exterior_pillar_big_3above\"},\
\9\9\9{-1, \"_castle_exterior_pillar_big_1below\"},\
\9\9},\
\9\9castle_exterior_pillar_small = {\
\9\9\9{1, \"_castle_exterior_pillar_small_1above\"},\
\9\9\9{2, \"_castle_exterior_pillar_small_2above\"},\
\9\9\9{-1, \"_castle_exterior_pillar_small_1below\"},\
\9\9},\
\9\9castle_exterior_wall_windows = {\
\9\9\9{1, \"_castle_exterior_wall_windows_1above\"},\
\9\9\9{2, \"_castle_exterior_wall_windows_2above\"},\
\9\9\9{-1, \"_castle_exterior_wall_windows_1below\"},\
\9\9},\
\9\9castle_exterior_parapet = {\
\9\9\9{1, \"_castle_exterior_parapet_1above\"},\
\9\9\9{2, \"_castle_exterior_parapet_2above\"},\
\9\9\9{3, \"_castle_exterior_parapet_3above\"},\
\9\9\9{-1, \"_castle_exterior_parapet_1below\"},\
\9\9\9{-2, \"_castle_exterior_parapet_2below\"},\
\9\9},\
\9\9castle_exterior_parapet_pillar = {\
\9\9\9{1, \"_castle_exterior_parapet_pillar_1above\"},\
\9\9\9{2, \"_castle_exterior_parapet_pillar_2above\"},\
\9\9\9{3, \"_castle_exterior_parapet_pillar_3above\"},\
\9\9\9{-1, \"_castle_exterior_parapet_pillar_1below\"},\
\9\9\9{-2, \"_castle_exterior_parapet_pillar_2below\"},\
\9\9},\9\9\9\9\
\9}\
\
\
\9-- Main Compiler Module\
\9-- ************************************\
\
\9function compileDungeon(firstLevel, lastLevel)\
\9\9local levels = getMaxLevels()\
\9\9for level = 1,levels do\
\9\9\9for x = 0,31 do\
\9\9\9\9for y = 0,31 do\
\9\9\9\9\9for l = firstLevel, lastLevel do\
\9\9\9\9\9\9if l ~= level then\
\9\9\9\9\9\9\9local stairsCheck = false\
\9\9\9\9\9\9\9-- Create Objects\
\9\9\9\9\9\9\9for i in entitiesAt(l, x, y) do\
\9\9\9\9\9\9\9\9-- Spawn multi-level architecture\
\9\9\9\9\9\9\9\9for object, defs in pairs(dungeonCompiler.wallset) do\
\9\9\9\9\9\9\9\9\9if i.name == object then\
\9\9\9\9\9\9\9\9\9\9local objToSpawn\
\9\9\9\9\9\9\9\9\9\9for _, spawnObjects in ipairs(defs) do\
\9\9\9\9\9\9\9\9\9\9\9if spawnObjects[1] == level - l then\
\9\9\9\9\9\9\9\9\9\9\9\9objToSpawn = spawnObjects[2]\
\9\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9\9if objToSpawn then\
\9\9\9\9\9\9\9\9\9\9\9spawn(objToSpawn, level, x, y, i.facing)\
\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9-- Spawn sx_remove_floor elements where not already present\
\9\9\9\9\9\9\9\9if l > firstLevel then\
\9\9\9\9\9\9\9\9\9if i.name == \"sx_remove_ceiling\" then\
\9\9\9\9\9\9\9\9\9\9local removeFloorFound = false\
\9\9\9\9\9\9\9\9\9\9for j in entitiesAt(l-1, x, y) do\
\9\9\9\9\9\9\9\9\9\9\9if j.name == \"sx_remove_floor\" then\
\9\9\9\9\9\9\9\9\9\9\9\9removeFloorFound = true\
\9\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9\9if not(removeFloorFound) then\
\9\9\9\9\9\9\9\9\9\9\9spawn(\"sx_remove_floor\", l-1, x, y, 0)\
\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9-- Create Walls\
\9\9\9\9\9\9\9if isWall(l, x, y) then\
\9\9\9\9\9\9\9\9for wallDir = 0, 3 do\
\9\9\9\9\9\9\9\9\9local dx, dy = getForward(wallDir)\
\9\9\9\9\9\9\9\9\9local wallRemover = false\
\9\9\9\9\9\9\9\9\9local isFloor = false\
\9\9\9\9\9\9\9\9\9for i in entitiesAt(l, x+dx, y+dy) do\
\9\9\9\9\9\9\9\9\9\9if i.name == \"sx_remove_wall\" and (i.facing+2)%4 == wallDir then\
\9\9\9\9\9\9\9\9\9\9\9wallRemover = true\
\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9if l > level then\
\9\9\9\9\9\9\9\9\9\9isFloor = true\
\9\9\9\9\9\9\9\9\9\9for i in entitiesAt(l-1, x+dx, y+dy) do\
\9\9\9\9\9\9\9\9\9\9\9if i.name == \"sx_remove_floor\" then\
\9\9\9\9\9\9\9\9\9\9\9\9isFloor = false\
\9\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9if not(isWall(l, x+dx, y+dy)) and not(wallRemover) and not(isFloor) then\
\9\9\9\9\9\9\9\9\9\9local objToSpawn\
\9\9\9\9\9\9\9\9\9\9for _, spawnObjects in ipairs(dungeonCompiler.wallset._wall) do\
\9\9\9\9\9\9\9\9\9\9\9if spawnObjects[1] == level - l then\
\9\9\9\9\9\9\9\9\9\9\9\9objToSpawn = spawnObjects[2]\
\9\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9\9if objToSpawn then\
\9\9\9\9\9\9\9\9\9\9\9spawn(objToSpawn, level, x+dx, y+dy, (wallDir+2)%4)\
\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9\9local px, py = getForward((wallDir+1)%4)\
\9\9\9\9\9\9\9\9\9\9-- Create pillars\
\9\9\9\9\9\9\9\9\9\9objToSpawn = nil\
\9\9\9\9\9\9\9\9\9\9for _, spawnObjects in ipairs(dungeonCompiler.wallset._pillar) do\
\9\9\9\9\9\9\9\9\9\9\9if spawnObjects[1] == level - l then\
\9\9\9\9\9\9\9\9\9\9\9\9objToSpawn = spawnObjects[2]\
\9\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9\9if objToSpawn then\
\9\9\9\9\9\9\9\9\9\9\9local p1x, p1y, p2x, p2y\
\9\9\9\9\9\9\9\9\9\9\9local wx, wy = getForward((wallDir+1)%4)\
\9\9\9\9\9\9\9\9\9\9\9if wallDir == 0 then\
\9\9\9\9\9\9\9\9\9\9\9\9p1x, p1y = x, y\
\9\9\9\9\9\9\9\9\9\9\9\9p2x, p2y = x+wx, y+wy\
\9\9\9\9\9\9\9\9\9\9\9elseif wallDir == 1 then\
\9\9\9\9\9\9\9\9\9\9\9\9p1x, p1y = x+dx, y+dy\
\9\9\9\9\9\9\9\9\9\9\9\9p2x, p2y = x+dx+wx, y+dy+wy\
\9\9\9\9\9\9\9\9\9\9\9elseif wallDir == 2 then\
\9\9\9\9\9\9\9\9\9\9\9\9p1x, p1y = x+dx, y+dy\
\9\9\9\9\9\9\9\9\9\9\9\9p2x, p2y = x+dx-wx, y+dy-wy\
\9\9\9\9\9\9\9\9\9\9\9elseif wallDir == 3 then\
\9\9\9\9\9\9\9\9\9\9\9\9p1x, p1y = x, y\
\9\9\9\9\9\9\9\9\9\9\9\9p2x, p2y = x-wx, y-wy\
\9\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9\9\9if not(findEntity(\"pillar.\"..level..\".\"..l..\".\"..p1x..\".\"..p1y)) then\
\9\9\9\9\9\9\9\9\9\9\9\9spawn(objToSpawn, level, p1x, p1y, wallDir, \"pillar.\"..level..\".\"..l..\".\"..p1x..\".\"..p1y)\
\9\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9\9\9if not(findEntity(\"pillar.\"..level..\".\"..l..\".\"..p2x..\".\"..p2y)) then\
\9\9\9\9\9\9\9\9\9\9\9\9spawn(objToSpawn, level, p2x, p2y, wallDir, \"pillar.\"..level..\".\"..l..\".\"..p2x..\".\"..p2y)\
\9\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9--Create floor\
\9\9\9\9\9\9\9if l > level then\
\9\9\9\9\9\9\9\9local removeFloorFound = false\
\9\9\9\9\9\9\9\9for j in entitiesAt(l, x, y) do\
\9\9\9\9\9\9\9\9\9if j.name == \"sx_remove_floor\" then\
\9\9\9\9\9\9\9\9\9\9removeFloorFound = true\
\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9if (l == lastLevel or not(removeFloorFound)) and not(isWall(l, x, y)) then\
\9\9\9\9\9\9\9\9\9local objToSpawn\
\9\9\9\9\9\9\9\9\9for _, spawnObjects in ipairs(dungeonCompiler.wallset._floor) do\
\9\9\9\9\9\9\9\9\9\9if spawnObjects[1] == level - l then\
\9\9\9\9\9\9\9\9\9\9\9objToSpawn = spawnObjects[2]\
\9\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9\9if objToSpawn then\
\9\9\9\9\9\9\9\9\9\9spawn(objToSpawn, level, x, y, 0)\
\9\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9\9end\
\9\9\9\9\9\9\9end\9\9\9\9\9\9\
\9\9\9\9\9\9end\
\9\9\9\9\9end\
\9\9\9\9end\
\9\9\9end\
\9\9end\
\9end\
\
\9compileDungeon(1,4)")
spawn("sx_remove_ceiling", 13,13,1, "sx_remove_ceiling_1")
spawn("sx_remove_ceiling", 13,14,1, "sx_remove_ceiling_2")
spawn("sx_remove_ceiling", 13,15,2, "sx_remove_ceiling_3")
spawn("sx_remove_ceiling", 13,16,1, "sx_remove_ceiling_4")
spawn("sx_remove_ceiling", 13,17,0, "sx_remove_ceiling_5")
spawn("sx_remove_ceiling", 14,17,3, "sx_remove_ceiling_6")
spawn("sx_remove_ceiling", 14,16,0, "sx_remove_ceiling_7")
spawn("sx_remove_ceiling", 14,15,0, "sx_remove_ceiling_8")
spawn("sx_remove_ceiling", 14,14,0, "sx_remove_ceiling_9")
spawn("sx_remove_ceiling", 14,13,2, "sx_remove_ceiling_10")
spawn("sx_remove_ceiling", 15,13,1, "sx_remove_ceiling_11")
spawn("sx_remove_ceiling", 16,13,1, "sx_remove_ceiling_12")
spawn("sx_remove_ceiling", 17,13,2, "sx_remove_ceiling_13")
spawn("sx_remove_ceiling", 17,14,1, "sx_remove_ceiling_14")
spawn("sx_remove_ceiling", 16,14,1, "sx_remove_ceiling_15")
spawn("sx_remove_ceiling", 15,14,2, "sx_remove_ceiling_16")
spawn("sx_remove_ceiling", 15,15,2, "sx_remove_ceiling_17")
spawn("sx_remove_ceiling", 15,16,0, "sx_remove_ceiling_18")
spawn("sx_remove_ceiling", 15,17,1, "sx_remove_ceiling_19")
spawn("sx_remove_ceiling", 16,17,3, "sx_remove_ceiling_20")
spawn("sx_remove_ceiling", 16,15,2, "sx_remove_ceiling_21")
spawn("sx_remove_ceiling", 17,15,2, "sx_remove_ceiling_22")
spawn("sx_remove_ceiling", 17,16,0, "sx_remove_ceiling_23")
spawn("sx_remove_ceiling", 16,16,1, "sx_remove_ceiling_24")
spawn("sx_remove_ceiling", 17,17,2, "sx_remove_ceiling_25")
spawn("sx_remove_ceiling", 17,18,2, "sx_remove_ceiling_26")
spawn("sx_remove_ceiling", 18,18,2, "sx_remove_ceiling_27")
spawn("sx_remove_ceiling", 20,18,2, "sx_remove_ceiling_29")
spawn("sx_remove_ceiling", 20,17,0, "sx_remove_ceiling_30")
spawn("sx_remove_ceiling", 15,18,2, "sx_remove_ceiling_31")
spawn("sx_remove_ceiling", 15,19,3, "sx_remove_ceiling_32")
spawn("sx_remove_ceiling", 15,20,2, "sx_remove_ceiling_33")
spawn("sx_remove_ceiling", 15,21,1, "sx_remove_ceiling_34")
spawn("sx_remove_ceiling", 15,22,1, "sx_remove_ceiling_35")
spawn("sx_remove_ceiling", 14,22,1, "sx_remove_ceiling_36")
spawn("sx_remove_ceiling", 14,23,1, "sx_remove_ceiling_37")
spawn("sx_remove_ceiling", 15,23,3, "sx_remove_ceiling_38")
spawn("sx_remove_ceiling", 15,24,3, "sx_remove_ceiling_39")
spawn("sx_remove_ceiling", 14,24,1, "sx_remove_ceiling_40")
spawn("sx_remove_ceiling", 13,23,2, "sx_remove_ceiling_41")
spawn("sx_remove_ceiling", 16,25,0, "sx_remove_ceiling_42")
spawn("sx_remove_ceiling", 16,24,3, "sx_remove_ceiling_43")
spawn("sx_remove_ceiling", 16,23,0, "sx_remove_ceiling_44")
spawn("sx_remove_ceiling", 16,21,2, "sx_remove_ceiling_45")
spawn("sx_remove_ceiling", 16,22,2, "sx_remove_ceiling_46")
spawn("sx_remove_ceiling", 16,20,2, "sx_remove_ceiling_47")
spawn("sx_remove_ceiling", 16,19,0, "sx_remove_ceiling_48")
spawn("sx_remove_ceiling", 11,18,3, "sx_remove_ceiling_804")
spawn("sx_remove_ceiling", 11,21,3, "sx_remove_ceiling_812")
spawn("sx_remove_floor", 11,21,3, "sx_remove_floor_721")
spawn("sx_remove_ceiling", 11,22,3, "sx_remove_ceiling_816")
spawn("sx_remove_floor", 11,22,3, "sx_remove_floor_725")
spawn("sx_remove_ceiling", 11,23,3, "sx_remove_ceiling_820")
spawn("sx_remove_ceiling", 11,24,3, "sx_remove_ceiling_824")
spawn("sx_remove_ceiling", 12,19,3, "sx_remove_ceiling_1200")
spawn("sx_remove_ceiling", 13,19,3, "sx_remove_ceiling_1201")
spawn("sx_remove_ceiling", 13,20,3, "sx_remove_ceiling_1202")
spawn("sx_remove_ceiling", 12,20,3, "sx_remove_ceiling_1203")
spawn("sx_remove_ceiling", 12,21,3, "sx_remove_ceiling_1204")
spawn("sx_simple_stairs_up", 20,17,0, "sx_simple_stairs_up_1")
spawn("castle_exterior_wall", 20,17,3, "castle_exterior_wall_1")
spawn("castle_exterior_wall", 20,17,1, "castle_exterior_wall_2")
spawn("castle_exterior_wall", 20,16,3, "castle_exterior_wall_3")
spawn("castle_exterior_wall", 20,16,1, "castle_exterior_wall_4")
spawn("sx_remove_ceiling", 20,16,3, "sx_remove_ceiling_1346")
spawn("castle_exterior_pillar_big", 14,22,3, "castle_exterior_pillar_big_32")
spawn("castle_exterior_pillar_big", 14,23,3, "castle_exterior_pillar_big_33")
spawn("castle_exterior_pillar_big", 13,23,1, "castle_exterior_pillar_big_34")
spawn("castle_exterior_pillar_big", 13,24,3, "castle_exterior_pillar_big_35")
spawn("castle_exterior_pillar_big", 14,24,3, "castle_exterior_pillar_big_36")
spawn("castle_exterior_pillar_big", 14,25,2, "castle_exterior_pillar_big_37")
spawn("castle_exterior_pillar_big", 16,25,3, "castle_exterior_pillar_big_38")
spawn("castle_exterior_pillar_big", 16,26,1, "castle_exterior_pillar_big_39")
spawn("castle_exterior_pillar_big", 17,26,3, "castle_exterior_pillar_big_40")
spawn("castle_exterior_pillar_big", 17,21,3, "castle_exterior_pillar_big_41")
spawn("castle_exterior_pillar_big", 17,23,1, "castle_exterior_pillar_big_42")
spawn("castle_exterior_pillar_big", 18,21,3, "castle_exterior_pillar_big_43")
spawn("castle_exterior_pillar_big", 19,21,3, "castle_exterior_pillar_big_44")
spawn("castle_exterior_pillar_big", 19,20,3, "castle_exterior_pillar_big_45")
spawn("castle_exterior_pillar_big", 22,20,1, "castle_exterior_pillar_big_46")
spawn("castle_exterior_pillar_big", 22,16,2, "castle_exterior_pillar_big_47")
spawn("castle_exterior_pillar_big", 18,27,0, "castle_exterior_pillar_big_48")
spawn("castle_exterior_pillar_big", 15,27,2, "castle_exterior_pillar_big_49")
spawn("castle_exterior_pillar_big", 15,26,2, "castle_exterior_pillar_big_50")
spawn("castle_exterior_pillar_big", 13,25,1, "castle_exterior_pillar_big_52")
spawn("castle_exterior_pillar_big", 12,25,0, "castle_exterior_pillar_big_53")
spawn("castle_exterior_pillar_big", 12,22,1, "castle_exterior_pillar_big_54")
spawn("castle_exterior_pillar_big", 15,20,0, "castle_exterior_pillar_big_55")
spawn("castle_exterior_pillar_big", 14,20,1, "castle_exterior_pillar_big_57")
spawn("castle_exterior_pillar_big", 14,19,3, "castle_exterior_pillar_big_58")
spawn("castle_exterior_pillar_big", 12,19,3, "castle_exterior_pillar_big_59")
spawn("castle_exterior_pillar_big", 12,12,3, "castle_exterior_pillar_big_60")
spawn("castle_exterior_pillar_big", 19,12,2, "castle_exterior_pillar_big_61")
spawn("castle_exterior_pillar_big", 19,14,1, "castle_exterior_pillar_big_62")
spawn("castle_exterior_pillar_big", 21,14,2, "castle_exterior_pillar_big_63")
spawn("castle_exterior_pillar_big", 21,16,3, "castle_exterior_pillar_big_64")
spawn("teleporter", 20,16,2, "teleporter_3")
	:setTriggeredByParty(true)
	:setTriggeredByMonster(false)
	:setTriggeredByItem(false)
	:setTeleportTarget(20,18,2,3)
	:setInvisible(true)
	:setSilent(true)
	:setHideLight(true)
	:setScreenFlash(false)
spawn("sx_remove_ceiling", 19,18,2, "sx_remove_ceiling_109")
spawn("sx_ceiling_lamp_outside", 15,15,3, "sx_ceiling_lamp_outside_4")
spawn("sx_ceiling_lamp_outside", 15,22,0, "sx_ceiling_lamp_outside_5")
spawn("sx_ceiling_lamp_outside", 19,18,0, "sx_ceiling_lamp_outside_6")
spawn("sx_remove_ceiling", 11,20,3, "sx_remove_ceiling_58")
spawn("sx_remove_floor", 11,20,3, "sx_remove_floor_30")
spawn("sx_remove_wall", 11,24,3, "sx_remove_wall_83")
spawn("script_entity", 15,9,3, "script_entity_1")
	:setSource("function particleTest()\
\9spawn(\"fx\", party.level, party.x, party.y, 0)\
\9\9:setParticleSystem(\"sky_particle\")\
\9\9:setLight(0, 0, 0, 0, 0, 10000000, false)\
\9\9:translate(0, 12, 0)\
end\
\
")
spawn("sx_simple_stairs_down", 13,20,3, "sx_simple_stairs_down_2")
spawn("sx_simple_stairs_down", 13,21,3, "sx_simple_stairs_down_3")
spawn("sx_remove_ceiling", 13,21,3, "sx_remove_ceiling_90")
spawn("sx_remove_ceiling", 14,21,3, "sx_remove_ceiling_91")
spawn("sx_remove_ceiling", 14,20,3, "sx_remove_ceiling_92")
spawn("sx_remove_floor", 12,20,3, "sx_remove_floor_57")
spawn("sx_remove_floor", 12,21,3, "sx_remove_floor_58")
spawn("castle_exterior_wall", 13,21,2, "castle_exterior_wall_7")
spawn("sx_remove_floor", 13,21,3, "sx_remove_floor_59")
spawn("sx_remove_floor", 13,20,2, "sx_remove_floor_60")
spawn("teleporter", 12,20,1, "teleporter_4")
	:setTriggeredByParty(true)
	:setTriggeredByMonster(false)
	:setTriggeredByItem(false)
	:setTeleportTarget(14,20,1,3)
	:setInvisible(true)
	:setSilent(true)
	:setHideLight(true)
	:setScreenFlash(false)
spawn("teleporter", 12,21,1, "teleporter_5")
	:setTriggeredByParty(true)
	:setTriggeredByMonster(false)
	:setTriggeredByItem(false)
	:setTeleportTarget(14,21,1,3)
	:setInvisible(true)
	:setSilent(true)
	:setHideLight(true)
	:setScreenFlash(false)
spawn("sx_remove_wall", 6,19,3, "sx_remove_wall_78")
spawn("sx_outwall_pillarkiller", 6,19,3, "sx_outwall_pillarkiller_42")
spawn("sx_remove_wall", 6,21,3, "sx_remove_wall_80")
spawn("sx_remove_wall", 6,20,3, "sx_remove_wall_77")
spawn("sx_outwall_pillarkiller", 6,21,3, "sx_outwall_pillarkiller_43")
spawn("sx_remove_wall", 6,23,3, "sx_remove_wall_128")
spawn("sx_remove_wall", 6,22,3, "sx_remove_wall_79")
spawn("sx_outwall_pillarkiller", 6,23,3, "sx_outwall_pillarkiller_44")
spawn("sx_remove_wall", 11,13,3, "sx_remove_wall_73")
spawn("sx_remove_wall", 11,14,3, "sx_remove_wall_74")
spawn("sx_remove_wall", 11,12,3, "sx_remove_wall_75")
spawn("sx_remove_wall", 11,11,3, "sx_remove_wall_76")
spawn("sx_remove_wall", 11,11,0, "sx_remove_wall_81")
spawn("sx_remove_wall", 12,11,0, "sx_remove_wall_82")
spawn("sx_remove_wall", 13,11,0, "sx_remove_wall_95")
spawn("sx_remove_wall", 14,11,0, "sx_remove_wall_96")
spawn("sx_remove_wall", 15,11,0, "sx_remove_wall_97")
spawn("sx_remove_wall", 16,11,0, "sx_remove_wall_98")
spawn("sx_remove_wall", 18,11,0, "sx_remove_wall_99")
spawn("sx_remove_wall", 17,11,0, "sx_remove_wall_100")
spawn("sx_remove_wall", 19,11,0, "sx_remove_wall_101")
spawn("sx_remove_wall", 19,11,1, "sx_remove_wall_102")
spawn("sx_remove_wall", 19,12,1, "sx_remove_wall_103")
spawn("sx_remove_wall", 21,13,0, "sx_remove_wall_104")
spawn("sx_remove_wall", 20,13,0, "sx_remove_wall_105")
spawn("sx_remove_wall", 21,13,1, "sx_remove_wall_106")
spawn("sx_remove_wall", 21,14,1, "sx_remove_wall_107")
spawn("sx_remove_wall", 22,15,0, "sx_remove_wall_108")
spawn("sx_remove_wall", 22,15,1, "sx_remove_wall_109")
spawn("sx_remove_wall", 22,16,1, "sx_remove_wall_110")
spawn("sx_remove_wall", 22,17,1, "sx_remove_wall_111")
spawn("sx_remove_wall", 22,18,1, "sx_remove_wall_112")
spawn("sx_remove_wall", 22,19,1, "sx_remove_wall_113")
spawn("sx_remove_wall", 22,20,1, "sx_remove_wall_114")
spawn("sx_remove_wall", 22,20,2, "sx_remove_wall_115")
spawn("sx_remove_wall", 21,20,2, "sx_remove_wall_84")
spawn("sx_remove_wall", 19,21,1, "sx_remove_wall_85")
spawn("sx_remove_wall", 20,20,2, "sx_remove_wall_86")
spawn("sx_remove_wall", 19,21,2, "sx_remove_wall_87")
spawn("sx_remove_wall", 18,22,1, "sx_remove_wall_88")
spawn("sx_remove_wall", 18,23,1, "sx_remove_wall_89")
spawn("sx_remove_wall", 18,24,1, "sx_remove_wall_90")
spawn("sx_remove_wall", 18,25,1, "sx_remove_wall_91")
spawn("sx_remove_wall", 18,26,1, "sx_remove_wall_92")
spawn("sx_remove_wall", 18,27,1, "sx_remove_wall_93")
spawn("sx_remove_wall", 18,27,2, "sx_remove_wall_94")
spawn("sx_remove_wall", 17,27,2, "sx_remove_wall_116")
spawn("sx_remove_wall", 16,27,2, "sx_remove_wall_117")
spawn("sx_remove_wall", 15,27,2, "sx_remove_wall_119")
spawn("sx_remove_wall", 14,27,2, "sx_remove_wall_120")
spawn("sx_remove_wall", 14,27,3, "sx_remove_wall_121")
spawn("sx_remove_wall", 13,26,2, "sx_remove_wall_122")
spawn("sx_remove_wall", 12,26,2, "sx_remove_wall_123")
spawn("sx_remove_wall", 12,26,3, "sx_remove_wall_124")
spawn("sx_remove_wall", 11,25,2, "sx_remove_wall_125")
spawn("sx_remove_wall", 11,25,3, "sx_remove_wall_126")
spawn("sx_remove_ceiling", 11,17,3, "sx_remove_ceiling_104")
spawn("sx_remove_ceiling", 11,16,3, "sx_remove_ceiling_105")
spawn("sx_remove_wall", 7,23,2, "sx_remove_wall_127")
spawn("sx_outwall_pillarkiller", 7,23,2, "sx_outwall_pillarkiller_39")
spawn("sx_remove_wall", 6,23,2, "sx_remove_wall_129")
spawn("sx_remove_wall", 9,23,2, "sx_remove_wall_131")
spawn("sx_outwall_pillarkiller", 9,23,2, "sx_outwall_pillarkiller_40")
spawn("sx_remove_wall", 8,23,2, "sx_remove_wall_118")
spawn("sx_remove_wall", 10,23,2, "sx_remove_wall_132")
spawn("sx_outwall_pillarkiller", 10,23,2, "sx_outwall_pillarkiller_41")
spawn("sx_remove_ceiling", 10,21,3, "sx_remove_ceiling_108")
spawn("sx_remove_floor", 10,21,3, "sx_remove_floor_65")
spawn("sx_remove_ceiling", 10,22,3, "sx_remove_ceiling_74")
spawn("sx_remove_floor", 10,22,3, "sx_remove_floor_7")
spawn("sx_remove_ceiling", 10,20,3, "sx_remove_ceiling_106")
spawn("sx_remove_floor", 10,20,3, "sx_remove_floor_63")
spawn("sx_remove_ceiling", 9,21,3, "sx_remove_ceiling_113")
spawn("sx_remove_floor", 9,21,3, "sx_remove_floor_68")
spawn("sx_remove_ceiling", 9,22,3, "sx_remove_ceiling_107")
spawn("sx_remove_floor", 9,22,3, "sx_remove_floor_64")
spawn("sx_remove_ceiling", 9,20,3, "sx_remove_ceiling_110")
spawn("sx_remove_floor", 9,20,3, "sx_remove_floor_66")
spawn("sx_remove_ceiling", 8,21,3, "sx_remove_ceiling_121")
spawn("sx_remove_floor", 8,21,3, "sx_remove_floor_71")
spawn("sx_remove_ceiling", 8,22,3, "sx_remove_ceiling_111")
spawn("sx_remove_floor", 8,22,3, "sx_remove_floor_67")
spawn("sx_remove_ceiling", 8,20,3, "sx_remove_ceiling_119")
spawn("sx_remove_floor", 8,20,3, "sx_remove_floor_69")
spawn("sx_remove_ceiling", 7,21,3, "sx_remove_ceiling_124")
spawn("sx_remove_floor", 7,21,3, "sx_remove_floor_74")
spawn("sx_remove_ceiling", 7,22,3, "sx_remove_ceiling_120")
spawn("sx_remove_floor", 7,22,3, "sx_remove_floor_70")
spawn("sx_remove_ceiling", 7,20,3, "sx_remove_ceiling_122")
spawn("sx_remove_floor", 7,20,3, "sx_remove_floor_72")
spawn("sx_remove_ceiling", 11,19,3, "sx_remove_ceiling_129")
spawn("sx_remove_floor", 11,19,3, "sx_remove_floor_79")
spawn("sx_remove_ceiling", 10,19,3, "sx_remove_ceiling_123")
spawn("sx_remove_floor", 10,19,3, "sx_remove_floor_73")
spawn("sx_remove_ceiling", 9,19,3, "sx_remove_ceiling_125")
spawn("sx_remove_floor", 9,19,3, "sx_remove_floor_75")
spawn("sx_remove_ceiling", 8,19,3, "sx_remove_ceiling_126")
spawn("sx_remove_floor", 8,19,3, "sx_remove_floor_76")
spawn("sx_remove_ceiling", 7,19,3, "sx_remove_ceiling_127")
spawn("sx_remove_floor", 7,19,3, "sx_remove_floor_77")
spawn("sx_remove_wall", 6,18,3, "sx_remove_wall_70")
spawn("sx_remove_wall", 9,15,0, "sx_remove_wall_71")
spawn("sx_outwall_pillarkiller", 9,15,0, "sx_outwall_pillarkiller_38")
spawn("sx_remove_wall", 10,15,0, "sx_remove_wall_130")
spawn("sx_remove_wall", 8,18,0, "sx_remove_wall_134")
spawn("sx_outwall_pillarkiller", 8,18,0, "sx_outwall_pillarkiller_45")
spawn("sx_remove_wall", 9,17,3, "sx_remove_wall_69")
spawn("sx_remove_wall", 9,16,3, "sx_remove_wall_136")
spawn("sx_outwall_pillarkiller", 9,16,3, "sx_outwall_pillarkiller_46")
spawn("sx_remove_wall", 9,15,3, "sx_remove_wall_133")
spawn("sx_remove_wall", 6,18,0, "sx_remove_wall_138")
spawn("sx_outwall_pillarkiller", 6,18,0, "sx_outwall_pillarkiller_47")
spawn("sx_remove_wall", 7,18,0, "sx_remove_wall_135")
spawn("sx_remove_ceiling", 10,16,3, "sx_remove_ceiling_130")
spawn("sx_remove_ceiling", 9,16,3, "sx_remove_ceiling_131")
spawn("sx_remove_ceiling", 9,17,3, "sx_remove_ceiling_132")
spawn("sx_remove_ceiling", 10,17,3, "sx_remove_ceiling_133")
spawn("sx_remove_ceiling", 10,18,3, "sx_remove_ceiling_134")
spawn("sx_remove_ceiling", 9,18,3, "sx_remove_ceiling_135")
spawn("sx_remove_ceiling", 8,18,3, "sx_remove_ceiling_136")
spawn("sx_remove_ceiling", 7,18,3, "sx_remove_ceiling_137")
spawn("sx_remove_ceiling", 6,18,3, "sx_remove_ceiling_138")
spawn("sx_remove_ceiling", 6,19,3, "sx_remove_ceiling_139")
spawn("sx_remove_ceiling", 6,20,3, "sx_remove_ceiling_140")
spawn("sx_remove_ceiling", 6,21,3, "sx_remove_ceiling_141")
spawn("sx_remove_ceiling", 6,22,3, "sx_remove_ceiling_142")
spawn("sx_remove_ceiling", 6,23,3, "sx_remove_ceiling_143")
spawn("sx_remove_ceiling", 7,23,3, "sx_remove_ceiling_144")
spawn("sx_remove_ceiling", 8,23,3, "sx_remove_ceiling_145")
spawn("sx_remove_ceiling", 9,23,3, "sx_remove_ceiling_146")
spawn("sx_remove_ceiling", 10,15,3, "sx_remove_ceiling_147")
spawn("sx_remove_ceiling", 9,15,3, "sx_remove_ceiling_148")
spawn("sx_remove_ceiling", 11,15,3, "sx_remove_ceiling_149")
spawn("sx_remove_ceiling", 10,23,3, "sx_remove_ceiling_150")
spawn("sx_remove_floor", 10,18,3, "sx_remove_floor_62")
spawn("sx_remove_floor", 9,18,3, "sx_remove_floor_78")
spawn("sx_remove_floor", 9,17,3, "sx_remove_floor_80")
spawn("sx_remove_floor", 10,17,3, "sx_remove_floor_81")
spawn("sx_remove_floor", 10,16,3, "sx_remove_floor_82")
spawn("sx_remove_floor", 9,16,3, "sx_remove_floor_83")
spawn("sx_remove_floor", 9,15,3, "sx_remove_floor_84")
spawn("sx_remove_floor", 10,15,3, "sx_remove_floor_85")
spawn("castle_exterior_pillar_big", 16,19,2, "castle_exterior_pillar_big_67")
spawn("sx_remove_ceiling", 11,14,3, "sx_remove_ceiling_153")
spawn("sx_remove_ceiling", 11,13,3, "sx_remove_ceiling_154")
spawn("sx_remove_ceiling", 11,12,3, "sx_remove_ceiling_155")
spawn("sx_remove_ceiling", 11,11,3, "sx_remove_ceiling_156")
spawn("sx_remove_ceiling", 12,11,3, "sx_remove_ceiling_157")
spawn("sx_remove_ceiling", 13,11,3, "sx_remove_ceiling_158")
spawn("sx_remove_ceiling", 14,11,3, "sx_remove_ceiling_159")
spawn("sx_remove_ceiling", 15,11,3, "sx_remove_ceiling_160")
spawn("sx_remove_ceiling", 16,11,3, "sx_remove_ceiling_161")
spawn("sx_remove_ceiling", 17,11,3, "sx_remove_ceiling_162")
spawn("sx_remove_ceiling", 18,11,3, "sx_remove_ceiling_163")
spawn("sx_remove_ceiling", 19,11,3, "sx_remove_ceiling_164")
spawn("sx_remove_ceiling", 19,12,3, "sx_remove_ceiling_166")
spawn("sx_remove_ceiling", 19,13,3, "sx_remove_ceiling_167")
spawn("sx_remove_ceiling", 20,13,3, "sx_remove_ceiling_168")
spawn("sx_remove_ceiling", 21,13,3, "sx_remove_ceiling_169")
spawn("sx_remove_ceiling", 21,14,3, "sx_remove_ceiling_128")
spawn("sx_remove_ceiling", 21,15,0, "sx_remove_ceiling_170")
spawn("sx_remove_ceiling", 22,15,3, "sx_remove_ceiling_171")
spawn("sx_remove_ceiling", 22,16,2, "sx_remove_ceiling_172")
spawn("sx_remove_ceiling", 22,17,2, "sx_remove_ceiling_173")
spawn("sx_remove_ceiling", 22,18,3, "sx_remove_ceiling_174")
spawn("sx_remove_ceiling", 22,19,3, "sx_remove_ceiling_175")
spawn("sx_remove_ceiling", 22,20,0, "sx_remove_ceiling_176")
spawn("sx_remove_ceiling", 21,20,0, "sx_remove_ceiling_178")
spawn("sx_remove_ceiling", 20,20,1, "sx_remove_ceiling_179")
spawn("sx_remove_ceiling", 19,20,1, "sx_remove_ceiling_180")
spawn("sx_remove_ceiling", 19,21,1, "sx_remove_ceiling_181")
spawn("sx_remove_ceiling", 18,21,1, "sx_remove_ceiling_182")
spawn("sx_remove_ceiling", 18,22,2, "sx_remove_ceiling_183")
spawn("sx_remove_ceiling", 18,23,0, "sx_remove_ceiling_184")
spawn("sx_remove_ceiling", 18,24,0, "sx_remove_ceiling_185")
spawn("sx_remove_ceiling", 18,25,0, "sx_remove_ceiling_186")
spawn("sx_remove_ceiling", 18,26,0, "sx_remove_ceiling_187")
spawn("sx_remove_ceiling", 18,27,0, "sx_remove_ceiling_188")
spawn("sx_remove_ceiling", 17,27,2, "sx_remove_ceiling_189")
spawn("sx_remove_ceiling", 16,27,2, "sx_remove_ceiling_190")
spawn("sx_remove_ceiling", 15,27,1, "sx_remove_ceiling_191")
spawn("sx_remove_ceiling", 14,27,3, "sx_remove_ceiling_192")
spawn("sx_remove_ceiling", 14,26,3, "sx_remove_ceiling_193")
spawn("sx_remove_ceiling", 13,26,1, "sx_remove_ceiling_194")
spawn("sx_remove_ceiling", 12,26,3, "sx_remove_ceiling_195")
spawn("sx_remove_ceiling", 12,25,3, "sx_remove_ceiling_196")
spawn("sx_remove_ceiling", 11,25,0, "sx_remove_ceiling_197")
spawn("starting_location", 16,15,2, "starting_location_1")

--- level 4 ---

mapName("Castle Level 4")
setWallSet("castle_exterior")
playStream("assets/samples/music/dungeon_ambient.ogg")
mapDesc([[
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
##############....##############
#########..###....##############
#########..###....##############
#########..###....##############
#########......#################
#########..#####################
#######.....####################
#######........#################
#######........#################
#######.....####################
################################
################################
################################
################################
################################
################################
################################
################################
################################
]])
spawn("sx_simple_stairs_up", 12,20,1, "sx_simple_stairs_up_2")
spawn("sx_simple_stairs_up", 12,21,1, "sx_simple_stairs_up_3")
spawn("castle_exterior_pillar_big", 7,19,1, "castle_exterior_pillar_big_19")
spawn("castle_exterior_pillar_big", 7,23,1, "castle_exterior_pillar_big_27")
spawn("castle_exterior_pillar_big", 12,23,1, "castle_exterior_pillar_big_56")
spawn("castle_exterior_pillar_big", 12,19,3, "castle_exterior_pillar_big_66")
spawn("sx_remove_ceiling", 7,19,2, "sx_remove_ceiling_28")
spawn("sx_remove_ceiling", 7,20,2, "sx_remove_ceiling_64")
spawn("sx_remove_ceiling", 7,21,0, "sx_remove_ceiling_65")
spawn("sx_remove_ceiling", 7,22,0, "sx_remove_ceiling_66")
spawn("sx_remove_ceiling", 8,22,3, "sx_remove_ceiling_67")
spawn("sx_remove_ceiling", 9,22,3, "sx_remove_ceiling_69")
spawn("sx_remove_ceiling", 11,22,1, "sx_remove_ceiling_75")
spawn("sx_remove_ceiling", 10,22,2, "sx_remove_ceiling_76")
spawn("sx_remove_ceiling", 10,21,2, "sx_remove_ceiling_77")
spawn("sx_remove_ceiling", 11,21,3, "sx_remove_ceiling_78")
spawn("sx_remove_ceiling", 11,20,3, "sx_remove_ceiling_79")
spawn("sx_remove_ceiling", 11,19,2, "sx_remove_ceiling_80")
spawn("sx_remove_ceiling", 10,19,2, "sx_remove_ceiling_81")
spawn("sx_remove_ceiling", 10,20,2, "sx_remove_ceiling_82")
spawn("sx_remove_ceiling", 9,20,2, "sx_remove_ceiling_83")
spawn("sx_remove_ceiling", 9,21,2, "sx_remove_ceiling_84")
spawn("sx_remove_ceiling", 8,21,1, "sx_remove_ceiling_85")
spawn("sx_remove_ceiling", 8,20,0, "sx_remove_ceiling_86")
spawn("sx_remove_ceiling", 8,19,1, "sx_remove_ceiling_88")
spawn("sx_remove_ceiling", 9,19,2, "sx_remove_ceiling_89")
spawn("castle_exterior_wall", 12,21,2, "castle_exterior_wall_8")
spawn("castle_exterior_wall", 12,20,0, "castle_exterior_wall_9")
spawn("castle_exterior_wall", 13,20,0, "castle_exterior_wall_11")
spawn("castle_exterior_wall", 13,22,0, "castle_exterior_wall_12")
spawn("castle_exterior_pillar_big", 12,20,3, "castle_exterior_pillar_big_68")
spawn("castle_exterior_pillar_big", 12,22,3, "castle_exterior_pillar_big_69")
spawn("teleporter", 13,21,3, "teleporter_6")
	:setTriggeredByParty(true)
	:setTriggeredByMonster(false)
	:setTriggeredByItem(false)
	:setTeleportTarget(11,21,3,4)
	:setInvisible(true)
	:setSilent(true)
	:setHideLight(true)
	:setScreenFlash(false)
spawn("teleporter", 13,20,3, "teleporter_7")
	:setTriggeredByParty(true)
	:setTriggeredByMonster(false)
	:setTriggeredByItem(false)
	:setTeleportTarget(11,20,3,4)
	:setInvisible(true)
	:setSilent(true)
	:setHideLight(true)
	:setScreenFlash(false)
spawn("sx_remove_ceiling", 9,18,2, "sx_remove_ceiling_93")
spawn("sx_remove_ceiling", 10,18,2, "sx_remove_ceiling_95")
spawn("sx_remove_ceiling", 10,17,2, "sx_remove_ceiling_96")
spawn("sx_remove_ceiling", 9,17,2, "sx_remove_ceiling_97")
spawn("sx_remove_ceiling", 9,16,2, "sx_remove_ceiling_98")
spawn("sx_remove_ceiling", 10,16,2, "sx_remove_ceiling_99")
spawn("sx_remove_ceiling", 10,15,2, "sx_remove_ceiling_100")
spawn("sx_remove_ceiling", 10,14,2, "sx_remove_ceiling_101")
spawn("sx_remove_ceiling", 9,14,2, "sx_remove_ceiling_102")
spawn("sx_remove_ceiling", 9,15,2, "sx_remove_ceiling_103")
spawn("sx_ceiling_lamp_outside", 13,21,3, "sx_ceiling_lamp_outside_7")
spawn("sx_ceiling_lamp_outside", 9,16,0, "sx_ceiling_lamp_outside_8")
spawn("sx_remove_ceiling", 13,20,2, "sx_remove_ceiling_151")
spawn("sx_remove_ceiling", 13,21,2, "sx_remove_ceiling_152")
spawn("torch_holder", 14,15,3, "torch_holder_3")
	:addTorch()
