-- This file has been generated by Dungeon Editor 1.3.6

--- level 1 ---

mapName("Unnamed")
setWallSet("castle_exterior")
playStream("assets/samples/music/dungeon_ambient.ogg")
mapDesc([[
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
#############.....##############
#############.....##############
#############.....##############
#############.....##############
#############.....##.###########
###############.#....###########
###############..###############
###############..###############
###############..###############
##############...###############
#############....###############
##############...###############
################################
################################
################################
################################
################################
################################
################################
]])
spawn("sx_remove_ceiling", 13,14,1, "sx_remove_ceiling_2")
spawn("sx_remove_ceiling", 14,14,1, "sx_remove_ceiling_3")
spawn("sx_remove_ceiling", 14,13,2, "sx_remove_ceiling_4")
spawn("sx_remove_ceiling", 15,13,0, "sx_remove_ceiling_5")
spawn("sx_remove_ceiling", 15,14,0, "sx_remove_ceiling_6")
spawn("sx_remove_ceiling", 15,15,0, "sx_remove_ceiling_7")
spawn("sx_remove_ceiling", 14,15,1, "sx_remove_ceiling_8")
spawn("sx_remove_ceiling", 13,15,1, "sx_remove_ceiling_9")
spawn("sx_remove_ceiling", 13,16,1, "sx_remove_ceiling_10")
spawn("sx_remove_ceiling", 13,17,1, "sx_remove_ceiling_11")
spawn("sx_remove_ceiling", 14,16,0, "sx_remove_ceiling_12")
spawn("sx_remove_ceiling", 13,13,3, "sx_remove_ceiling_1")
spawn("torch_holder", 14,13,0, "torch_holder_1")
	:addTorch()
spawn("torch_holder", 17,16,1, "torch_holder_2")
	:addTorch()
spawn("sx_ceiling_lamp_outside", 15,15,0, "sx_ceiling_lamp_outside_4")
spawn("castle_exterior_pillar_big", 15,13,2, "castle_exterior_pillar_big_1")
spawn("starting_location", 14,15,0, "starting_location")
spawn("castle_exterior_pillar_big", 13,13,2, "castle_exterior_pillar_big_3")
spawn("castle_exterior_pillar_big", 13,15,2, "castle_exterior_pillar_big_4")
spawn("castle_exterior_pillar_big", 13,18,2, "castle_exterior_pillar_big_5")
spawn("sx_remove_ceiling", 14,17,0, "sx_remove_ceiling_43")
spawn("sx_remove_ceiling", 15,17,0, "sx_remove_ceiling_44")
spawn("sx_remove_ceiling", 15,16,0, "sx_remove_ceiling_45")
spawn("sx_remove_ceiling", 16,14,0, "sx_remove_ceiling_14")
spawn("sx_remove_ceiling", 16,13,0, "sx_remove_ceiling_42")
spawn("sx_remove_ceiling", 17,13,0, "sx_remove_ceiling_46")
spawn("sx_remove_ceiling", 17,14,0, "sx_remove_ceiling_47")
spawn("sx_remove_ceiling", 16,15,0, "sx_remove_ceiling_49")
spawn("sx_remove_ceiling", 17,15,0, "sx_remove_ceiling_13")
spawn("sx_remove_ceiling", 16,16,0, "sx_remove_ceiling_51")
spawn("sx_remove_ceiling", 17,16,0, "sx_remove_ceiling_48")
spawn("sx_remove_ceiling", 16,17,0, "sx_remove_ceiling_53")
spawn("sx_remove_ceiling", 17,17,0, "sx_remove_ceiling_50")
spawn("temple_door_portcullis", 15,18,0, "temple_door_portcullis_1")
spawn("sx_remove_ceiling", 17,18,0, "sx_remove_ceiling_54")
spawn("sx_remove_ceiling", 15,18,0, "sx_remove_ceiling_55")
spawn("sx_remove_ceiling", 15,19,0, "sx_remove_ceiling_56")
spawn("castle_exterior_pillar_big", 15,18,2, "castle_exterior_pillar_big_6")
spawn("castle_exterior_pillar_big", 16,18,2, "castle_exterior_pillar_big_7")
spawn("castle_exterior_pillar_big", 17,18,2, "castle_exterior_pillar_big_8")
spawn("castle_exterior_pillar_big", 18,18,2, "castle_exterior_pillar_big_9")
spawn("castle_exterior_pillar_big", 18,13,2, "castle_exterior_pillar_big_10")
spawn("skeleton_warrior", 16,17,0, "skeleton_warrior_1")
spawn("blocker", 16,16,3, "blocker_1")
spawn("blocker", 17,17,2, "blocker_2")
spawn("blocker", 14,16,2, "blocker_3")
spawn("blocker", 15,17,2, "blocker_4")
spawn("blocker", 13,17,2, "blocker_6")
spawn("skeleton_warrior", 14,17,0, "skeleton_warrior_3")
spawn("castle_exterior_wall_level2", 19,13,2, "castle_exterior_wall_level2_1")
spawn("castle_exterior_wall_level2", 18,15,1, "castle_exterior_wall_level2_3")
spawn("castle_exterior_wall_level2", 18,14,1, "castle_exterior_wall_level2_4")
spawn("castle_exterior_pillar_big_level2", 19,14,0, "castle_exterior_pillar_big_level2_1")
spawn("castle_exterior_pillar_big_level2", 19,16,0, "castle_exterior_pillar_big_level2_3")
spawn("castle_exterior_wall_level2", 19,15,2, "castle_exterior_wall_level2_5")
spawn("castle_exterior_wall_level2", 17,18,2, "castle_exterior_wall_level2_9")
spawn("castle_exterior_wall_level2", 16,20,1, "castle_exterior_wall_level2_2")
spawn("castle_exterior_wall_level2", 16,19,1, "castle_exterior_wall_level2_6")
spawn("castle_exterior_pillar_big_level2", 17,19,1, "castle_exterior_pillar_big_level2_5")
spawn("castle_exterior_pillar_big_level2", 17,21,0, "castle_exterior_pillar_big_level2_2")
spawn("castle_exterior_wall_level2", 17,20,2, "castle_exterior_wall_level2_7")
spawn("castle_exterior_wall_level2", 18,18,2, "castle_exterior_wall_level2_10")
spawn("castle_exterior_pillar_big_level2", 19,19,0, "castle_exterior_pillar_big_level2_6")
spawn("sx_remove_ceiling", 16,19,0, "sx_remove_ceiling_16")
spawn("sx_remove_ceiling", 15,20,0, "sx_remove_ceiling_17")
spawn("sx_remove_ceiling", 16,20,0, "sx_remove_ceiling_18")
spawn("sx_remove_ceiling", 16,21,0, "sx_remove_ceiling_19")
spawn("sx_remove_ceiling", 15,21,0, "sx_remove_ceiling_20")
spawn("sx_remove_ceiling", 15,22,0, "sx_remove_ceiling_21")
spawn("sx_remove_ceiling", 16,22,0, "sx_remove_ceiling_22")
spawn("sx_remove_ceiling", 14,22,0, "sx_remove_ceiling_23")
spawn("sx_remove_ceiling", 18,18,0, "sx_remove_ceiling_52")
spawn("sx_remove_ceiling", 19,18,0, "sx_remove_ceiling_57")
spawn("sx_remove_ceiling", 20,18,0, "sx_remove_ceiling_58")
spawn("sx_remove_ceiling", 20,17,0, "sx_remove_ceiling_59")
spawn("castle_exterior_pillar_big", 17,19,2, "castle_exterior_pillar_big_11")
spawn("castle_exterior_wall_windows_level2", 18,15,1, "castle_exterior_wall_windows_level2_1")
spawn("castle_exterior_pillar_small_level2", 19,15,3, "castle_exterior_pillar_small_level2_1")
spawn("castle_exterior_wall_windows_level2", 17,18,2, "castle_exterior_wall_windows_level2_3")
spawn("castle_exterior_pillar_small_level2", 18,19,3, "castle_exterior_pillar_small_level2_3")
spawn("castle_exterior_pillar_small_level2", 17,20,3, "castle_exterior_pillar_small_level2_4")
spawn("sx_ceiling_lamp_outside", 18,18,0, "sx_ceiling_lamp_outside_2")
spawn("castle_exterior_wall_level3", 18,18,2, "castle_exterior_wall_level3_1")
spawn("castle_exterior_wall_level3", 17,19,1, "castle_exterior_wall_level3_3")
spawn("castle_exterior_wall_level3", 18,19,1, "castle_exterior_wall_level3_4")
spawn("castle_exterior_wall_windows_level3", 18,18,2, "castle_exterior_wall_windows_level3_1")
spawn("castle_exterior_pillar_big_level3", 18,19,1, "castle_exterior_pillar_big_level3_1")
spawn("castle_exterior_pillar_big_level3", 19,19,1, "castle_exterior_pillar_big_level3_3")
spawn("castle_exterior_pillar_big_level3", 18,20,1, "castle_exterior_pillar_big_level3_4")
spawn("castle_exterior_wall_windows_level3", 17,19,1, "castle_exterior_wall_windows_level3_3")
spawn("castle_exterior_pillar_big", 20,18,2, "castle_exterior_pillar_big_12")
spawn("castle_exterior_pillar_big", 21,19,2, "castle_exterior_pillar_big_13")
spawn("castle_exterior_pillar_big", 21,17,2, "castle_exterior_pillar_big_14")
spawn("castle_exterior_pillar_big", 20,17,2, "castle_exterior_pillar_big_15")
spawn("castle_exterior_wall_level2", 19,19,3, "castle_exterior_wall_level2_11")
spawn("castle_exterior_wall_level2", 19,20,3, "castle_exterior_wall_level2_12")
spawn("castle_exterior_wall_level2", 18,20,2, "castle_exterior_wall_level2_13")
spawn("castle_exterior_pillar_big_level2", 19,21,0, "castle_exterior_pillar_big_level2_7")
spawn("castle_exterior_pillar_big_level2", 20,16,0, "castle_exterior_pillar_big_level2_8")
