-- This file was generated by Centauri Soldier

-- TODO: place your custom NPC definitions here

defineObject{
	name = "npc_boatman",
	class = "Monster",
	model = "assets/models/monsters/goromorg.fbx",
	meshName = "goromorg_mesh",
	animations = {
		idle = "assets/animations/monsters/goromorg/goromorg_idle.fbx",
		moveForward = "assets/animations/monsters/goromorg/goromorg_walk.fbx",
		strafeLeft = "assets/animations/monsters/goromorg/goromorg_strafe_left.fbx",
		strafeRight = "assets/animations/monsters/goromorg/goromorg_strafe_right.fbx",
		turnLeft = "assets/animations/monsters/goromorg/goromorg_turn_left.fbx",
		turnRight = "assets/animations/monsters/goromorg/goromorg_turn_right.fbx",
		attack = "assets/animations/monsters/goromorg/goromorg_idle.fbx",--"assets/animations/monsters/goromorg/goromorg_attack.fbx",
		getHitFrontLeft = "assets/animations/monsters/goromorg/goromorg_get_hit_front_left.fbx",
		getHitFrontRight = "assets/animations/monsters/goromorg/goromorg_get_hit_front_right.fbx",
		getHitBack = "assets/animations/monsters/goromorg/goromorg_get_hit_back.fbx",
		getHitLeft = "assets/animations/monsters/goromorg/goromorg_get_hit_left.fbx",
		getHitRight = "assets/animations/monsters/goromorg/goromorg_get_hit_right.fbx",
		fall = "assets/animations/monsters/goromorg/goromorg_get_hit.fbx",
	},
	--attackAnimSpeed = 1.7,
	--moveAnimSpeed = 1.2,
	--turnAnimSpeed = 1.3,		
	moveSound = "goromorg_walk",
	footstepSound = "goromorg_footstep",
	attackSound = "empty",
	hitSound = "empty",
	dieSound = "empty",
	hitEffect = "empty",
	capsuleHeight = 0.8,
	capsuleRadius = 0.25,
	collisionRadius = 0.8,
	health = 25000,
	sight = 0,
	seeInvisible = false,
	allAroundSight = false,
	attackPower = 0,
	evasion = 25000,
	protection = 25000,
	rangedAttack = {},
	coolDown = {21600,21601},
	movementCoolDown = 7,
	exp = 0,	
	particleSystem = "goromorg_lantern",
	particleSystemNode = "light1",
	lightName = "light1",
	lightColor = vec(0.2, 1.0, 2.5),
	lightBrightness = 5,
	lightRange = 4.5,
	healthIncrement = 50,
	brain = "Melee",
	onRangedAttack = function()
	return false
	end,
	onDamage = function()
	return false
	end,
	onDealDamage = function()
	return false
	end,	
	onProjectileHit = function()
	return false
	end,
	onDie = function()
	return false
	end,
	onMove = function(hEntity, nDirection)
	return NPC.AllowMovement(hEntity, nDirection)
	end,
	onTurn = function(hEntity, nDirection)
	return NPC.AllowMovement(hEntity, nDirection)
	end,
}