-- This file was generated by Centauri Soldier

-- TODO: place your custom Party definitions and hooks here

cloneObject{
	name = "party",
	baseObject = "party",
	onAttack = function(nChampionID, hWeapon)	
	local nXAdjust = 0;
	local nYAdjust = 0;
	local hParty = findEntity("party");
	local tNPCObjects = {"npc_boatman"};
		
		--get the tile in front of the party
		if hParty.facing == 0 then
		nYAdjust = -1;
		
		elseif hParty.facing == 1 then
		nXAdjust = 1;
		
		elseif hParty.facing == 2 then
		nYAdjust = 1;
		
		elseif hParty.facing == 3 then
		nXAdjust = -1;
		
		end
		
		--check for NPCs in front of the party
		for hEntity in entitiesAt(hParty.level, hParty.x + nXAdjust, hParty.y + nYAdjust) do
			
			for nObjectID, sObject in pairs(tNPCObjects) do
				
				--if found, request a dialog
				if hEntity.name == sObject then				
				NPC.RequestDialog(hEntity.id);	
				return false
				end
				
			end
			
		end
		
	return true
	end,
	onDrawGui = function(hGUI)
	GUI.OnDraw(hGUI)
	end,
	onDrawInventory = function(hGUI)
	GUI.OnDrawInventory(hGUI)
	end,
	onDrawStats = function(hGUI)
	GUI.OnDrawStats(hGUI)
	end,	
	onDrawSkills = function(hGUI)
	GUI.OnDrawSkills(hGUI)
	end,
}