-- This file has been generated by Dungeon Editor 1.3.6

-- import standard assets
import "assets/scripts/standard_assets.lua"

-- import custom assets
import "mod_assets/scripts/items.lua"
import "mod_assets/scripts/monsters.lua"
import "mod_assets/scripts/objects.lua"
import "mod_assets/scripts/wall_sets.lua"
import "mod_assets/scripts/recipes.lua"
import "mod_assets/scripts/spells.lua"
import "mod_assets/scripts/materials.lua"
import "mod_assets/scripts/sounds.lua"

cloneObject{
	name = "party",
	baseObject = "party",
	
	onMove = function()		
		return DIALOG.isMovingAllowed()
	end,
	
	onDrawGui = function(ctx)
		DIALOG.OnDraw(ctx)
		WINDOW.OnDraw(ctx)
		WINDOW2.OnDraw(ctx)
		CHARSHEET.OnDraw(ctx)
		TRAVEL.OnDraw(ctx)
	end,
	
	onDrawInventory = function(ctx)
		CHARSHEET.OnDrawTab(ctx, 1)
		return false
	end,

	onDrawStats = function(ctx)
		CHARSHEET.OnDrawTab(ctx, 2)
		return false
	end,
	
	onDrawSkills = function(ctx)
		CHARSHEET.OnDrawTab(ctx, 3)
		return false
	end,
}
