-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom material definitions here



defineMaterial{
	name = "airshiprope",

	diffuseMap = "mod_assets/textures/wiosla1.tga",
	
		doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "airshiprope2",

	diffuseMap = "mod_assets/textures/wiosla2.tga",
	
		doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}



defineMaterial{
	name = "airshipdeck",

	diffuseMap = "mod_assets/textures/domek1.tga",
	
		doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "airshipdeck2",

	diffuseMap = "mod_assets/textures/domek2.tga",
	
		doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "airshipdeck3",

	diffuseMap = "mod_assets/textures/domek3.tga",
	
		doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}



defineMaterial{
	name = "airship4",

	diffuseMap = "mod_assets/textures/kadlub2.tga",
	
		doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}


defineMaterial{
	name = "airship3",

	diffuseMap = "mod_assets/textures/kadlub1.tga",
	
		doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}


defineMaterial{
	name = "airship2",

	diffuseMap = "mod_assets/textures/drewno2b.tga",
		doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}


defineMaterial{
	name = "airship1",

	diffuseMap = "mod_assets/textures/dach.tga",
		doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}



defineMaterial{
	name = "fountain",

	diffuseMap = "mod_assets/textures/fountainD.tga",
	normalMap = "mod_assets/textures/fountainN.tga",
	specularMap = "mod_assets/textures/fountainS.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}


defineMaterial{
	name = "bad_dog",

	diffuseMap = "mod_assets/textures/baddog_normals.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}



defineMaterial{
	name = "barb_f_body",

	diffuseMap = "mod_assets/textures/barb.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "poster_bed",

	diffuseMap = "mod_assets/textures/poster_bed_d.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}
defineMaterial{
	name = "diz1",

	diffuseMap = "mod_assets/textures/diz1.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}
defineMaterial{
	name = "cook_clothes",

	diffuseMap = "mod_assets/textures/cook_clothes_D.tga",
	normalMap = "mod_assets/textures/additional_cloth_normal.tga",
		

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "cook_eye",

	diffuseMap = "mod_assets/textures/cook_eye_D.tga",
	specularMap = "mod_assets/textures/cook_eye_S.tga",
		

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "cook_hand",

	diffuseMap = "mod_assets/textures/cook_hand_D.tga",
		

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "cook_head",

	diffuseMap = "mod_assets/textures/cook_head_D.tga",
	normalMap = "mod_assets/textures/cook_head_N.tga",
normalMap = "mod_assets/textures/additional_head_normal.tga",
		

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "wolf",

	diffuseMap = "mod_assets/textures/wolf.tga",
	
	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}


--Samurai
defineMaterial{
	name = "samurai",
	diffuseMap = "mod_assets/textures/td.tga",
	
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = -2.2,
	depthBias = 0,
}



--WIZ
defineMaterial{
	name = "wiz1",
	diffuseMap = "mod_assets/textures/wiz1dds.tga",
	
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = -2.2,
	depthBias = 0,
}
defineMaterial{
	name = "wiz2",
	diffuseMap = "mod_assets/textures/wiz2dds.tga",
	
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = -2.2,
	depthBias = 0,
}




--Cathedral
defineMaterial{
	name = "primal",
	diffuseMap = "mod_assets/textures/PrimalBeast_Dif.tga",
	
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = -2.2,
	depthBias = 0,
}



--Cathedral
defineMaterial{
	name = "cathedral",
	diffuseMap = "mod_assets/textures/Sanctuary_Diffuse.tga",
	
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 2,
	depthBias = 0,
}


--House
defineMaterial{
	name = "house_doorwindow",
	diffuseMap = "mod_assets/textures/doorwindow_set.tga",
	normalMap = "mod_assets/textures/doorwindow_set_N.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 2,
	depthBias = 0,
}

defineMaterial{
	name = "house_door",
	diffuseMap = "mod_assets/textures/house_door_001.tga",
	normalMap = "mod_assets/textures/house_door_001_n.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 2,
	depthBias = 0,
}
defineMaterial{
	name = "house_roof",
	diffuseMap = "mod_assets/textures/roof_01.tga",
	normalMap = "mod_assets/textures/roof_01_N.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 2,
	depthBias = 0,
}
defineMaterial{
	name = "house_wood",
	diffuseMap = "mod_assets/textures/wood_planks_01.tga",
	normalMap = "mod_assets/textures/wood_planks_01_N.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 2,
	depthBias = 0,
}

defineMaterial{
	name = "house_stone",
	diffuseMap = "mod_assets/textures/stone_005_c.tga",
	normalMap = "mod_assets/textures/stone_005_n.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 2,
	depthBias = 0,
}
defineMaterial{
	name = "house_dirt",
	diffuseMap = "mod_assets/textures/con_dirt_01.tga",
	normalMap = "mod_assets/textures/con_dirt_01_n.tga",
	specularMap = "mod_assets/textures/con_dirt_01_s.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 2,
	depthBias = 0,
}



--Horse
defineMaterial{
	name = "horse",
	diffuseMap = "mod_assets/textures/horse_d.tga",
	normalMap = "mod_assets/textures/horse_n.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 2,
	depthBias = 0,
}

defineMaterial{
	name = "horsemane",
	diffuseMap = "mod_assets/textures/horsemane_d.tga",
	normalMap = "mod_assets/textures/horsemane_n.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 2,
	depthBias = 0,
}

defineMaterial{
	name = "horsehmm",
	diffuseMap = "mod_assets/textures/horsehmm.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 2,
	depthBias = 0,
}










--EMPTY
defineMaterial{
	name = "small_empty",
	diffuseMap = "mod_assets/textures/small_empty.tga",
	specularMap = "mod_assets/textures/small_empty.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}



--Cozy Dungeon
defineMaterial{
	name = "WizBooks",
	diffuseMap = "mod_assets/textures/WizBooks_dif.tga",
	specularMap = "mod_assets/textures/WizBooks_spec.tga",
	normalMap = "mod_assets/textures/WizBooks_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}

defineMaterial{
	name = "WizWood",
	diffuseMap = "mod_assets/textures/WizWood_dif.tga",
	specularMap = "mod_assets/textures/WizWood_spec.tga",
	normalMap = "mod_assets/textures/WizWood_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}

defineMaterial{
	name = "WizCushion",
	diffuseMap = "mod_assets/textures/WizCushion_dif.tga",
	specularMap = "mod_assets/textures/WizCushion_spec.tga",
	normalMap = "mod_assets/textures/WizCushion_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}

defineMaterial{
	name = "WizDishes",
	diffuseMap = "mod_assets/textures/WizDishes_dif.tga",
	specularMap = "mod_assets/textures/WizDishes_spec.tga",
	normalMap = "mod_assets/textures/WizDishes_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}



-- GOBELINS


defineMaterial{

	name = "gobelin_green",

	diffuseMap = "mod_assets/lol_gobelins/textures/env/gobelin_green_dif.tga",
	specularMap = "assets/textures/env/dungeon_gobelin_spec.tga",

	normalMap = "assets/textures/env/dungeon_gobelin_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}



defineMaterial{

	name = "gobelin_green_torn",
	diffuseMap = "mod_assets/lol_gobelins/textures/env/gobelin_green_torn_dif.tga",

	specularMap = "assets/textures/env/dungeon_gobelin_torn_spec.tga",

	normalMap = "assets/textures/env/dungeon_gobelin_torn_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 20,

	depthBias = 0,

}



defineMaterial{

	name = "gobelin_crimson",

	diffuseMap = "mod_assets/lol_gobelins/textures/env/gobelin_crimson_dif.tga",
	specularMap = "assets/textures/env/dungeon_gobelin_spec.tga",

	normalMap = "assets/textures/env/dungeon_gobelin_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}



defineMaterial{

	name = "gobelin_crimson_torn",
	diffuseMap = "mod_assets/lol_gobelins/textures/env/gobelin_crimson_torn_dif.tga",

	specularMap = "assets/textures/env/dungeon_gobelin_torn_spec.tga",

	normalMap = "assets/textures/env/dungeon_gobelin_torn_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 20,

	depthBias = 0,

}



defineMaterial{

	name = "gobelin_blue",

	diffuseMap = "mod_assets/lol_gobelins/textures/env/gobelin_blue_dif.tga",
	specularMap = "assets/textures/env/dungeon_gobelin_spec.tga",

	normalMap = "assets/textures/env/dungeon_gobelin_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}



defineMaterial{

	name = "gobelin_blue_torn",
	diffuseMap = "mod_assets/lol_gobelins/textures/env/gobelin_blue_torn_dif.tga",

	specularMap = "assets/textures/env/dungeon_gobelin_torn_spec.tga",

	normalMap = "assets/textures/env/dungeon_gobelin_torn_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 20,

	depthBias = 0,

}


defineMaterial{

	name = "gobelin_unicorns",

	diffuseMap = "mod_assets/lol_gobelins/textures/env/gobelin_unicorns_dif.tga",
	specularMap = "assets/textures/env/dungeon_gobelin_spec.tga",

	normalMap = "assets/textures/env/dungeon_gobelin_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = true,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}



defineMaterial{

	name = "gobelin_unicorns_torn",
	diffuseMap = "mod_assets/lol_gobelins/textures/env/gobelin_unicorns_torn_dif.tga",

	specularMap = "assets/textures/env/dungeon_gobelin_torn_spec.tga",

	normalMap = "assets/textures/env/dungeon_gobelin_torn_normal.tga",

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = 20,

	depthBias = 0,

}

