-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom monster definitions here

defineObject{
	name = "npc_herder",
	class = "Monster",
	model = "assets/models/monsters/herder_big_top.fbx",
	meshName = "herder_big_top_mesh",
	animations = {
		idle = "assets/animations/monsters/herder/herder_big_top_idle.fbx",
		moveForward = "assets/animations/monsters/herder/herder_big_top_walk.fbx",
		turnLeft = "assets/animations/monsters/herder/herder_big_top_turn_left.fbx",
		turnRight = "assets/animations/monsters/herder/herder_big_top_turn_right.fbx",
		attack = "assets/animations/monsters/herder/herder_big_top_attack.fbx",
		getHitFrontLeft = "assets/animations/monsters/herder/herder_big_top_get_hit_front_left.fbx",
		getHitFrontRight = "assets/animations/monsters/herder/herder_big_top_get_hit_front_right.fbx",
		getHitBack = "assets/animations/monsters/herder/herder_big_top_get_hit_back.fbx",
		getHitLeft = "assets/animations/monsters/herder/herder_big_top_get_hit_left.fbx",
		getHitRight = "assets/animations/monsters/herder/herder_big_top_get_hit_right.fbx",
		fall = "assets/animations/monsters/herder/herder_big_top_get_hit_front_left.fbx",
	},
	moveSound = "herder_walk",
	footstepSound = "herder_footstep",
	attackSound = "herder_big_attack",
	hitSound = "herder_hit",
	dieSound = "herder_big_die",
	hitEffect = "hit_goo",
	capsuleHeight = 0.2,
	capsuleRadius = 0.7,
	health = 1300,
	sight = 0,
	allAroundSight = true,
	attackPower = 0,
	movementCoolDown = .5,
	coolDown = { 2, 3 },
	evasion = 25,
	immunities = { "poison" },
	noRecoilInterval = { 0.1, 0.5 },
	exp = 395,
	lootDrop = { 50, "herder_cap", 20, "herder_cap" },
	healthIncrement = 30,
	attackPowerIncrement = 4,
	brain = "HerderBig",
}



defineObject{
	name = "npc_ogre",
	class = "Monster",
	model = "mod_assets/models/ogre_hammerless.fbx",
	meshName = "tunnel_ogre_mesh",
onAttack = function(monster,attack)
return false
end,


	animations = {
		idle = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_idle.fbx",
		moveForward = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_walk.fbx",
		turnLeft = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_turn_left.fbx",
		turnRight = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_turn_right.fbx",
		attack = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_attack.fbx",
		attack2 = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_attack_stab.fbx",
		attack3 = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_attack_two_handed.fbx",
		attack4 = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_attack_leap.fbx",
		turnAttackLeft =  "assets/animations/monsters/tunnel_ogre/tunnel_ogre_attack_left.fbx",
		turnAttackRight =  "assets/animations/monsters/tunnel_ogre/tunnel_ogre_attack_right.fbx",
		getHitFrontLeft = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_get_hit_front_left_02.fbx",
		getHitFrontRight = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_get_hit_front_right_02.fbx",
		getHitBack = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_get_hit_back_02.fbx",
		getHitLeft = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_get_hit_left_02.fbx",
		getHitRight = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_get_hit_right_02.fbx",
		fall = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_get_hit_back_02.fbx",
		rushBegin = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_rush_begin.fbx",
		rushContinue1 = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_rush_continue_right_step.fbx",
		rushContinue2 = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_rush_continue_left_step.fbx",
		rushHit1 = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_rush_hit_right_step.fbx",
		rushHit2 = "assets/animations/monsters/tunnel_ogre/tunnel_ogre_rush_hit_left_step.fbx",
	},
	moveSound = "party_move_burdened",
	footstepSound = "party_move",
	attackSound = "ogre_attack",
	hitSound = "ogre_hit",
	impactSound = "ogre_impact",
	dieSound = "ogre_die",
	rushBeginSound = "ogre_rush_begin",
	--soundClipDistance = 8,
	hitEffect = "hit_blood",
	capsuleHeight = 0.6,
	capsuleRadius = 0.6,
	health = 5700,
	sight = 0,
	attackPower = 5,
	accuracy = -30,
	protection = 100,
	evasion = 10,
	coolDown = { 2, 3 },
	movementCoolDown = .3,
	noRecoilInterval = { 0.1, 1.0 }, -- interval must end at 1, otherwise turn attack can be interrupted (looks ugly)
	exp = 750,
	lootDrop = { 100, "ogre_hammer" },	
	healthIncrement = 50,
	attackPowerIncrement = 10,
	protectionIncrement = 1,
	brain = "Ogre",
	onDealDamage = function(self, champion, damage)
		party:shakeCamera(0.5, 0.3)
		party:playScreenEffect("damage_screen")
	end
}

defineObject{
	name = "npc_warden",
	class = "Monster",
	model = "mod_assets/models/guardian_flailess.fbx",
	meshName = "guardian_mesh",
onAttack = function(monster,attack)
return false
end,


	animations = {
		idle = "assets/animations/monsters/guardian/guardian_idle.fbx",
		moveForward = "assets/animations/monsters/guardian/guardian_walk.fbx",
		turnLeft = "assets/animations/monsters/guardian/guardian_turn_left.fbx",
		turnRight = "assets/animations/monsters/guardian/guardian_turn_right.fbx",
		attack = "assets/animations/monsters/guardian/guardian_attack.fbx",
		attack2 = "assets/animations/monsters/guardian/guardian_attack_swing.fbx",
		turnAttackLeft =  "assets/animations/monsters/guardian/guardian_attack_swing_left.fbx",
		turnAttackRight =  "assets/animations/monsters/guardian/guardian_attack_swing_right.fbx",
		getHitFrontLeft = "assets/animations/monsters/guardian/guardian_get_hit_front_left.fbx",
		getHitFrontRight = "assets/animations/monsters/guardian/guardian_get_hit_front_right.fbx",
		getHitBack = "assets/animations/monsters/guardian/guardian_get_hit_back.fbx",
		getHitLeft = "assets/animations/monsters/guardian/guardian_get_hit_left.fbx",
		getHitRight = "assets/animations/monsters/guardian/guardian_get_hit_right.fbx",
		fall = "assets/animations/monsters/guardian/guardian_get_hit_front_left.fbx",
		rushBegin = "assets/animations/monsters/guardian/guardian_rush_begin.fbx",
		rushContinue1 = "assets/animations/monsters/guardian/guardian_rush_continue_right_step.fbx",
		rushContinue2 = "assets/animations/monsters/guardian/guardian_rush_continue_left_step.fbx",
		rushHit1 = "assets/animations/monsters/guardian/guardian_rush_hit_right_step.fbx",
		rushHit2 = "assets/animations/monsters/guardian/guardian_rush_hit_left_step.fbx",
	},
	turnAnimSpeed = 1.1,
	attackAnimSpeed = 1.2,
	moveSound = "party_move_burdened",
	footstepSound = "party_move",
	attackSound = "warden_attack",
	impactSound = "warden_impact",
	hitSound = "warden_hit",
	dieSound = "warden_die",
	rushBeginSound = "warden_rush_begin",
	rushHitSound = "warden_rush_hit",
	--soundClipDistance = 8,
	hitEffect = "hit_dust",
	capsuleHeight = 0.6,
	capsuleRadius = 0.6,
	health = 12000,
	immunities = { "poison", "assassination" },
	sight = 0,
	seeInvisible = true,
	allAroundSight = true,
	attackPower = 20,
	accuracy = 10,
	coolDown = { 2, 4 },
	protection = 80,
	evasion = 10,
	movementCoolDown = .3,
	noRecoilInterval = { 0.1, 1 }, -- interval must end at 1, otherwise turn attack can be interrupted (looks ugly)
	exp = 750,
	healthIncrement = 100,
	attackPowerIncrement = 10,
	brain = "Warden",
	onDealDamage = function(self, champion, damage)
		party:shakeCamera(0.5, 0.3)
		party:playScreenEffect("damage_screen")
	end
}
