-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom dungeon object definitions here

-- This file has been generated by Dungeon Editor 1.3.1

defineObject{
	name = "town_ceiling_lamp",
	class = "LightSource",
	lightPosition = vec(0, 9, 0),
	lightRange = 30,
	lightColor = vec(1.0, 0.5, .2),
	brightness = 30,
	castShadow = true,
	particleSystem = "prison_ceiling_lamp",
	placement = "floor",
	editorIcon = 88,
}

defineObject{
	name = "msy_town_wall_quartersize",
	class = "Door",
	model = "mod_assets/models/msy_town_wall_quartersize.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}


defineObject{
	name = "msy_town_pillar_quartersize",
	class = "Decoration",
	model = "mod_assets/models/msy_town_pillar_quartersize.fbx",
	placement = "pillar",
	editorIcon = 108,
}


defineObject{
	name = "airship",
	class = "Decoration",
	model = "mod_assets/models/airship.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "fountain",
	class = "Blockage",
	model = "mod_assets/models/fountain.fbx",
	placement = "floor",
	editorIcon = 52,
}



defineObject{
	name = "npc_barbarian",
	class = "Blockage",
	model = "mod_assets/models/testbar.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "npc_samurai",
	class = "Blockage",
	model = "mod_assets/models/samurai.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "npc_cook",
	class = "Blockage",
	model = "mod_assets/models/npc_cook.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "npc_diz",
	class = "Altar",
	model = "mod_assets/models/diz_hug2.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "wolf",
	class = "Altar",
	model = "mod_assets/models/wolf.fbx",
	placement = "floor",
	editorIcon = 52,
}
defineObject{
	name = "poster_bed",
	class = "Altar",
	model = "mod_assets/models/poster_bed.fbx",
	placement = "floor",
	editorIcon = 52,
}


--Wiz

defineObject{
	name = "npc_wiz",
	class = "Altar",
	model = "mod_assets/models/wiz.fbx",
	placement = "floor",
	editorIcon = 52,
	}



--Primal Beast
defineObject{
	name = "npc_primal",
	class = "Altar",
	model = "mod_assets/models/PrimalBeast.fbx",
	placement = "floor",
	editorIcon = 52,
	}




--DESK
defineObject{
	name = "house",
	class = "Altar",
	model = "mod_assets/models/house.fbx",
	placement = "floor",
	editorIcon = 52,
	}


--Cathedral
defineObject{
	name = "cathedral",
	class = "Altar",
	model = "mod_assets/models/cathedral.fbx",
	placement = "floor",
	editorIcon = 52,
	}

--DESK
defineObject{
	name = "desk",
	class = "Altar",
	model = "mod_assets/models/Desk.fbx",
	placement = "floor",
	editorIcon = 52,
	}

--Horse
defineObject{
	name = "horse",
	class = "Altar",
	model = "mod_assets/models/horse.fbx",
	placement = "floor",
	editorIcon = 52,
	}



--INDOOR DOOR
defineObject{
	name = "indoor_door_wooden",
	class = "Door",
	model = "assets/models/env/door_wooden.fbx",
	doorFrameModel = "assets/models/env/prison_door_frame.fbx",
	pullChainModel = "assets/models/env/door_pullchain.fbx",
	pullChainAnim = "assets/animations/env/door_pullchain.fbx",
	openSound = "gate_open",
	closeSound = "gate_close",
	lockSound = "gate_lock",
	killPillars = true,
	openVelocity = 1.3,
	closeVelocity = 0,
	closeAcceleration = -10,
	placement = "wall",
	editorIcon = 128,
}



--COZY DUNGEONS
defineObject{
	name = "temple_bookshelf_01",
	class = "Decoration",
	model = "mod_assets/models/TempleBookShelf01.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}

defineObject{
	name = "temple_bookshelf_02",
	class = "Decoration",
	model = "mod_assets/models/TempleBookShelf02.fbx",
	placement = "wall",
	replacesWall = true,
	editorIcon = 92,
}

defineObject{
	name = "temple_bookshelf_alcove",
	class = "Alcove",
	model = "mod_assets/models/TempleBookShelfAlcove.fbx",
	placement = "wall",
	replacesWall = true,
	anchorPos = vec(0, 0.62, 0.17),
	targetPos = vec(0, 1.3, 0),
	targetSize = vec(1.2, 0.8, 0.6),
	editorIcon = 8,
}

defineObject{
	name = "table_chairs",
	class = "Decoration",
	model = "mod_assets/models/TableChairs.fbx",
	placement = "floor",
	replacesFloor = false,
	editorIcon = 136,
}

defineObject{
	name = "table_chairs_cushion",
	class = "Decoration",
	model = "mod_assets/models/TableChairsCushion.fbx",
	placement = "floor",
	replacesFloor = false,
	editorIcon = 136,
}

defineObject{
	name = "dishes_01",
	class = "Decoration",
	model = "mod_assets/models/TableDishes.fbx",
	placement = "floor",
	replacesFloor = false,
	editorIcon = 136,
}

defineObject{
	name = "table_altar",
	class = "Altar",
	model = "mod_assets/models/Table.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "table_blockage",
	class = "Blockage",
	model = "mod_assets/models/Table.fbx",
	placement = "floor",
	repelProjectiles = true,
	hitSound = "impact_blade",
	editorIcon = 56,
}

-- GOBELINS

defineObject{
	name = "gobelin_green",
	class = "WallTapestry",
	model = "mod_assets/lol_gobelins/models/env/gobelin_green.fbx",
	brokenModel = "mod_assets/lol_gobelins/models/env/gobelin_green_torn.fbx",
	placement = "wall",
	editorIcon = 92,
}

defineObject{
	name = "gobelin_crimson",
	class = "WallTapestry",
	model = "mod_assets/lol_gobelins/models/env/gobelin_crimson.fbx",
	brokenModel = "mod_assets/lol_gobelins/models/env/gobelin_crimson_torn.fbx",
	placement = "wall",
	editorIcon = 92,
}

defineObject{
	name = "gobelin_blue",
	class = "WallTapestry",
	model = "mod_assets/lol_gobelins/models/env/gobelin_blue.fbx",
	brokenModel = "mod_assets/lol_gobelins/models/env/gobelin_blue_torn.fbx",
	placement = "wall",
	editorIcon = 92,
}

defineObject{
	name = "gobelin_unicorns",
	class = "WallTapestry",
	model = "mod_assets/lol_gobelins/models/env/gobelin_unicorns.fbx",
	brokenModel = "mod_assets/lol_gobelins/models/env/gobelin_unicorns_torn.fbx",
	placement = "wall",
	editorIcon = 92,
}

