-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom dungeon object definitions here

defineObject{
	name = "npc_alma",
	class = "Blockage",
	model = "mod_assets/models/alma2.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "guillotine",
	class = "Blockage",
	model = "mod_assets/models/gillotine.fbx",
	placement = "floor",
	editorIcon = 52,
}



defineObject{
	name = "npc_barbarian",
	class = "Blockage",
	model = "mod_assets/models/testbar.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "npc_cook",
	class = "Blockage",
	model = "mod_assets/models/npc_cook.fbx",
	placement = "floor",
	editorIcon = 52,
}


defineObject{
	name = "npc_diz",
	class = "Altar",
	model = "mod_assets/models/diz.fbx",
	placement = "floor",
	editorIcon = 52,
}
defineObject{
	name = "throne",
	class = "Altar",
	model = "mod_assets/models/duke_throne.fbx",
	placement = "wall",
	replacesWall = false,

	editorIcon = 52,
}


defineObject{
	name = "npc_diz_bow",
	class = "Altar",
	model = "mod_assets/models/diz_bow.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "wolf",
	class = "Altar",
	model = "mod_assets/models/wolf.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "npc_diz_hug",
	class = "Altar",
	model = "mod_assets/models/diz_hug2.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "poster_bed",
	class = "Altar",
	model = "mod_assets/models/poster_bed.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "npc_ranger",
	class = "Altar",
	model = "mod_assets/models/ranger.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "npc_spidey",
	class = "Altar",
	model = "mod_assets/models/spidey.fbx",
	placement = "floor",
	editorIcon = 52,
}



defineObject{
	name = "ivy_statue",
	class = "Altar",
	model = "mod_assets/models/statue.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "jet",
	class = "Altar",
	model = "mod_assets/models/Jet.fbx",
	placement = "floor",
	editorIcon = 52,
}




