-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom wall set definitions here

defineWallSet{
	name = "temple",
	randomFloorFacing = true,

	floors = {
		"assets/models/env/temple_floor_01.fbx", 30,
		--"assets/models/env/temple_floor_drainage.fbx", 1,
	},
	
	walls = {
		"assets/models/env/temple_wall_01.fbx", 50,
		"assets/models/env/temple_wall_drainage.fbx", 1,
	},
	
	pillars = {
		"assets/models/env/temple_pillar.fbx", 1,
	},
	
	ceilings = {
		"assets/models/env/temple_ceiling.fbx", 1,
	},
	
	ceilingShafts = {
		"assets/models/env/temple_ceiling_pit.fbx", 1,
	},
	
	floorDecorations = {
	},
	
	wallDecorations = {
		"assets/models/env/metal_hooks_wall.fbx", 1,
		"assets/models/env/metal_hooks_chain_wall.fbx", 1,
	},
	
	pillarDecorations = {
		"assets/models/env/metal_hook_pillar.fbx", 1,
		"assets/models/env/metal_hook_chain_pillar.fbx", 1,
		"assets/models/env/metal_ring_pillar.fbx", 1,
	},
}