-- This file has been generated by Dungeon Editor 1.3.6

-- import standard assets
import "assets/scripts/standard_assets.lua"                                                                                     
import "mod_assets/grimwidgets/grimwidgets.lua"

-- import custom assets
import "mod_assets/scripts/items.lua"
import "mod_assets/scripts/monsters.lua"
import "mod_assets/scripts/objects.lua"
import "mod_assets/scripts/wall_sets.lua"
import "mod_assets/scripts/recipes.lua"
import "mod_assets/scripts/spells.lua"
import "mod_assets/scripts/materials.lua"
import "mod_assets/scripts/sounds.lua"
import "mod_assets/sx_towntileset/scripts/sx_towntileset.lua"
import "mod_assets/sx_autumn_forest/scripts/sx_autumn_forest_tileset.lua"
import "mod_assets/grim_bed/grim_bed.lua"
import "mod_assets/scripts/flooded_dungeon.lua"