-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom item definitions here

cloneObject{
		name = "message",
		baseObject = "scroll",	
		uiName = "Message from Agent",
		description = "Sealed. You need deliver this to Thief Guild safely.",
}


cloneObject{
		name = "quest2note1",
		baseObject = "note",	
		uiName = "Note from Agen",
		description = "Sir Unknown, I have the message ! Will be waiting for you near the Graveyard. Come asap. Agent Snail.",
}


cloneObject{
		name = "tailor_key",
		baseObject = "iron_key",	
		uiName = "Tailors Key",
		description = "Key from Tailors shop.",
}

cloneObject{
		name = "green_smaragd",
		baseObject = "green_gem",	
		uiName = "Green Smaragd",
		description = "This is what Thieves Guild want.",
}