-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom material definitions here
defineMaterial{
	name = "MineGround",
	diffuseMap = "mod_assets/textures/MineGround_dif.tga",
	specularMap = "mod_assets/textures/MineGround_spec.tga",
	normalMap = "mod_assets/textures/MineGround_normal.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 40,
	depthBias = 0,
}

-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom material definitions here

defineMaterial{
	name = "duke throne",

	diffuseMap = "mod_assets/textures/duke_throne_d.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "gillotine",

	diffuseMap = "mod_assets/textures/gillotine.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -1.8,

	depthBias = 0,

}


defineMaterial{
	name = "barb_f_body",

	diffuseMap = "mod_assets/textures/barb.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "poster_bed",

	diffuseMap = "mod_assets/textures/poster_bed_d.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "witchman",

	diffuseMap = "mod_assets/textures/witchman.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}


defineMaterial{
	name = "diz1",

	diffuseMap = "mod_assets/textures/diz1.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "alma",

	diffuseMap = "mod_assets/textures/Alma_d.tga",
	normalMap = "mod_assets/textures/Alma_n.tga",
	specularMap = "mod_assets/textures/Alma_s.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "ranger_body",

	diffuseMap = "mod_assets/textures/body_d.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "ranger_legs",

	diffuseMap = "mod_assets/textures/cloth_d.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}


defineMaterial{
	name = "ranger_head",

	diffuseMap = "mod_assets/textures/face_d.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2.5,

	depthBias = 0,

}

defineMaterial{
	name = "ranger_body",

	diffuseMap = "mod_assets/textures/body_d.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "ranger_cape",

	diffuseMap = "mod_assets/textures/cape_d.tga",
	specularMap = "mod_assets/textures/cape_s.tga",
	normalMap = "mod_assets/textures/cape_n.tga",





	

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "witchman",

	diffuseMap = "mod_assets/textures/witchman.tga",

	

	doubleSided = false,

	lighting = true,

	alphaTest = false,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}


defineMaterial{
	name = "bigdoor",

	diffuseMap = "mod_assets/textures/bigdoordiff.tga",
	normalMap = "mod_assets/textures/bigdoornormal.tga",
	specularMap = "mod_assets/textures/bigdoorspec.tga",
	

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "ivy_statue",

	diffuseMap = "mod_assets/textures/statue_d.tga",
	normalMap = "mod_assets/textures/statue_n.tga",
	specularMap = "mod_assets/textures/statue_s.tga",
	

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "cook_clothes",

	diffuseMap = "mod_assets/textures/cook_clothes_D.tga",
	normalMap = "mod_assets/textures/additional_cloth_normal.tga",
		

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "cook_eye",

	diffuseMap = "mod_assets/textures/cook_eye_D.tga",
	specularMap = "mod_assets/textures/cook_eye_S.tga",
		

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "cook_hand",

	diffuseMap = "mod_assets/textures/cook_hand_D.tga",
		

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "cook_head",

	diffuseMap = "mod_assets/textures/cook_head_D.tga",
	normalMap = "mod_assets/textures/cook_head_N.tga",
normalMap = "mod_assets/textures/additional_head_normal.tga",
		

	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "wolf",

	diffuseMap = "mod_assets/textures/wolf.tga",
	
	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "spidey_body",

	diffuseMap = "mod_assets/textures/spiderman_body_d.tga",
	
	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "spidey_belt",

	diffuseMap = "mod_assets/textures/spiderman_belt_d.tga",
	
	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "YF12N",

	diffuseMap = "mod_assets/textures/YF-12A_N.tga",
	
	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}
defineMaterial{
	name = "YF12",

	diffuseMap = "mod_assets/textures/YF-12A_P01.tga",
	
	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}

defineMaterial{
	name = "cockpitglass",

	diffuseMap = "mod_assets/textures/Glass_Cockpit.tga",
	
	doubleSided = false,

	lighting = true,

	alphaTest = true,

	blendMode = "Opaque",

	textureAddressMode = "Wrap",

	glossiness = -2,

	depthBias = 0,

}











