-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom monster definitions here

cloneObject{
name = "snail_agent",
baseObject = "snail",
exp = 200,
health = 150,
sight = 4,
attackPower = 20,
movementCoolDown = 2,
exp = 200,

onDie = function(self)
key = spawn("message", self.level, self.x, self.y, self.facing)

hudPrint(" You have killed agent Snail ")
end,

}