-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom dungeon object definitions here
defineObject{
	name = "mine_floor_basic",
	class = "Decoration",
	model = "mod_assets/models/MineFloor04.fbx",
	placement = "floor",
	replacesFloor = true,
	editorIcon = 136,
}

defineObject{
	name = "npc_alma",
	class = "Blockage",
	model = "mod_assets/models/alma2.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "guillotine",
	class = "Blockage",
	model = "mod_assets/models/gillotine.fbx",
	placement = "floor",
	editorIcon = 52,
}



defineObject{
	name = "npc_barbarian",
	class = "Blockage",
	model = "mod_assets/models/testbar.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "npc_cook",
	class = "Blockage",
	model = "mod_assets/models/npc_cook.fbx",
	placement = "floor",
	editorIcon = 52,
}


defineObject{
	name = "npc_diz",
	class = "Altar",
	model = "mod_assets/models/diz.fbx",
	placement = "floor",
	editorIcon = 52,
}
defineObject{
	name = "throne",
	class = "Altar",
	model = "mod_assets/models/duke_throne.fbx",
	placement = "wall",
	replacesWall = false,

	editorIcon = 52,
}


defineObject{
	name = "npc_diz_bow",
	class = "Altar",
	model = "mod_assets/models/diz_bow.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "wolf",
	class = "Altar",
	model = "mod_assets/models/wolf.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "npc_diz_hug",
	class = "Altar",
	model = "mod_assets/models/diz_hug2.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "poster_bed",
	class = "Altar",
	model = "mod_assets/models/poster_bed.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "npc_ranger",
	class = "Altar",
	model = "mod_assets/models/ranger.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "npc_spidey",
	class = "Altar",
	model = "mod_assets/models/spidey.fbx",
	placement = "floor",
	editorIcon = 52,
}



defineObject{
	name = "ivy_statue",
	class = "Altar",
	model = "mod_assets/models/statue.fbx",
	placement = "floor",
	editorIcon = 52,
}

defineObject{
	name = "jet",
	class = "Altar",
	model = "mod_assets/models/Jet.fbx",
	placement = "floor",
	editorIcon = 52,
}

---------------------------------   TOMBSTONES
defineObject{
    name = "ast_tombstone_marble_curved",
    class = "Decoration",
    model = "mod_assets/models/ast_tombstone_curved.fbx",
    placement = "floor",
    replacesWall = true,
	editorIcon = 8,
}

defineObject{
    name = "ast_tombstone_obsidian_curved",
    class = "Decoration",
    model = "mod_assets/models/ast_obsidian_tombstone_curved.fbx",
    placement = "floor",
    replacesWall = true,
	editorIcon = 8,
}


defineObject{
    name = "ast_tombstone_marble_square",
    class = "Decoration",
    model = "mod_assets/models/ast_tombstone_square.fbx",
    placement = "floor",
    replacesWall = true,
	editorIcon = 8,
}

defineObject{
    name = "ast_tombstone_obsidian_square",
    class = "Decoration",
    model = "mod_assets/models/ast_obsidian_tombstone_square.fbx",
    placement = "floor",
    replacesWall = true,
	editorIcon = 8,
}

defineObject{
    name = "ast_tombstone_broken",
    class = "Decoration",
    model = "mod_assets/models/ast_tombstone_broken.fbx",
    placement = "floor",
    replacesWall = true,
	editorIcon = 8,
}

defineObject{
	name = "ast_rusty_cage",
	class = "Blockage",
	model = "mod_assets/models/ast_rusty_cage.fbx",
        brokenModel = "assets/models/env/barrel_crate_block_broken.fbx",
	placement = "floor",
	editorIcon = 100,
	hitSound = "impact_blade",
}
-----------------------
defineObject{
	name = "cityfog",
	class = "LightSource",
	lightPosition = vec(0, 0, 0),
	lightRange = 0,
	lightColor = vec(2.55, 2.55, 2.55),
	brightness = 12,
	castShadow = true,
	particleSystem = "cityfog",
	placement = "floor",
	editorIcon = 88,
}

defineObject{
	name = "msy_town_wall_quartersize",
	class = "Door",
	model = "mod_assets/models/msy_town_wall_quartersize.fbx",
	openSound = "wall_sliding",
	closeSound = "wall_sliding",
	lockSound = "wall_sliding_lock",
	openVelocity = 0.5,
	closeVelocity = -0.5,
	secretDoor = true,
	placement = "wall",
	editorIcon = 120,
}