-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom sound definitions here
defineSound{
   name = "dog",
   filename = "mod_assets/sounds/dog.wav",
   loop = false,
   volume = 2,
   minDistance = 6,
   maxDistance = 12,
}

defineSound{
   name = "thunder",
   filename = "mod_assets/sounds/thunder.wav",
   loop = false,
   volume = 2,
   minDistance = 6,
   maxDistance = 12,
}

defineSound{
   name = "walk",
   filename = "mod_assets/sounds/walk.wav",
   loop = false,
   volume = 2,
   minDistance = 6,
   maxDistance = 12,
}


defineSound{
   name = "snore",
   filename = "mod_assets/sounds/snore.wav",
   loop = true,
   volume = 2,
   minDistance = 1,
   maxDistance = 3,
}

defineSound{
   name = "sx_stream",
   filename = "mod_assets/sounds/sx_stream.wav",
   loop = true,
   volume = 2,
   minDistance = 1,
   maxDistance = 3,
}