-- This file has been generated by Dungeon Editor 1.3.6

--- level 1 ---

mapName("Unnamed")
setWallSet("dungeon")
playStream("assets/samples/music/dungeon_ambient.ogg")
mapDesc([[
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
############.#.....#############
##############.....#############
############.......#############
############.......#############
############.......#############
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
]])
spawn("starting_location", 15,17,3, "starting_location")
spawn("torch_holder", 15,14,0, "torch_holder_1")
	:addTorch()
spawn("healing_crystal_green", 12,16,2, "healing_crystal_green_1")
	:setSource("")
spawn("script_entity", 12,11,0, "crystalHandler")
	:setSource("crystalObjects = {}\
\
-- *****************************************************************************************\
--                                    CRYSTAL FUNCTIONS\
-- *****************************************************************************************\
\
function createCrystals()\
\
\9for level = 1, getMaxLevels() do\
\
\9\9for x = 0,31 do\
\9\9\9\
\9\9\9for y = 0,31 do\
\9\9\9\9\
\9\9\9\9for i in entitiesAt(level, x, y) do\
\9\9\9\9\9\
\9\9\9\9\9if i.name == \"healing_crystal_green\" then\
\9\9\9\9\9\9\
\9\9\9\9\9\9-- Create crystal script object\
\9\9\9\9\9\9crystalObjects[i.id] = {}\
\9\9\9\9\9\9local crystal = crystalObjects[i.id]\
\9\9\9\9\9\9crystal.id = i.id\
\9\9\9\9\9\9\
\9\9\9\9\9\9-- Set it to active\
\9\9\9\9\9\9crystal.active = true\
\9\9\9\9\9\9\
\9\9\9\9\9\9-- Spawn projectiles and register IDs\
\9\9\9\9\9\9crystal.main = shootProjectileWithId(\"_healing_crystal_green_main\",level,x,y,0,0,0,0,0,14,0,0,party,true)\
\9\9\9\9\9\9crystal.small = shootProjectileWithId(\"_healing_crystal_green_small\",level,x,y,0,0,0,0,0,14,0,0,party,true)\
\9\9\9\9\9\9crystal.mainAdditive = shootProjectileWithId(\"_healing_crystal_green_main_additive\",level,x,y,0,0,0,0,0,14,0,0,party,true)\
\9\9\9\9\9\9\
\9\9\9\9\9\9-- Spawn lights & particles and register IDs\
\9\9\9\9\9\9for j = 0,3 do\
\9\9\9\9\9\9\9spawn(\"_healing_crystal_green_light\", level, x, y, j, crystal.id..\"_light_\"..j)\
\9\9\9\9\9\9end\
\9\9\9\9\9\9spawn(\"_healing_crystal_green_particleSystem\", level, x, y, 0, crystal.id..\"_particleSystem\")\
\9\9\9\9\9\9\
\9\9\9\9\9\9-- Spawn altar and fake item\
\9\9\9\9\9\9spawn(\"_healing_crystal_altar\", level, x, y, 0, crystal.id..\"_altar\")\
\9\9\9\9\9\9\9:addItem(spawn(\"_healing_crystal_fake_item\"))\
\9\9\9\9\9\9\9:addConnector(\"deactivate\", \"crystalHandler\", \"activateCrystal\")\
\9\9\9\9\9\9\
\9\9\9\9\9end\
\9\9\9\9\
\9\9\9\9end\
\9\9\9\
\9\9\9end\
\9\9\
\9\9end\
\9\
\9end\
end\
\
function activateCrystal(altar)\
\9\
\9setMouseItem(nil)\
\9altar:addItem(spawn(\"_healing_crystal_fake_item\"))\
\9party:heal()\
\9\
end\
\
-- *****************************************************************************************\
--                                    HELPER FUNCTIONS\
-- *****************************************************************************************\
\
function shootProjectileWithId(projName,level,x,y,dir,speed,gravity,velocityUp,offsetX,offsetY,offsetZ,attackPower, ignoreEntity,fragile,championOrdinal)\
\9local pIds = {}\
\9for i in entitiesAt(level, x, y) do\
\9\9if i.class == \"Item\" and string.find(i.id, \"^%d+$\") then\
\9\9\9pIds[i.id] = i.name\
\9\9end\
\9end\
\9shootProjectile(projName,level,x,y,dir,speed,gravity,velocityUp,offsetX,offsetY,offsetZ,attackPower, ignoreEntity,fragile,championOrdinal)\
 \9for i in entitiesAt(level, x, y) do\
\9\9if i.class == \"Item\" and string.find(i.id, \"^%d+$\") and not(pIds[i.id]) then\
\9\9\9return i.id\
\9\9end\
\9end  \
end\
\
-- *****************************************************************************************\
--                                           INIT\
-- *****************************************************************************************\
\
createCrystals()\
\
")
spawn("healing_crystal", 12,18,0, "healing_crystal_1")
