-- This file has been generated by Dungeon Editor 1.3.6

--- level 1 ---

mapName("Unnamed")
setWallSet("dungeon")
playStream("assets/samples/music/dungeon_ambient.ogg")
mapDesc([[
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
############.#.....#############
##############.....#############
############.......#############
############.......#############
############.......#############
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
]])
spawn("starting_location", 15,17,3, "starting_location")
spawn("torch_holder", 15,14,0, "torch_holder_1")
	:addTorch()
spawn("healing_crystal_green", 12,16,2, "healing_crystal_green_1")
	:setSource("")
spawn("script_entity", 13,11,0, "crystalHandler")
	:setSource("crystalObjects = {}\
\
-- *****************************************************************************************\
--                                    CRYSTAL FUNCTIONS\
-- *****************************************************************************************\
\
function createCrystals()\
\
\9for level = 1, getMaxLevels() do\
\
\9\9for x = 0,31 do\
\9\9\9\
\9\9\9for y = 0,31 do\
\9\9\9\9\
\9\9\9\9for i in entitiesAt(level, x, y) do\
\9\9\9\9\9\
\9\9\9\9\9if i.name == \"healing_crystal_green\" then\
\9\9\9\9\9\9\
\9\9\9\9\9\9-- Create crystal lua object\
\9\9\9\9\9\9crystalObjects[i.id] = {}\
\9\9\9\9\9\9local crystal = crystalObjects[i.id]\
\9\9\9\9\9\9crystal.id = i.id\
\9\9\9\9\9\9crystal.level = i.level\
\9\9\9\9\9\9crystal.x = i.x\
\9\9\9\9\9\9crystal.y = i.y\
\9\9\9\9\9\9\
\9\9\9\9\9\9-- Set it to active\
\9\9\9\9\9\9crystal.active = true\
\9\9\9\9\9\9\
\9\9\9\9\9\9-- Spawn active state projectiles and register IDs\
\9\9\9\9\9\9crystal.main = shootProjectileWithId(\"_healing_crystal_green_main\",level,x,y,0,0,0,0,0,14,0,0,party,true)\
\9\9\9\9\9\9crystal.mainAdditive = shootProjectileWithId(\"_healing_crystal_green_main_additive\",level,x,y,0,0,0,0,0,14,0,0,party,true)\
\9\9\9\9\9\9crystal.small = shootProjectileWithId(\"_healing_crystal_green_small\",level,x,y,0,0,0,0,0,14,0,0,party,true)\
\9\9\9\9\9\9\
\9\9\9\9\9\9-- Spawn lights & particles lightsources\
\9\9\9\9\9\9for j = 0,3 do\
\9\9\9\9\9\9\9spawn(\"_healing_crystal_green_light\", level, x, y, j, crystal.id..\"_light_\"..j)\
\9\9\9\9\9\9\9spawn(\"_healing_crystal_green_light_deactivated\", level, x, y, j, crystal.id..\"_light_deactivated_\"..j):deactivate()\
\9\9\9\9\9\9end\
\9\9\9\9\9\9spawn(\"_healing_crystal_green_particleSystem\", level, x, y, 0, crystal.id..\"_particleSystem\")\
\9\9\9\9\9\9\
\9\9\9\9\9\9-- Spawn altar and fake item\
\9\9\9\9\9\9spawn(\"_healing_crystal_altar\", level, x, y, 0, crystal.id..\"_altar\")\
\9\9\9\9\9\9\9:addItem(spawn(\"_healing_crystal_fake_item\"))\
\9\9\9\9\9\9\9:addConnector(\"deactivate\", \"crystalHandler\", \"useCrystal\")\
\9\9\9\9\9\9\9\
\9\9\9\9\9\9-- Spawn crystal timer\
\9\9\9\9\9\9spawn(\"timer\", level, x, y, 0, crystal.id..\"_timer\")\
\9\9\9\9\9\9\9:setTimerInterval(15)\
\9\9\9\9\9\9\9:addConnector(\"activate\", \"crystalHandler\", \"reactivateCrystal\")\
\9\9\9\9\9\9\
\9\9\9\9\9end\
\9\9\9\9\
\9\9\9\9end\
\9\9\9\
\9\9\9end\
\9\9\
\9\9end\
\9\
\9end\
end\
\
\
function useCrystal(altar)\
\9\
\9-- Respawn item on altar\
\9setMouseItem(nil)\
\9altar:addItem(spawn(\"_healing_crystal_fake_item\"))\
\9\
\9-- Retrieve crystal lua object by extracting its id from the altar id\
\9local crystal = crystalObjects[string.sub(altar.id,0,-7)]\
\9local level, x, y = altar.level, altar.x, altar.y\9\
\9\
\9if crystal.active then\
\9\
\9\9-- Heal Party\
\9\9party:heal()\
\9\9\
\9\9-- Turn off activated state lights and turn on deactivated state lights\
\9\9for i = 0,3 do\
\9\9\9findEntity(crystal.id..\"_light_\"..i):deactivate()\
\9\9\9findEntity(crystal.id..\"_light_deactivated_\"..i):activate()\
\9\9end\
\9\9\
\9\9-- Turn off particle system\
\9\9findEntity(crystal.id..\"_particleSystem\"):deactivate()\
\9\9\
\9\9-- Destroy activated state projectiles\
\9\9findEntity(crystal.main):destroy()\
\9\9findEntity(crystal.mainAdditive):destroy()\
\9\9findEntity(crystal.small):destroy()\
\9\9\
\9\9-- Spawn deactivated state projectiles and register IDs\
\9\9crystal.main = shootProjectileWithId(\"_healing_crystal_green_main_deactivated\",level,x,y,0,0,0,0,0,14,0,0,party,true)\
\9\9crystal.small = shootProjectileWithId(\"_healing_crystal_green_small_deactivated\",level,x,y,0,0,0,0,0,14,0,0,party,true)\
\
\9\9-- Start timer\
\9\9findEntity(crystal.id..\"_timer\"):activate()\
\9\9\
\9\9-- Deactivate crystal\
\9\9crystal.active = false\
\9\
\9end\
\9\
end\
\
\
function reactivateCrystal(timer)\
\
\9-- Retrieve crystal lua object by extracting its id from the timer id\
\9local crystal = crystalObjects[string.sub(timer.id,0,-7)]\
\9local level, x, y = timer.level, timer.x, timer.y\
\9\9\
\9-- Turn off deactivated state lights and turn on activated state lights\
\9for i = 0,3 do\
\9\9findEntity(crystal.id..\"_light_\"..i):activate()\
\9\9findEntity(crystal.id..\"_light_deactivated_\"..i):deactivate()\
\9end\
\9\
\9-- Turn on particle system\
\9findEntity(crystal.id..\"_particleSystem\"):activate()\
\9\
\9-- Destroy deactivated state projectiles\
\9findEntity(crystal.main):destroy()\
\9findEntity(crystal.small):destroy()\
\9\
\9-- Spawn deactivated state projectiles and register IDs\
\9crystal.main = shootProjectileWithId(\"_healing_crystal_green_main\",level,x,y,0,0,0,0,0,14,0,0,party,true)\
\9crystal.mainAdditive = shootProjectileWithId(\"_healing_crystal_green_main_additive\",level,x,y,0,0,0,0,0,14,0,0,party,true)\
\9crystal.small = shootProjectileWithId(\"_healing_crystal_green_small\",level,x,y,0,0,0,0,0,14,0,0,party,true)\
\
\9-- Stop timer\
\9findEntity(crystal.id..\"_timer\"):deactivate()\
\9\
\9-- Reactivate crystal\
\9crystal.active = true\
\9\
end\
\
-- *****************************************************************************************\
--                                    HELPER FUNCTIONS\
-- *****************************************************************************************\
\
function shootProjectileWithId(projName,level,x,y,dir,speed,gravity,velocityUp,offsetX,offsetY,offsetZ,attackPower, ignoreEntity,fragile,championOrdinal)\
\9local pIds = {}\
\9\
\9for i in entitiesAt(level, x, y) do\
\9\9if i.class == \"Item\" and string.find(i.id, \"^%d+$\") then\
\9\9\9pIds[i.id] = i.name\
\9\9end\
\9end\
\9\
\9shootProjectile(projName,level,x,y,dir,speed,gravity,velocityUp,offsetX,offsetY,offsetZ,attackPower, ignoreEntity,fragile,championOrdinal)\
 \9\
\9for i in entitiesAt(level, x, y) do\
\9\9if i.class == \"Item\" and string.find(i.id, \"^%d+$\") and not(pIds[i.id]) then\
\9\9\9return i.id\
\9\9end\
\9end  \
\
\9end\
\
-- *****************************************************************************************\
--                                           INIT\
-- *****************************************************************************************\
\
createCrystals()\
\
")
spawn("healing_crystal", 12,18,0, "healing_crystal_1")
