-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom item definitions here

cloneObject{
	name = "frost_brigandine",
	baseObject = "leather_brigandine",
	uiName = "Frost Brigandine",
	model = "mod_assets/models/frost_brigandine.fbx",
	slot = "Torso",
	armorSkill = "light_armor",
	armorSet = "frostleather",
	gfxAtlas = "mod_assets/textures/frost_items.tga",
	gfxIndex = 0,
	protection = 4,
	resistCold = 10,
	weight = 8.0,
}