-- This file has been generated by Dungeon Editor 1.3.6

-- TODO: place your custom material definitions here

defineMaterial{
	name = "frost_brigandine",
	diffuseMap = "mod_assets/textures/frost_brigandine_dif.tga",
	specularMap = "assets/textures/items/leather_brigandine_spec.tga",
	doubleSided = false,
	lighting = true,
	alphaTest = false,
	blendMode = "Opaque",
	textureAddressMode = "Wrap",
	glossiness = 20,
	depthBias = 0,
}